### ISSUE TITLE
BUG: Cannot connect because my db server doesnt have a postgres user

### ISSUE THREAD

**Issue by yawhide** [dbgate/dbgate#102]
**Describe the bug**
Hello, there is no way to provide a default database name so the program seems to use `progres`. My db server doessnt have a postgres user and I cannot connect to my postgres instance.

**To Reproduce**
1. Create a db server that does not have a `postres` database
2. Try to connect to it
3. You will get an error saying `postgres database does not exist`

**Expected behavior**
I should be able to connect to the server without a database OR provide a textbox in the connection dialogue to allow me to add a database.

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 4.1.9
 - Install source: installer
 - Type - Application
 - Database engine: PostgreSQL

**Additional context**

Thanks

**Comment by janproch** [comment]
the same problem as #96. Will be solved with #92
