### ISSUE TITLE
Can we add it to chocolatey?

### ISSUE THREAD

**Issue by frederikhors** [dbgate/dbgate#107]
Can we add it to [chocolatey](https://chocolatey.org/)?

**Comment by janproch** [comment]
Yes, sure, it will be great

**Comment by janproch** [comment]
If anybody could do this, I will appreciate it

**Comment by sriramjiyer** [comment]
Not exactly what is asked, but a config file for [scoop.sh](https://scoop.sh/) which is another windows software manager like chocolatey.

[DbGate.zip](https://github.com/dbgate/dbgate/files/7123780/DbGate.zip)

Download the file, unzip and install using command

`scoop install <path>/DbGate.json`

It is also available in a scoop bucket https://github.com/sriramjiyer/MyScoopBucket.git

**Comment by atwright147** [comment]
And brew for Mac :)

**Comment by janproch** [comment]
Created new issue #234, closing this
