### ISSUE TITLE
BUG: Error clicking on "All Tables" button in Import/Export view

### ISSUE THREAD

**Issue by luisxkimo** [dbgate/dbgate#109]
**Describe the bug**
When click on "All Tables" button in the Import/Export view for a specific database, an error popup appears.

**To Reproduce**
1. Open list of databases in tree of connection
2. Right click on one of them
3. Select "Export" option
4. Fill fields like in attached screenshot
5. Click on "All Tables" button to select all before run exportation

**Expected behavior**
Backup of all tables is generated

**Screenshots**
1.
![popup](https://user-images.githubusercontent.com/6990299/116566029-ac447e80-a906-11eb-8b14-fb21666e1f1d.png)
2.
![STATUS](https://user-images.githubusercontent.com/6990299/116566018-a9498e00-a906-11eb-9431-a8d7c0946ba1.png)
3.
![code](https://user-images.githubusercontent.com/6990299/116566041-aea6d880-a906-11eb-87bc-230ab3fda0c4.png)
4.
![console-error](https://user-images.githubusercontent.com/6990299/116566069-b49cb980-a906-11eb-8656-4ac20990c594.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version

![image](https://user-images.githubusercontent.com/6990299/116566363-fb8aaf00-a906-11eb-9caa-689c3962da7d.png)

 - Install source: Docker
 - Type - Web
 - Database engine: SQL Server

**Additional context**
Total number of tables on database could be more or less 243

**Comment by janproch** [comment]
Thank you for reporting. This issue should be fixed in newest BETA version. Number of tables (~250) should not be problem.

**Comment by janproch** [comment]
fixed in version 4.1.11. In case of problems please let me know. Closing for now

**Comment by luisxkimo** [comment]
Thanks so much for the info and fix @janproch 👍 💯
