### ISSUE TITLE
Unable to connect to DBs (over SSH tunnel) until connection is tested

### ISSUE THREAD

**Issue by greenskeleton** [dbgate/dbgate#110]
**Describe the bug**
Connecting to various database types over SSH tunnel hang indefinitely, unless I first edit the connection and test. Once the test proves successful, I am able to use DBGate for this connections resources. The test must be performed on each connection, or that connection will hang.

**To Reproduce**
1. Open DBGate with pre-configured MariaDB and MS SQL connections, using SSH tunnel with keyfile
2. Click on connection name in Connections pane
3. Tables, Views, and Functions displays 'Loading database structure' and spins indefinitely, 'Loading' in status bar. No reasonable amount of time seems to allow this to correct itself.
4. Close DBGate
5. Re-open DBGate
6. Right click on connection name in Connections pane, click edit
7. Click Test, green check indicates success almost immediately
7. Close connection window
8. Click on connection name in Connections pane
9. _Immediately_, Tables, Views, and Functions displays expected list, connection shows green check in status bar

**Expected behavior**
Upon opening DBGate, clicking on the connection name should connect as quickly as the test in the connection configuration.

**Screenshots**
Main window connection hanging:
![image](https://user-images.githubusercontent.com/526130/116909468-401d8f80-ac12-11eb-8cc5-7ae67107c48b.png)
Connection config test hanging:
![image](https://user-images.githubusercontent.com/526130/116909514-4f044200-ac12-11eb-804d-4b47cc3a541f.png)
Connection config test success:
![image](https://user-images.githubusercontent.com/526130/116909615-74914b80-ac12-11eb-879d-9a12c9a19191.png)
Main window connection success:
![image](https://user-images.githubusercontent.com/526130/116909700-94c10a80-ac12-11eb-9f49-b6e890e96a2b.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - App Version: 4.1.11
 - Install source: deb
 - Type - Web/Application
 - Database engine: MariaDB and SQL Server

**Additional context**
Both DB connections are using a keyfile SSH tunnel. After the connection is stuck in a loading state, the connection test no longer works.

**Comment by janproch** [comment]
Thanks very much! I have succesfully reproduced this error, I will fix it with highest priority, it seems be to serious problem for all SSH tunnel connections.

**Comment by janproch** [comment]
Should be fixed in newest BETA version. If no problems will occur, it will be released tomorow as hotfix release.

**Comment by greenskeleton** [comment]
I can confirm this issue appears to be resolved for me in 4.1.12-beta.2. Thanks!

**Comment by janproch** [comment]
Fixed in 4.1.12
