### ISSUE TITLE
FEAT: CockroachDB support

### ISSUE THREAD

**Issue by mholt** [dbgate/dbgate#112]
**Is your feature request related to a problem? Please describe.**

I can't use DBgate since I use CockroachDB.

**Describe the solution you'd like**

A CockroachDB driver plugin.

**Describe alternatives you've considered**

Using DBeaver in the meantime.

**Additional context**

[CockroachDB is similar to PostgreSQL](https://www.cockroachlabs.com/docs/v20.2/postgresql-compatibility.html), but with a few differences that make it incompatible with the Postgres plugin. For example, when selecting a DB in DBgate after connecting to a Cockroach server, I get an error "Unknown function: format()".

This program looks very promising and I'm excited to use it! As soon as it supports Cockroach.

**Comment by janproch** [comment]
Thanks for the suggestion. I am adding this to nearest milestone, it seems to be no problem in implementing this

**Comment by mholt** [comment]
Awesome! I hope it is as easy as I think it might be. 🤞  If I used any other DB, I'd probably already be using DBgate -- great work, I found it on HN and I think you deserve all the positive feedback it got. :+1:

**Comment by janproch** [comment]
Added in version 4.2.0

**Comment by mholt** [comment]
Very nice, thank you! So far it works like a charm.
