### ISSUE TITLE
FEAT: Horizontal scrolling with Shift + mouse wheel

### ISSUE THREAD

**Issue by aeno** [dbgate/dbgate#113]
**Is your feature request related to a problem? Please describe.**
When editing tables with many columns, I have to click and drag the horizontal scrollbar to access the rightmost columns.

**Describe the solution you'd like**
I'd like to be able to scroll horizontically by holding `Shift` and scrolling with the mouse wheel.

**Describe alternatives you've considered**
- none -

**Additional context**
Shift + mouse wheel is a widely adopted method for horizontal scrolling.

**Comment by janproch** [comment]
Good idea! Adding to next milestone

**Comment by aeno** [comment]
Looking forward to it! 
by the way, dbgate ist great - it recently became my main DB manager.

**Comment by janproch** [comment]
Added in version 4.2.0
