### ISSUE TITLE
FEAT: Support generating ER Diagrams

### ISSUE THREAD

**Issue by bbkane** [dbgate/dbgate#118]
**Is your feature request related to a problem? Please describe.**

I tend not to touch databases for months, and then come back to them to run ad-hoc queries. ER diagrams help me re-learn the database schema so I can work.

**Describe the solution you'd like**

I'd love it if DbGate could generate ER Diagrams from connected databases. The gold standard for this (imo) is TablePlus. When you generate an ER diagram, TablePlus creates a new window so you can keep the diagram to the side or even on another monitor. See an example TablePlus style diagram at https://diagramplus.com/ or a screenshot below

![image](https://user-images.githubusercontent.com/6081085/118554188-feaed900-b715-11eb-9699-cc53a1a6d527.png)

**Describe alternatives you've considered**

There are some of alternatives:
- looking at the list in the "Columns" window and clicking through the Foreign Keys. This is super helpful, but doesn't give me quite the bird's eye view that I sometimes need.
- Using TablePlus or SchemaSpy to generate ER diagrams. This works, but is more difficult to use.

**Additional context**

I asked this on [HackerNews](https://news.ycombinator.com/item?id=26904609) and you replied so I hope you don't see this as annoying. It just seems GitHub issues are the best place to track feature requests and I didn't see ER diagrams as an issue already, so I'm making this.

**Comment by janproch** [comment]
Thanks for adding this. This is good place to add feature requests, but as I wrote in HN, it has not the biggest priority. I hope ER diagrams could be added in several months.

**Comment by janproch** [comment]
ERD diagrams are implemented in BETA v4.5.2-beta.8 . If no problems will occur, it will be released this week.

**Comment by bbkane** [comment]
Wonderful, thank you!!!

**Comment by janproch** [comment]
released in 4.6.0

**Comment by SoCalDude** [comment]
I have a database with 97 tables. I am unable to find a way to import all the tables at once to a new diagram. Dragging the database name to the empty diagram does nothing. If only I could select more than one table in the tables view and drag them over. Any suggestions?
