### ISSUE TITLE
Why is trying to connect to tracker.ilibr.org

### ISSUE THREAD

**Issue by afzaal-ameer** [dbgate/dbgate#119]
I am running the appimage and it tries to connect to domains like `tracker.ilibr.org` and `tRaCKer.Ds.iS` when starting.

**Comment by janproch** [comment]
What platform are you using?

Could you please share link, which you used to download AppImage?

DbGate has no tracking code inside, only external website, which is contacted, is npmjs.org for plugins, and this is only when opening plugins widget.

**Comment by afzaal-ameer** [comment]
Ubuntu

Downloaded this right before I filed the issue. https://github.com/dbgate/dbgate/releases/latest/download/dbgate-latest.AppImage

**Comment by janproch** [comment]
Do you have some screenshot with this network communication? Something what could help find source of this request.

I tried to analyse start of exactly this AppImage on Ubuntu with Wireshark, and I found only communication with github server, which is correct, it is autoupdate check dispatched by [electron-updater](https://www.npmjs.com/package/electron-updater) package

**Comment by afzaal-ameer** [comment]
I downloaded it again. Extract the appimage. Got a new domain this time.

![image](https://user-images.githubusercontent.com/72922998/118668351-14470000-b7f5-11eb-8e66-a83ab629b1ed.png)

**Comment by afzaal-ameer** [comment]
![image](https://user-images.githubusercontent.com/72922998/118669222-dd251e80-b7f5-11eb-85fc-edf4296860f2.png)

**Comment by janproch** [comment]
I am not network guru, but there is

Source IP: ::1  
Destination IP: ::1  
which is localhost. DbGate starts local HTTP server on random port, GUI communicates with this server. It seems, that somehow OpenSnitch interprets this local server as pirate DNS.

If you start DbGate from console, there is message   
DbGate API listening on port XXXX

Is this port the same, as Dst Port in OpenSnitch message?

**Comment by afzaal-ameer** [comment]
That explains it.

```
; <<>> DiG 9.16.1-Ubuntu <<>> @8.8.8.8 tracker.piratepublic.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9285
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tracker.piratepublic.com.	IN	A

;; ANSWER SECTION:
tracker.piratepublic.com. 10117	IN	CNAME	piratepublic.com.
piratepublic.com.	10781	IN	A	127.0.0.1

;; Query time: 35 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue May 18 18:39:44 CEST 2021
;; MSG SIZE  rcvd: 83

```
