### ISSUE TITLE
BUG: PostgreSQL 12 - All functions "undefined" and then crashing

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#122]
**Describe the bug**
Not showing correct function names in the db explorer. Shortly after, the whole application crashes. Tables and views looks ok.

**To Reproduce**
1. Connect to db
2. Expand Function list
3. See all named undefined

**Expected behavior**
Expects to see the correct function names and not to crash afterwards.

**Screenshots**
![image](https://user-images.githubusercontent.com/10090010/119655995-783b7b00-be2a-11eb-8017-6fc32acdfca9.png)

**Version Information (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - App Version: 4.2.3
 - Install source: Appimage 
 - Type - Application
 - Database engine: PostgreSQL 12.7

 Additional context**
Using some custom db types etc. Don't know if that could lead to this issue.

**Comment by janproch** [comment]
Thanks for reporting. I have replicated this problem in integration test, will be fixed in next release, probably on tueasday 2021-06-01

**Comment by janproch** [comment]
Next release will be postponed, because of problems unveiled by new integration tests. However, fix is available in newest BETA version 4.2.4-beta.2

**Comment by janproch** [comment]
fixed in version 4.2.4
