### ISSUE TITLE
FEAT: Add support for listing PostgreSQL Materialized Views similar to tables/views/functions

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#123]
Would be great to be able to list/view/filter materialized views the same way that you can do for tables/views/functions in the left bottom corner as seen here:
![image](https://user-images.githubusercontent.com/10090010/119965398-831d1980-bfaa-11eb-9f6a-ea9b7d40c3ee.png)

 I'm using mainly PostgreSQL and this query might be some help for this function:

```
	WITH matviews as ( SELECT schemaname || '.' || matviewname AS matviewname,
	definition
	FROM pg_catalog.pg_matviews 
	WHERE schemaname NOT LIKE 'pg_%' 
	)
	SELECT
	matviewname,
	definition,
	COALESCE(string_agg(indexdef, ';' || E'\n\n') || ';', '')  as indexdef
	FROM matviews
	LEFT JOIN  pg_catalog.pg_indexes on matviewname = schemaname || '.' || tablename
	group by matviewname, definition
	ORDER BY
	matviewname;
```

**Comment by janproch** [comment]
Thanks for the suggestion. It seem that support of PostgreSQL materialized views will be added into next release bext week.

**Comment by janproch** [comment]
added in version 4.2.4
