### ISSUE TITLE
FEAT: Support SSH Key in Web Version

### ISSUE THREAD

**Issue by SanketDG** [dbgate/dbgate#124]
**Is your feature request related to a problem? Please describe.**
The "SSH Authorization" mode selection fails on the web.

Relevant code in `packages/web/src/modals/ConnectionModalSshTunnelFields.svelte`:

```
<FormSelectField
  label="SSH Authentication"
  name="sshMode"
  isNative
  disabled={!useSshTunnel}
  options={[
    { value: 'userPassword', label: 'Username & password' },
    { value: 'agent', label: 'SSH agent' },
    electron && { value: 'keyFile', label: 'Key file' },
  ]}
/>
```

**Describe the solution you'd like**
There are two things here:

1. When I launch `dbgate` through the docker version, the "SSH Authorization" dropdown does not open.

2. The `SSH Key` option is not there when I set up the dev environment using `yarn start`

**Comment by janproch** [comment]
SSH authentization should work on web, only there is not possibility to select private key file (now in connection only path to key file is stored, which doesn't have sense in web environment. In case of web, upload of key file should be implemented)

However, if you use configuring connections with environment variables (which I think is most used variant when using docker installation), it is quite easy to define SSH tunnel with keyfile connection - only which is needed is to extend getPortalCollections() implementation to support  sshKeyfile parameter. 

https://github.com/dbgate/dbgate/blob/87efb92f07346cd7c2772dfb29067cd9806802d2/packages/api/src/controllers/connections.js#L37

Let me know, if this could help you, I will add this support. Or feel free to create PR ...

**Comment by SanketDG** [comment]
Sounds good. 

I just think we should visit this again:

> 1. When I launch `dbgate` through the docker version, the "SSH Authorization" dropdown does not open.

Can you launch the docker image and see if the "SSH Authorization" dropdown opens? It does not for me.

**Comment by janproch** [comment]
I replicated this in docker image. But this problem was in older version, updating image before starting container
```sh
docker pull dbgate/dbgate
```
fixed this issue for me

**Comment by janproch** [comment]
It seems solved
