### ISSUE TITLE
BUG: Minimizing function tree only remove a couple of nodes and then crash the app

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#125]
**Describe the bug**
In the left bottom corner, the minimizing/expanding the function list often leads to crashes of the application. It does not happen all the time, but maybe 50% of the time. What happens is that only a couple of functions disappear from the list when collapsing and then I get a popup saying that the app has crashed. I have also gotten this message when refreshing the db. Is there anyway to get the actual crash logs/output so that I can attach them here?

**To Reproduce**
1. Collapse Tables/Views/Materialized Views in the grid.
2. Collaps/Expand the Function list until it crashes.
3. Can also try to refresh db a couple of times in between if it doesn't crash.

**Expected behavior**
Should not crash the application and the function list should be fully collapsed when collapsing it.

**Version Information (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - App Version: dbgate-4.2.4-linux_x86_64.AppImage
 - Install source: AppImage
 - Type - Application
 - Database engine: PostgreSQL 13.3

**Comment by tvarsis** [comment]
@janproch Thanks for your reply! I tested it more now with the latest beta and it still crashes with this error:

![image](https://user-images.githubusercontent.com/10090010/121415867-72848000-c968-11eb-8c37-40c56b1badaf.png)

It doesn't always crash, but most of the time it does. We use multiple schemas like dev and public and more in the db. And what I noticed what that when I try to collapse the function tree, only the nodes from the dev schema are removed  from the list before the crash and all other functions are not collapsed/removed, which might be useful information.

Please let me know if you need any further details or what me to do some more tests!

**Comment by janproch** [comment]
@tvarsis Thank you for report.

Could you please try version 4.2.5-beta.2 https://github.com/dbgate/dbgate/releases/tag/v4.2.5-beta.2 , in this version is should be fixed

It is problem in Svelte, I tried also to upgrade it to newest version, but in Svelte changelog I don't see anything, which seems to solve this problem

But if you could also try 4.2.5-beta.3 https://github.com/dbgate/dbgate/releases/tag/v4.2.5-beta.3 , it will help me. But I guess that the problem will be solved only in 4.2.5-beta.2

**Comment by tvarsis** [comment]
@janproch Thanks for your reply! And I'm impressed about your responsiveness and dedication to this project! Good job!

I tested both beta 2 and 3 now.

Beta 2: It does not crash, but the collapse is not working properly. It only removes some of the functions from the list and not all, and when expanding again, not all functions are coming back. For example, my dev schema functions are removed when collapsing, but are not coming back when expanding. Also public.citext and public.regexp_match functions are not getting removed, but this also applies for some of our own functions so it is not clear to me what is the cause for a function to be able to be removed from the list on collapse or not.. 

Beta 3 it still crashes with the same error as in the screenshot above.

Here is the reference when I click bundle.js link in the error in the initial screenshot if that is any help:
![image](https://user-images.githubusercontent.com/10090010/121496297-9f717b00-c9da-11eb-87bf-b6f76d0a2792.png)

On a side note: What is the expected behavior when clicking on a function in that list? It just opens up a black query editor for me, and the right click menu with Generator Create option, is also not working for me and shows  me only this:
![image](https://user-images.githubusercontent.com/10090010/121497478-c8ded680-c9db-11eb-8129-a50a9ea2b25e.png)

Imo, clicking a function should bring up the full CREATE FUNCTION... code in the query window so it can easily be run or edited.

**Comment by janproch** [comment]
@tvarsis Thanks for your help. This is critical issue, it seems it occurs only on some environments. I didn't never replicate it, although the same problem was already here - https://github.com/dbgate/dbgate/issues/105 )

Could you please try the newest BETA 4 https://github.com/dbgate/dbgate/releases/tag/v4.2.5-beta.4? It is based on BETA2, with one place fixed, which could cause this problem.  
It the problem remains, it is possible to create video with crash, so that I could move forward?

Also obtaining CREATE FUNCTION script from postgre  database is fixed in BETA 4

**Comment by tvarsis** [comment]
@janproch I tested beta 4 now, and it seems to have fixed all the mentioned issues above. As a bonus it also fixed the search filter in that list, which did also have issues prior to this, I guess those were related. Clicking functions not brings up them up correctly in the query view as well. Now I can start to really test this app out :grinning: Big thanks and good job!
