### ISSUE TITLE
QUESTION: thousands separator

### ISSUE THREAD

**Issue by anothergituser** [dbgate/dbgate#136]
**Details:**
Is there a setting for thousands separator? Maybe remove it, thanks

**Comment by janproch** [comment]
Now it is not configurable.

I have already pushed enhancement, which solves this, in next version it will be configurable (use thousands separator or not). 
Which separator to use is defined by current locale.

Also, default value for this configuration is not use thousands separator.

Thanks for good suggestion

**Comment by janproch** [comment]
Implemented in 4.2.6
