### ISSUE TITLE
BUG: Problem with arm64 build on mac

### ISSUE THREAD

**Issue by anothergituser** [dbgate/dbgate#138]
**Describe the bug**
When trying to install arm64 for mac it says archive is damaged and will not open.
The intel version works fine.
Thanks

**Comment by janproch** [comment]
Thanks for reporting. I have little chance to do anything with this, because lack of mac hardware. 

Could you please add screenshot with exact error message?

**Comment by anothergituser** [comment]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/1887699/124110599-b0a52900-da68-11eb-837f-111275101f13.png">

**Comment by anothergituser** [comment]
This seems so solve the issue, it now opens and runs correctly the arm64 version
```xattr -cr /Applications/dbgate.app```
This command would remove all extended attributes from the app

**Comment by janproch** [comment]
Fixed in version 4.8.4

ARM build is replaced with universal build, working on both Intel and Applice Silicon processors (without any hacking)
