### ISSUE TITLE
loosing connection in Win 10

### ISSUE THREAD

**Issue by br-egidio** [dbgate/dbgate#140]
**Details:**
connection to mariadb ist kept only for a short time and cannot be reconnected from within dbgate. only a new start enables  this.
Is there a setting to keep connections alive?

**Version Information [might be relevant to your issue]**
Operating System: 
Windows 10 Pro
Build: 19042.1052
App Version [help -> about]: 
Version: 4.2.6
Build date: 2021-06-30

**Screenshot [if appropriate]**:
A screenshot of the app if that helps
![grafik](https://user-images.githubusercontent.com/86768383/124085573-7b8cdc80-da50-11eb-95cb-f8cb67b4454b.png)

Thanks for your help! The programm has great features
B.Egidio

**Comment by janproch** [comment]
Thanks for bug report.

This issue is fixed in newest beta, 4.2.7-beta.1 . Release with this fix will be in 2 weeks.

**Comment by br-egidio** [comment]
Thanks for the beta. I installed it and let you know of any problems
B.Egidio

**Comment by janproch** [comment]
Fixed in 4.2.7
