### ISSUE TITLE
FEAT:  SQL Generator: Insert

### ISSUE THREAD

**Issue by Deigmin** [dbgate/dbgate#142]
Good day! 
I faced this problem, using `postgres`. I need to flow my data from one database into another. I generate insert query and save it. One column in my table has `boolean` row. Script generates `1` or `0` instead of `true` or `false`. Postgres has no implicity data cast. And when I'm starting to execute the script, program throws me an error. How could I generate that thing in `true`-`false`? Or there is no functionality for it now? 

P.S. I want to say, that dbgate is awesome. I tried to use DataGrip, but I wasn't able to find anything that could make me stay there. Thanks for your work!

Best regards

**Comment by janproch** [comment]
Thanks for feedback. It is fixed in latest BETA, tomorrow it will be in release.

In new version, for Postgres are generated true or false literals instead of 0 or 1

**Comment by janproch** [comment]
Fixed in 4.2.7
