### ISSUE TITLE
BUG: Update/Insert MongoDB

### ISSUE THREAD

**Issue by cschreier** [dbgate/dbgate#143]
**Describe the bug**
If you edit an existing entry or want to add a new entry and then click save, the changes will not be applied.

**To Reproduce**
1. Connect to a MongoDB
2. Edit an existing entry
3. Save the changes

**Expected behavior**
The changes should be applied to the entry.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 4.2.6
 - Install source: Installer
 - Type: Application
 - Database engine: MongoDB

**Comment by s4nd3r-m4nd3r** [comment]
Same here

**Comment by janproch** [comment]
Thanks for feedback. It is fixed in latest BETA, tomorrow it will be in release
