### ISSUE TITLE
BUG: Edit data num pad

### ISSUE THREAD

**Issue by cschreier** [dbgate/dbgate#145]
**Describe the bug**
If you click on a cell (not double click) and press a number on the numpad, the data will not be edited.
If you click any other key on the keyboard, the data will be edited.

**To Reproduce**
1. Go to a database
2. Click on a cell and press a key on the numpad
3. Data will not be edited

**Expected behavior**
The data should be edited.

**Version Information (please complete the following information)**
 - OS: Windows
 - App Version: 4.2.7
 - Install source: Installer
 - Type: Application
 - Database engine: MSSQL

**Comment by janproch** [comment]
@cschreier thanks for PR, this should work in newest BETA
