### ISSUE TITLE
Error showing columns

### ISSUE THREAD

**Issue by adonisnr** [dbgate/dbgate#147]
Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100108, now running 100419. Please use mysql_upgrade to fix this error.

**Comment by janproch** [comment]
Seems to be problem of MariaDB

In this stack-overflow thread is advice:
https://stackoverflow.com/questions/16177465/column-count-of-mysql-proc-is-wrong-expected-20-found-16-the-table-is-probabl

![image](https://user-images.githubusercontent.com/2543891/130036942-b8a28471-9218-42d1-97fd-f124da5050ac.png)
