### ISSUE TITLE
FEAT: support sideways scrolling in tables

### ISSUE THREAD

**Issue by vtnate** [dbgate/dbgate#150]
**Is your feature request related to a problem? Please describe.**
I can't scroll sideways with laptop trackpad

**Describe the solution you'd like**
Scrolling sideways to work with two-finger drag, similar to other apps, without having to click and drag on the slider on the bottom

**Describe alternatives you've considered**
Use the slider and not whine about a great free tool.

**Comment by boobo94** [comment]
I found Dbgate these days and is very cool.
The scrolls on the laptop are a very nice feature. I'm currently using a Macbook Pro and I cannot scroll using gestures.

**Comment by janproch** [comment]
Thanks for PR, now it is released in version 4.3.0
