### ISSUE TITLE
FEAT: redis conection

### ISSUE THREAD

**Issue by ssmns** [dbgate/dbgate#151]
**Is your feature request related to a problem? Please describe.**
add redis connection 

**Describe the solution you'd like**
can add a redis connection and show/modified  datas

**Comment by janproch** [comment]
This could be done maybe in future. But redis has structure very different from SQL and document (mongo) databases, currently I am not sure, how this integration could look like.

**Comment by Zerotask** [comment]
Redis support would be really great. I'm currently using https://www.npmjs.com/package/redis-commander

**Comment by axiaoxin** [comment]
Support Redis will be cool!

**Comment by Zerotask** [comment]
I mostly use it as a cache system, where I don't really care about the stored data at all. In that case metrics is more important for me.
Other use cases are related to caching, but on a higher level, e. g. storing frequently used user data

**Comment by Zerotask** [comment]
It would be great if you could consider RedisJSON too
https://oss.redis.com/redisjson/

I haven't worked with it yet, but it looks promising

**Comment by janproch** [comment]
Thanks for the feedback.

Redis connection is released, I am closing this issue.

Please create issues, if any problem with redis occurs.

About RedisJSON... It is not part of first release, but I consider it into some future release. If someone need this fature (explicit support of RedisJSON), please create standalone issue, to increase priority.
