### ISSUE TITLE
QUESTION: How could I find constraints in postgres?

### ISSUE THREAD

**Issue by Deigmin** [dbgate/dbgate#155]
Hello! 
My question is simple: how could I find constraints in postgres? I looked for it in "Open structure" menu, but there is no constraints. If dbgate doesn't have this functionality, maybe it's good to add it into that menu?

**Comment by Deigmin** [comment]
Also I couldn't find any information about `unique` fields in menu

**Comment by janproch** [comment]
Which constraints do you miss?

Now only supported constraints in PostgreSQL are primary keys and foreign keys, in tableeditor2 branch also indexes are supported (well, non-unique index is not constraint)

https://github.com/dbgate/dbgate/blob/tableeditor2/plugins/dbgate-plugin-postgres/src/backend/Analyser.js

I will add analysing of uniques, hopefully also check constraints. Any other constraint type do you miss?

**Comment by Deigmin** [comment]
Good day! Thank you!
