### ISSUE TITLE
BUG: Cannot Connect to Mongo DB, even though Testing the Connection is fine

### ISSUE THREAD

**Issue by whanata** [dbgate/dbgate#159]
**Describe the bug**
I cannot connect to Mongo DB that we have setup, even though testing the connection works though.

**To Reproduce**
1. Add a new connection.
2. Choose MongoDB.
3. Use the `Use Database URL`.
4. Test Connection, it works.
5. Try to connect the DB, and it has an `x`.

**Expected behavior**
If the test connection works, then I should be able to connect to the DB.

**Screenshots**
![image](https://user-images.githubusercontent.com/5918928/129513309-e3d1ac53-ba5d-4af7-9b9c-add03f02a2bc.png)
![image](https://user-images.githubusercontent.com/5918928/129513316-525746ab-56f1-45f3-934a-3c325a4fbb39.png)

**Version Information (please complete the following information):**
 - OS: Mac OS (Big Sur 11.5.1)
 - App Version: 4.2.7
 - Install source: Installer (from the website: https://dbgate.org/)
 - Type: Application
 - Database engine: MongoDB

**Additional context**
I think it would be good to find a way to get the logs for this connection, but I can't find a way to do this.

**Comment by janproch** [comment]
Thanks for error report. It seems, that error occurs after succesful connection.

If you hold mouse cursor on error icon, there is detailed information about error.  
Also when you run DbGate from console, there should be enough information to identify problem.

Could you add this information to this issue?  
Thanks

**Comment by whanata** [comment]
Hi @janproch, my bad I got it working, didn't have permission to list the databases, but if I specify a specific database, it's working fine.

Thanks for your help, and thanks for the app, it was hard to find a client that supports MySQL and Mongo at the same time. Glad I found this :)
