### ISSUE TITLE
FEAT: Change colors in JSON view for dark mode

### ISSUE THREAD

**Issue by cschreier** [dbgate/dbgate#160]
**Is your feature request related to a problem? Please describe.**
The font colors in the JSON view in dark mode have too little contrast 

**Describe the solution you'd like**
Choose font colors with better contrast.

**Comment by janproch** [comment]
It should be better now. However, fell free to improve these colors, definitions are in JsonCellView.svelte (see commit changes). Any PR welcome

Thanks

**Comment by janproch** [comment]
fixed in 4.3.0
