### ISSUE TITLE
BUG: MongoDB table view unable to copy field values

### ISSUE THREAD

**Issue by cschreier** [dbgate/dbgate#163]
**Describe the bug**
If a MongoDB document with nested objects is opened in the table view, no values can be copied.
The copied value is always _(No field)_.

**To Reproduce**
1. Open a mongodb document with nested objects
2. Switch to table view
3. Unhide the columns of the nested object
4. Copy a field value
5. Paste the copied value anywhere

**Expected behavior**
The copied value should be the field value.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 4.2.8-beta.2
 - Install source: Installer
 - Type: Application
 - Database engine: MongoDB

**Comment by janproch** [comment]
Thanks for perfect description. This issue is fixed in newest BETA, 4.2.8-beta.4, this fix will be released this week

**Comment by cschreier** [comment]
It's working!
Thank you!
