### ISSUE TITLE
FEAT: Add an ARM64 Windows edition in download

### ISSUE THREAD

**Issue by ppczouz** [dbgate/dbgate#165]
There is currently no DB client I could find that is native on ARM64 Windows.

**Comment by Zerotask** [comment]
There is a win_x64 download.

**Comment by ppczouz** [comment]
> There is a win_x64 download.

Win_x64 is an entirely different beast.
Win10 on ARM64 cannot execute x64 code, actually. Win11 would be able to, albeit through emulation (slowing things down)

**Comment by Zerotask** [comment]
No, it isn't. See https://en.wikipedia.org/wiki/X86-64 or many other websites.

**Comment by janproch** [comment]
Windows arm64 build is added, now is available in BETA version

**Comment by janproch** [comment]
added in version 4.3.0. Thanks for suggestion
