### ISSUE TITLE
BUG: MongoDB filter by _id

### ISSUE THREAD

**Issue by cschreier** [dbgate/dbgate#166]
**Describe the bug**
If a MongoDB collection is filtered on the ObjectID, no row is displayed.

**To Reproduce**
1. Connect to a MongoDB
2. Filter the ObjectID
3. See error (no result)

**Expected behavior**
Row with given ObjectID is displayed.

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 4.2.8
 - Install source: Installer
 - Type: Web
 - Database engine: MongoDB

**Comment by janproch** [comment]
fixed in 4.3.0
