### ISSUE TITLE
【Bug】postgresql  9.2.24 relation pg_ catalog.pg_matviews does not exit

### ISSUE THREAD

**Issue by beeflyme** [dbgate/dbgate#171]
**Describe the bug**
dbgate 4.3.0
postgresql  9.2.24 relation pg_ catalog.pg_matviews does not exit

**To Reproduce**

1. get / install 9.2.24 postgresql  
2. use dbgate to conn this db
3. See error
     relation pg_ catalog.pg_matviews does not exit

**Additional context**
postgresql   9.3 version begin has pg_ catalog.pg_matviews 

refer to https://www.postgresql.org/docs/current/view-pg-matviews.html
             https://www.postgresql.org/docs/9.3/view-pg-matviews.html

**Comment by beeflyme** [comment]
add an VIEW  is forbiden , the following error occur

=# create VIEW  pg_catalog.pg_matviews  as select * from public.pg_matviews
# ;
ERROR:  permission denied to create "pg_catalog.pg_matviews"
DETAIL:  System catalog modifications are currently disallowed.
nedoc_test3=#

**Comment by beeflyme** [comment]
===> add a pg_matviews without data.
create table public.pg_matviews 
(
"schemaname" varchar(64) COLLATE "default"  ,
"matviewname" varchar(255) COLLATE "default",
"matviewowner" varchar(64) COLLATE "default",
"tablespace" varchar(64) COLLATE "default",
"hasindexes" varchar(64) COLLATE "default",
"ispopulated" varchar(64) COLLATE "default",
"definition" varchar(64) COLLATE "default"
);

alter table  public.pg_matviews  set schema pg_catalog; 

https://billtian.github.io/digoal.blog/2017/03/15/03.html

**Comment by janproch** [comment]
Thanks for reporting. Is fixed in newest BETA, 4.3.1-beta.2

**Comment by janproch** [comment]
Released in 4.3.1

**Comment by beeflyme** [comment]
> Released in 4.3.1

Thank you, so fast.
