### ISSUE TITLE
QUESTION: Are release notes available somewhere?

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#174]
There are a lot of releases coming out for dbgate, which is cool. But I can't find any release notes for what has changed. So far I try to dig through commits to see, but it is not super easy to get a good overview from it. Is there any release notes available somewhere, and if not, maybe it could be added as part of each release directly here on Github?
Thanks!

**Comment by janproch** [comment]
change log should be up to date: https://github.com/dbgate/dbgate/blob/master/CHANGELOG.md

**Comment by tvarsis** [comment]
Ah, thanks! Didn't see that one.
