### ISSUE TITLE
FEAT: Copy row as INSERT/UPDATE statement

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#176]
Navicat has a feature where you can select a rows and then copy them as INSERT or UPDATE statements directly. So when you then paste, it will already be formatted as a correct INSERT/UPDATE statement with all the data in it.

I think this would be a great feature which should have a good value/effort ratio.

Thanks!

**Comment by janproch** [comment]
Thanks, good idea. Probably it will be implemented in next not-hotfix version

**Comment by janproch** [comment]
Release in 4.3.3
