### ISSUE TITLE
FEAT: Make window remember that it was maximized

### ISSUE THREAD

**Issue by KBulmer** [dbgate/dbgate#177]
**Is your feature request related to a problem? Please describe.**
Not sure if this is a FEAT or a BUG, but I like my window maximized, but every time I restart the program it's just a regular window in the wrong place.

**Describe the solution you'd like**
When starting DbGate, restore the window exactly as it was when it was closed. 🙂

**Comment by janproch** [comment]
Interesting, it it works for me on both Windows and Linux.

Which operating system do you use? And do you have more displays ?

**Comment by KBulmer** [comment]
I'm on Windows 10 using a single display. DbGate version 4.3.1 - portable. To elaborate I can say it remembers its windowed position perfectly. It's only when it's maximized (after restarting) that it ends up slightly smaller and a little bit off screen to the top left.
