### ISSUE TITLE
BUG: can't delete row with `binary` IDs in MySQL

### ISSUE THREAD

**Issue by Zerotask** [dbgate/dbgate#182]
**Describe the bug**
I tried deleting a row of a table, but it didn't work.

**To Reproduce**
1. install [Shopware](https://www.shopware.com/) locally
1. Open a random table
2. Try to delete a row

**Expected behavior**
I expect that the row is deleted.

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 4.3.1

**Additional context**
Shopware is using `binary` for their IDs and I assume that this is the problem.
The statement shows something like  `... WHERE id = NULL;`.

Adminer and MySQL Workbench are able to delete rows with binary IDs.

**Comment by janproch** [comment]
Thanks for bug report

I have created a fix now, it will be part of next release
The problem fixed was generally with MySQL binary fields

**Comment by janproch** [comment]
Released in 4.4.0
