### ISSUE TITLE
FEAT: Reorder table tabs and show text fields in a textarea 

### ISSUE THREAD

**Issue by anothergituser** [dbgate/dbgate#186]
Hello,

It would be nice to be able to click and drag open tables tabs to change the order, something like in firefox.
And the second thing is that in form view for a row, text column types are shown in a text input field that can get very wide when having lots of text, maybe for this type of field show it by default in textarea as wide as the widest field in it's column. This could be an option like "Use textarea for text type columns in form view".

Thanks

**Comment by janproch** [comment]
Thanks for feedback.

About draggable tabs, concept of DbGate is a bit different now, it sorts tabs automatically and groups the by databases (you can eg. close whole  group with one click). This concept is not compatible with draggable tabs. It is possible in future to have two variants - current variant and variant with draggable tabs without auto-sort and grouping. But now it is not priority for me.

I made some improvements of formview now, width of text fields in form view are now limited in the some way as in the table view (2/3 portion of available width). Textarea could be a bit more complicated, as it influences row height, which is used for computing column count.

**Comment by anothergituser** [comment]
Also, is there a way to set the font size? Thanks

**Comment by janproch** [comment]
Thank you for the idea

I have added zoom option in settings just now. It will be available today in BETA version, probably tomorrow in release

Changing font size of part of app is not possible

Please create new issues for new topics if possible

**Comment by janproch** [comment]
Released in 4.4.1
