### ISSUE TITLE
BUG: Incorrect timestamps being returned

### ISSUE THREAD

**Issue by jeffse** [dbgate/dbgate#188]
**Describe the bug**
Timestamps are being displayed several hours ahead of their true values.

**To Reproduce**
1. Load any table with timestamps from a database storing their timestamps in UTC.
2. Timestamps are rendered four hours ahead of their stored values

I suspect that DbGate is parsing the timestamps in the local time zone, then reconverting to UTC. Since I'm currently four hours behind UTC, the displayed timestamps are four hours ahead of their actual values.

If I change my computer's timezone to UTC, then the correct timestamps are displayed.

**Expected behavior**
Timestamps to be displayed as their true values.

**Screenshots**
Sample output from DBeaver showing the correct timestamps:
![image](https://user-images.githubusercontent.com/4191494/139449665-8931e853-680c-43e3-81fb-776c3a08d902.png)

Same output in DbGate:
![image](https://user-images.githubusercontent.com/4191494/139449759-af919bae-546b-452d-9f41-e1ecb7cb4e0c.png)

**Version Information (please complete the following information):**
 - OS: PopOS (Linux)
 - App Version: 4.3.3
 - Install source: unknown
 - Type: Application
 - Database engine: MySQL and PostgreSQL

**Comment by janproch** [comment]
For MS SQL solved in #137

**Comment by janproch** [comment]
Fixed in 4.4.1

Thanks for reporting

**Comment by jeffse** [comment]
Thank you!!!!
