### ISSUE TITLE
FEAT: code completion when table is not aliased? 

### ISSUE THREAD

**Issue by whudwl** [dbgate/dbgate#190]
When a table is not aliased, dbgate doesn't offer code completion. example: 
```
select 
  column -- suppose there is a column named columnA, dbgate wouldn't suggest it here 
from 
  some_table
```

If a table is aliased, code completion seems to work fine. example 
```
select 
  T0.column -- suppose there is a column named columnA, dbgate would suggest it here 
from 
  some_table T0 
```

I'm not sure if this is a feature or bug, but I myself certainly want code completion without having to always give alias to tables ( some people like T0, T1, T2 etc, which I hate since that makes code less readable).

**Comment by janproch** [comment]
Thanks for the feedback. Code completion was slighly improved in 4.4.0, your scenario is now supported.
