### ISSUE TITLE
Docker container takes 10 seconds to stop

### ISSUE THREAD

**Issue by max-datagamma** [dbgate/dbgate#192]
It takes an inordinately long time to stop the container -- 10 seconds is not unusual.

**To reproduce**
Start a Docker container, then issue docker stop -- it takes 5-10 seconds to complete.

**Expected behavior**
A docker stop for this type of application should not take more than a second.

**Version Information (please complete the following information):**
 - OS: OSX 11.6
 - Docker engine 20.10.8
 - App Version 4.3.4

My guess is that this is due to the lack of proper signal handling. I know it sounds minor, but if you have to start and stop these things often, it really makes a difference. Very nice app, by the way!

**Comment by janproch** [comment]
Will be solved if future release. 

Docker should send SIGTERM signal when running docker stop ( https://docs.docker.com/engine/reference/commandline/stop/ ), this signal is handled by nodejs by default - exit process immediately. There are child processes, they are exited after 1s using childProcessChecker mechanism. So it should work now, deeper analysis will be neccessary.

**Comment by janproch** [comment]
Fixed in BETA dbgate/dbgate:beta

**Comment by max-datagamma** [comment]
Thanks, looking forward to it. Much appreciated.

**Comment by janproch** [comment]
Released in 4.5.0

**Comment by max-datagamma** [comment]
Not that you need my validation, but I can confirm that this issue is indeed fixed. Thank you!
