### ISSUE TITLE
BUG: Materialized views and fuctions are not part of intellisense/auto complete

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#200]
Materialized views and functions does not show up in the auto suggest completion that pops up when typing. It seems to only work for views/tables.

 - OS: OpenSUSE Tumbleweed
 - App Version: 4.4.3
 - Install source: Appimage
 - Type: Application
 - Database engine: PostgreSQL 13.5

**Comment by janproch** [comment]
Released in 4.5.0

Thanks for suggestion
