### ISSUE TITLE
FEAT: Turn off spell check

### ISSUE THREAD

**Issue by EdenHell** [dbgate/dbgate#203]
**Is your feature request related to a problem? Please describe.**
The red wavy line of uuid is annoying.

**Describe the solution you'd like**
Turn off the spell check of electron.

**Additional context**
![image](https://user-images.githubusercontent.com/5779655/148022298-a3edc79a-f042-48b9-895f-16b9ce61ffb6.png)

**Comment by janproch** [comment]
Released in 4.5.1

Thanks for reporting
