### ISSUE TITLE
BUG: Latest download link for MacOS broken

### ISSUE THREAD

**Issue by rgeraldporter** [dbgate/dbgate#204]
**Describe the bug**
The main link to download DBGate on the website is a dead link: https://github.com/dbgate/dbgate/releases/download/v4.5.1/dbgate-latest.dmg

**To Reproduce**
1. Go to website when using a Mac
2. Click on Download for MacOS
3. Get 404 error

**Expected behavior**
Should download a DMG file

**Comment by asselinpaul** [comment]
breaks brew cask as well

**Comment by janproch** [comment]
Fied in BETA v4.5.2-beta.8 . Thanks for reporting this

**Comment by janproch** [comment]
fix released in 4.6.0
