### ISSUE TITLE
BUG: Can't select .pem certificates

### ISSUE THREAD

**Issue by yuriizinets** [dbgate/dbgate#206]
**Describe the bug**
Can't use any .pem files for SSL connection (confirmed for PostgreSQL)

**To Reproduce**
1. Add connection
2. Go to SSL tab
3. "Use SSL"
4. Try to select .pem certificate

**Expected behavior**
I think it's clear

**Screenshots**
![Screenshot 2022-01-17 at 09 34 05](https://user-images.githubusercontent.com/17050536/149735299-ef8f01e0-7f87-41ef-a5f7-bb9feae5e7d6.jpg)

**Version Information (please complete the following information):**
 - OS: MacOS 11.6.1 (Big Sur)
 - App Version 4.5.1
 - Install source: Installer
 - Type - Application
 - Database engine: PostgreSQL

**Comment by janproch** [comment]
Fixed in version 4.8.4
