### ISSUE TITLE
BUG: Opening more than one instance resets theme

### ISSUE THREAD

**Issue by jamerst** [dbgate/dbgate#207]
**Describe the bug**
Opening a new instance of dbgate when one is already open resets the theme to light.

**To Reproduce**
1. Open dbgate, ensure dark theme is selected
2. Open another instance, light theme will be used instead of dark

**Expected behavior**
The dark theme should be used

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 4.5.1
 - Install source installer
 - Type - Application
 - Database engine: SQL Server (issue occurs before connecting though)

**Additional context**
Other UI settings also seem to be reset to default, e.g. side pane width

**Comment by janproch** [comment]
Theme settings is saved in local storage. It seems that electron has problems to access local storage from more simutaneously opened windows.

I am going to move same settings to settings.json file, inlcuding current theme.

**Comment by janproch** [comment]
Implemented in 4.7.1

Thanks for reporting
