### ISSUE TITLE
QUESTION: Environment variable for ssh tunnel

### ISSUE THREAD

**Issue by koenigmarcel** [dbgate/dbgate#210]
When i restart my Docker all connections reset and have to be added again, so i want to configure this with environment variables.
All variables work but i dont know how to configure the SSH Tunnel with them. Is it even possible?

_Linux Debian, Docker
DbGate 4.6.0_

**Comment by janproch** [comment]
Thanks for that question. Now it is not implemented, I will add this possibility into next version.

**Comment by janproch** [comment]
Implemented in current BETA, variables added to documentation on docker hub: https://hub.docker.com/r/dbgate/dbgate

Release is planned next week

**Comment by janproch** [comment]
Released in v4.6.1
