### ISSUE TITLE
FEAT: Upload/Download of files in Blob Datatypes

### ISSUE THREAD

**Issue by fofo78** [dbgate/dbgate#211]
**Is your feature request related to a problem? Please describe.**
Right now i can neiter select a blob column for upload of a file nor for download of a file.

**Describe the solution you'd like**
I want a context menu entry to up- and download a file in a blob column

**Comment by janproch** [comment]
Thanks for the idea  This could be a bit more complicated, as it will require correct handling of blob fields in all db drivers, but it is planned as main topic of next release

**Comment by janproch** [comment]
Implemented in BETA 4.6.2-beta.1, release will be next week

**Comment by janproch** [comment]
Released in version 4.6.3
