### ISSUE TITLE
BUG: Column or function 'REFERENTIAL_CONSTRAINTS.CONSTRAINT_NAME' is not recognized

### ISSUE THREAD

**Issue by marcinhladki** [dbgate/dbgate#214]
The error appears in the TABLES, VIEWS, FUNCTIONS panel. For this reason, there is no information about the database structure, and the structure suggestion in the editor does not work.
The fruitless attempts to download the structure cannot be stopped despite the deactivation of the 'Automatic refresh of database ...' option.

Server for this connection is not exatly server, but CData JDBC driver for Salesforce working in JDBC Remoting mode. It shows MySQL version = 5.7.6

**Comment by janproch** [comment]
Thanks for reporting. It is fixed in BETA 4.6.2-beta-2, release will be next week

**Comment by janproch** [comment]
Released in version 4.6.3
