### ISSUE TITLE
Minor BUG: Typo

### ISSUE THREAD

**Issue by mroeling** [dbgate/dbgate#221]
**Describe the bug**
Right click menu on a data row contains two minor typos.

**To Reproduce**
postgres
execute query
right click on data row
notice colunn instead of column

**Screenshots**
![image](https://user-images.githubusercontent.com/2706186/153444584-8fcf5fab-6c1e-4371-a008-da178209fe1c.png)

**Comment by janproch** [comment]
Thanks, fixed
