### ISSUE TITLE
Font size settings

### ISSUE THREAD

**Issue by TheHorizo** [dbgate/dbgate#229]
If there a next update please include the control of font size, the size of the letter is too small but I love the UI of it

**Comment by janproch** [comment]
You can control zoom level of application in settings. If this is not suitable for you, please describe, how you imagine controlling of font size.

Thanks

**Comment by janproch** [comment]
I am going to implement font size settings for SQL editor

**Comment by janproch** [comment]
In version 4.7.1 is zoom supported in electron app (menu) and in web app (native browser zoom)

**Comment by TheHorizo** [comment]
> You can control zoom level of application in settings. If this is not suitable for you, please describe, how you imagine controlling of font size.
> 
> Thanks

![DBgate](https://user-images.githubusercontent.com/64895072/156757457-549ee5f2-5cac-4512-988e-130c2500c00f.png)

Sorry for the late noticed 
Zoom function for me is perfectly fine but when I try to read my query or write a query Zoom function seem to only expand the size of an icon, Status bar or tab bar. The more I zoom in the seem the size of the font will become a little bigger but I can't easily access it when it runs, or to see the change. I thought I was just overly needy, but when I recommend DBgate to my group of friends 4/6 say the same thing 
Thanks for understanding

**Comment by janproch** [comment]
OK, thanks for clarifying. I will add editor font size settings, as was the original plan

**Comment by janproch** [comment]
Released in 4.7.2
