### ISSUE TITLE
Publish DbGate windows build to Chocolatey community repo

### ISSUE THREAD

**Issue by janproch** [dbgate/dbgate#234]
As described here

https://docs.chocolatey.org/en-us/create/create-packages

If anyone wants to contribute, this is good option

**Comment by janproch** [comment]
I am closing related issue #107

**Comment by dgalbraith** [comment]
Packages for DbGate have been created for the Chocolatey community repository - [dbgate](https://community.chocolatey.org/packages/dbgate/4.7.1), [dbgate.install](https://community.chocolatey.org/packages/dbgate.install/4.7.1) and [dbgate.portable](https://community.chocolatey.org/packages/dbgate.portable/4.7.1).  They are currently awaiting review by a moderator.

The packages can be installed with:

```
choco install -y dbgate --version=4.7.1
choco install -y dbgate.install --version=4.7.1
choco install -y dbgate.portable --version=4.7.1
```

Once the packages have been approved by a moderator version specification will no longer be required and the latest version will be installed if a version is not specified.

The `dbgate` package is a meta-package which will install the `dbgate.portable` package for all users.

The only point to note is that the install package can currently only perform a per-user install as opposed to one for all users.  It looks as though the NSIS generation specified `/currentuser` only and does not support an override.  It might be worth updating this at some point.

**Comment by janproch** [comment]
Great, thank you!

**Comment by janproch** [comment]
Packages are now reviewed and published, closing
