### ISSUE TITLE
FEAT: allow to sort on multiple keys

### ISSUE THREAD

**Issue by opensas** [dbgate/dbgate#235]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to create compound sorting keys by combining several fields in ascending and descending order

**Describe the solution you'd like**
When you click on a field instead of the `Sort ascending` and `Sort descending` options like this:

![image](https://user-images.githubusercontent.com/481687/155591911-35a2abe0-aa7b-4b54-b530-10cb0d689c9c.png)

Show the following options

- Clear sort criteria (disabled when no sort criteria has been set)
- Add to sort criteria ascending
- Add to sort criteria descending

This allowing sort by several fields

**Describe alternatives you've considered**
Being able to manualy edit the query

**Comment by janproch** [comment]
Good idea, thanks! It is not greatest priority, but I will definitely implement it.

**Comment by janproch** [comment]
Released in 5.0.3

**Comment by opensas** [comment]
YES!!!! :clap:
