### ISSUE TITLE
FEAT: Include button to close all tabs for a database, even when there's only one tab open for the given database

### ISSUE THREAD

**Issue by superDuperCyberTechno** [dbgate/dbgate#238]
**Is your feature request related to a problem? Please describe.**
The small button to close all tabs for a given database is only included when there's more than one tab open. For more consistent UX, I think it would be a nice touch to include it even though it's arguably superfluous.

![tab_close_button](https://user-images.githubusercontent.com/6486383/155963937-107e01a6-e26b-44b2-a9e0-e3240268d4da.png)

**Describe the solution you'd like**
Add button to close all tabs for a database even though it (the database) only has one tab open.

**Describe alternatives you've considered**
A alternative solution (and complementary addition to UX) could be to add a keyboard shortcut that always closes all tabs for a given database. Right now there are shortcuts to close the current tab and _all_ tabs. Maybe include a function to close all tabs for the current database?

**Comment by janproch** [comment]
Hide close button for database containing one opened tab was an intention, but you are right, it looks weird. I will change it. Only when there is (NoDB) title, close button will be hidden
