### ISSUE TITLE
FEAT: Search function for the Keyboard Shortcuts overview

### ISSUE THREAD

**Issue by superDuperCyberTechno** [dbgate/dbgate#239]
**Is your feature request related to a problem? Please describe.**
It's very finicky to track down shortcuts you want to look up (or customize). Being able to do a free text search would greatly improve the usability.

**Describe the solution you'd like**
Add a shortcut `ctrl-f` to the Keyboard Shortcuts view where you can search for anything.

**Describe alternatives you've considered**
Initially I looked for a way to export the data in the Keyboard Shortcuts view (to use `ctrl-f` in my text editor) but that didn't exist. Now I lock eyes on a column and scroll until I track down the thing I need.

**Comment by janproch** [comment]
Good idea, I am going to add this
