### ISSUE TITLE
BUG: Unable to open database file for SQLite

### ISSUE THREAD

**Issue by DanS** [dbgate/dbgate#243]
**Unable to select SQLite database file to make a new database connection**

**To Reproduce**
1. Create a SQLite database file with the name of "dev.db" 
2. Click on "add new connection
3. Select "SQLite" as database engine
4. Click the "Browse" button 
5. Browse to location of file created in step 1
6. Observe file is greyed out and unselectable
7. Open button is greyed out and unclickable

**Expected behavior**
user should be able to select file
"open" button should not be greyed out

**Version Information:**
 - OS: Mac Big Sur  - have not tested other OS
 - App Version 4.7.0 Build date: 2022-02-21
 - Install source NPM
 - Type - Application
 - Database engine: SQLite

**Additional info**
Work around:  When unable to select file
1. right click on file
2. choose "rename" but don't edit the file name
3. click the open button which has become clickable

**Comment by vtnate** [comment]
Looks similar to #149 that @janproch worked on a while back.

**Comment by janproch** [comment]
Fixed in version 4.8.4
