### ISSUE TITLE
BUG: ctrl-tab cycles only among the last two tabs

### ISSUE THREAD

**Issue by opensas** [dbgate/dbgate#245]
**Describe the bug**
After opening three tabs, pressing `ctrl-tab` cycles only between the last two visited tabs, instead of cycling among all of them

**To Reproduce**

1. Open DbGate
3. Open thre tabs (for example, press ctrl-q three or more times)
4. repeteadly press `ctrl-tab`
5. `ctrl-tab` will only cycle among the two last opened tabs

**Expected behavior**
I expect `ctrl-tab` to cycle among all open tabs

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - App Version 4.7.2
 - Install source can't recall
 - Type - Application
 - Database engine: PostgreSQL

**Comment by janproch** [comment]
Fixed in version 4.8.8

Added Ctrl+Shift+Tab for reverse order tab browsing
