### ISSUE TITLE
allways get -  foreign key mismatch even when reference match 

### ISSUE THREAD

**Issue by opitData** [dbgate/dbgate#247]
*using web interface docker with sqlite DB

when trying to add a new row to a table which have a foreign key column , after trying to save will allays get error of 
foreign key mismatch - "TestTable" referencing "ENUM_VALUES"

To Reproduce:

1.create a reference table and fill the enums
for example:

 CREATE TABLE `ENUM_VALUES` ( 
  `id` integer   PRIMARY KEY autoincrement,  
  `enumID` int(11) NOT NULL,
  `Type` varchar(100) NOT NULL,
  `Value` varchar(100) NOT NULL
) ;

INSERT INTO ENUM_VALUES (enumID, Type, Value)  VALUES (0,"PHASE_TYPE","1P1W");
INSERT INTO ENUM_VALUES (enumID, Type, Value)  VALUES (1,"PHASE_TYPE","1P2W");
INSERT INTO ENUM_VALUES (enumID, Type, Value)  VALUES (2,"PHASE_TYPE","3P1W");
INSERT INTO ENUM_VALUES (enumID, Type, Value)  VALUES (3,"PHASE_TYPE","3P2W");
INSERT INTO ENUM_VALUES (enumID, Type, Value)  VALUES (4,"PHASE_TYPE","3P3W");

2. create the table that use the reference 
 CREATE TABLE `TestTable` ( 
  `id` integer   PRIMARY KEY autoincrement,  
    `WhereAmITime` varchar(100) NOT NULL,
  `WhereWasI` varchar(100) NOT NULL,
      PHASE_TYPE      INTEGER NOT NULL,
    FOREIGN KEY (PHASE_TYPE) REFERENCES ENUM_VALUES(enumID)
) ;

3. try to add a new row to TestTable via web interface

4. when trying to send quarry will send error of   foreign key mismatch
Expected behavior:
should insert the new row.

Screenshots:
1.
https://ibb.co/LZ9VQtC
2.
https://ibb.co/b74PZZ6
3.
https://ibb.co/dDTdk7w

Version Information (please complete the following information):

 - OS: ubunto
 - App Version: 4.7.3
 - Install source : Docker
 - Type Web
 - Database engine: sqlite

Additional info:
same quary from the web interface works when using from the sqlite terminal on linux

**Comment by janproch** [comment]
It is error returned directly by SQLite engine, DbGate has no influence on this

However, you have foreign kery referencing to normal column. Standard approach is to reference primary key column, or at least column, which is has unique index on it

I am not sure, how SQLite defines this, but other SQL engines mostlly requires foreign key to be reference to primary key or unique index

If you use this table:

```sql
CREATE TABLE TestTable2 (
id integer PRIMARY KEY autoincrement,
WhereAmITime varchar(100) NOT NULL,
WhereWasI varchar(100) NOT NULL,
PHASE_TYPE INTEGER NOT NULL,
FOREIGN KEY (PHASE_TYPE) REFERENCES ENUM_VALUES(id)
) ;
```

Than inserting works correctly
