### ISSUE TITLE
FEAT: consider changing the dbgate-data directory that is created in HOME

### ISSUE THREAD

**Issue by devtrends** [dbgate/dbgate#248]
**Is your feature request related to a problem? Please describe.**
Under linux, dbgate creates a visible, dbgate-data folder directly in the user's home directory. This is not typical Linux behaviour and it clutters the home directory.

**Describe the solution you'd like**
Store this data  in a .config sub-directory e.g. ~/.config/dbgate-data/

Alternatively, change the current directory to ~/.dbgate-data/

**Comment by janproch** [comment]
Good point! I will do this, it will require moving data into new location, but this should be definitely done

**Comment by janproch** [comment]
Changed in 5.0.0

**Comment by ethanmlee** [comment]
You may want to change this in the docker-compose example on docker hub. I ran into some problems until I saw this issue. https://hub.docker.com/r/dbgate/dbgate. So change the following from the docker-hub page:

```
    volumes:
      - dbgate-data:/root/dbgate-data
```

to this:

```
    volumes:
      - dbgate-data:/root/.dbgate
```

**Comment by janproch** [comment]
@ethanmlee Thanks, updated
