### ISSUE TITLE
FEAT: Configure default click action for table/function/views/materialized views etc

### ISSUE THREAD

**Issue by tvarsis** [dbgate/dbgate#255]
When a user clicks in the left pane table explorer on view for example, it will then load up the data from that view. It would be a nice feature to be able to configure that default click action in settings to define the click action for tables/function/views/materialized views independent from each other. For me personally when I click a view, I would like to come to the "CREATE VIEW" script since I would rather see the code and then maybe double click to load data or similar. But I understand it is a matter of opinion/workflow, hence defining this for different entities in the settings, would be a great addition that will support more use cases and workflows.

Thanks!

**Comment by janproch** [comment]
Nice idea, I like it, thanks! I will try to implement it soon

**Comment by janproch** [comment]
Released in 5.0.3
