### ISSUE TITLE
QUESTION: How to set extension or theme icon?

### ISSUE THREAD

**Issue by wallysonn** [dbgate/dbgate#256]
**Details:**
I made a theme "dbgate-plugin-wg-theme-dark" and I would like the icon.svg to be visible in available extensions;

**Version Information**
Operating System: Windows 11 22H2
App Version 4.8.2:

**Comment by janproch** [comment]
Nice theme! Setting icon is a bit tricky, as NPM doesn't support icons, as I know...

Publish your icon somewhere under public URL and add icon URL in description attyribute in your package.json:
```
"description": "Any description ![icon](https://link_to_icon.svg)",
```

This will work from newest BETA, 4.8.3-beta.2 . It replaces old approach, which requries public github repository with plugin

**Comment by wallysonn** [comment]
> ![icon](https://link_to_icon.svg)

![image](https://user-images.githubusercontent.com/7926071/161681103-218d7d71-879a-41ef-ac78-10c32f15fd31.png)
