### ISSUE TITLE
BUG: Latest Mac Arm build fails on M1

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [dbgate/dbgate#259]
Says it's damaged and to trash it.

**Comment by janproch** [comment]
Ok, thanks for alerting. I should be able to solve Mac related issues next week, after my new Mac M1 will arrive.

**Comment by janproch** [comment]
Fixed in version 4.6.4

ARM build is replaced with universal build, working on both Intel and Applice Silicon processors
