### ISSUE TITLE
Windows authentication for Web application 

### ISSUE THREAD

**Issue by jorgia111** [dbgate/dbgate#261]
Does the web application support Windows authentication? or how do i authenticate numbers  AD users against the web application ? I am using latest dbgate docker images ,any help with ?

**Comment by janproch** [comment]
You mean authentizate web app users against AD or use MS SQL windows auth?

Ms sql windows auth is as I know not possible inside linux docker containers.

Authentization web app users against AD is now not supported, but it should be implemented in future.

**Comment by wil-m** [comment]
upvoting for AD authentication :+1:

**Comment by janproch** [comment]
Active directory is configurable view env. variables (see docs https://dbgate.org/docs/env-variables.html)

AD_URL - URL of LDAP provider (eg ldap://domain.com)
AD_BASEDN - eg. dc=domain,dc=com
AD_USERNAME - username to active directory
AD_PASSWORD - password to acvtive directory
AD_ALLOWED_LOGINS - comma separator login names, which will be allowed to login. If not specified, all logins will be allowed to use DbGate app.
