### ISSUE TITLE
FEAT: more updated app design

### ISSUE THREAD

**Issue by Zerotask** [dbgate/dbgate#262]
**Is your feature request related to a problem? Please describe.**
Not a real problem, but the app design (GUI) looks outdated compared to other similar programs I used recently

**Describe the solution you'd like**
Make a new default design with updated colors, font(s) and better color schemes so that the program looks more welcome for others
Example:
![image](https://user-images.githubusercontent.com/20150243/162503313-392bfdb5-a7d3-430f-8f83-8a79135ff14d.png)

**Comment by janproch** [comment]
Thanks ofr your opinion.

Design is point of view, however, I must admin, that I am not strong in this. I used design ideas from Visual Studio Code, I guess the same method used Matthew from Beekeeper Studio on screenshot.

Design of DbGate is improved gradually, last big improvement was introducing non native menu for Windows and Linux, in next week I want to do similar improvements for Mac.

But DbGate has plugin system, which allows creating custom themes. Now there are already 2 cool looking themes from other contributors. If some custom theme will look like more popular than original theme, I have no problem (with author's permission) to replace default theme. 

![image](https://user-images.githubusercontent.com/2543891/162560246-99e2445c-78b9-4b31-8b9b-80557a02c755.png)

![image](https://user-images.githubusercontent.com/2543891/162560270-52ce2d79-7869-46fe-9716-04c3b6256b09.png)

**Comment by GitClickOk** [comment]
@janproch I totally disagree with this request for a "more updated app design". The VsCode like UI is very nice, and seriously I found in DbGate what I was searching for in Azure Data Studio. I understand you will improve the UI with the time, and you can leave for theme developers this task.
Thank you and keep up the great work!
