### ISSUE TITLE
BUG: Cannot Load Models on MSSQL 2005

### ISSUE THREAD

**Issue by FabricioGonzalez** [dbgate/dbgate#266]
When connecting and trying to load the databases, show an error of invalid_column is_sparse.

- Connect to database.
- Click in one of the db.
- The error will be shown on the tables,views,functions tab

The database should load all models and tables.

![Captura de tela 2022-04-12 200057](https://user-images.githubusercontent.com/52975021/163068242-9a047b8a-21d7-48e3-90b7-2ef9b3142047.png)

 - OS: Window 11
 - App Version:  4.8.3
 - Install source: Installer
 - Type - Application
 - Database engine: SQL Server

**Comment by janproch** [comment]
SQL 2005 is now not supported. Now I have no hardware to test this. Are you able to test this support, if added? Probably I could make it in 1 month.

**Comment by FabricioGonzalez** [comment]
I could test. I thought it was a bug. 
It is an isolated case. Maybe I will try to help in some free time.
By the way, your project is very good. I Liked the way UI works.
It is better than other tools to manager DB systems.
I will keep using this for a long time.
