### ISSUE TITLE
BUG: Cannot read property 'columns' of null

### ISSUE THREAD

**Issue by moalamri** [dbgate/dbgate#268]
**Describe the bug**
The app crash due trying to add index to new table

**To Reproduce**
1. Connect to DB
2. Create new table
3. Add columns
4. Save
5. **The table tab gets refreshed with empty columns**
6. Press `Add index`
7. **App crash**

Due to having empty columns when the view gets refreshed the app crashes when I press on 'Add index'

**Expected behavior**
To refresh tab with the created columns

**Screenshots**
![image](https://user-images.githubusercontent.com/964077/163288637-b45ea32c-216b-49d8-9198-1a9955b96141.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 4.8.3
 - Install source: installer
 - Type - Application
 - Database engine: SQL Server 2019

**Comment by janproch** [comment]
I have fixed crashing after clicking "Add index"

However, there is still problem, which I cannot reproduce, when you click "Save", columns should not vanish

Is there any error in console, when you run dbgate from command line?

**Comment by moalamri** [comment]
I didn’t use the source code instead I used bundled with installer as I couldn’t get the source to run.
I will test it today against different providers. Also will post any console output here.

**Comment by moalamri** [comment]
Hi,
I have downloaded & installed Version: 4.8.7-beta.2 for Windows 64
The issue mentioned here is fixed so no more null columns crash.

Regarding the semi-related issue (Table refresh), I tested it against another provider (Postgres 14) as well and got the same results: the table gets refreshed to empty state (Nothing printed on console)

The only guess I have for now is that perhaps something gets passed to the table creation window that causes this, because I noticed that when creating a new table for postgres the app still treat it as a mssql table so it shows columns types related to mssql (int, nvarchar .. etc) and just to try when I chose nvarchar for postgres I get this alert: `Type 'nvarchar' does not exist` and here's the generated script for postgres:
```sql
BEGIN TRANSACTION;
ALTER TABLE "public"."newTable" ADD "Name" NVARCHAR(250) NULL;
COMMIT;
```
Which is non-postgres related script.

My other guessing is it could be OS related issue? I faced many since I updated to Windows 11.
Anyways I will close this issue as it has been fixed, and the other issue could be from my side, so if any further user report the same issue could you please mention me so we can work it out?

Thank you
