### ISSUE TITLE
BUG: OS X App unresponsive, cannot paste

### ISSUE THREAD

**Issue by data-source** [dbgate/dbgate#270]
**Describe the bug**
Intel installer gives 404 (https://github.com/dbgate/dbgate/releases/download/v4.8.6/dbgate-latest-64.dmg ) 
Went with ARM+Intel app. 
Tried a few tests, I can connect to a DB, type a query, but cannot paste any. 

**To Reproduce**
1. Add a query
2. Try Command + V 
3. See nothing getting pasted 

**Expected behavior**
Code block should be added

**Screenshots**
N/A

**Version Information (please complete the following information):**
 - OS: OS X Monterey 12.3.1
 - App Version: 4.8.6 
 - Install source: Installer
 - Type: Application
 - Database engine: PostgreSQL

**Additional info**
N/A

**Comment by janproch** [comment]
Hi, thanks for reporting, copy & paste operations on macOS are already fixed in BETA, release will be probably on thursday

**Comment by janproch** [comment]
Released in 4.8.7
