### ISSUE TITLE
BUG: loading database structure very slowly

### ISSUE THREAD

**Issue by alisanguo** [dbgate/dbgate#273]
**Describe the bug**
loading database structure very slowly, there are about 500 tables in my database

**Screenshots**
![image](https://user-images.githubusercontent.com/17509906/164959054-e87f215a-4460-4a49-8126-8a66ebfeaf09.png)

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: 4.8.7
 - Install source: installer
 - Type - Application
 - Database engine: MySQL5.7.29

**Comment by janproch** [comment]
There are possible optimizations to make it faster

I see the biggest chance to improve performance in loading MySQL views. How many views approx does contain your database?

And what approx time is needed for loading structure?

**Comment by alisanguo** [comment]
no views in my database, some minutes when there are 1800 tables. I think it is too slow

**Comment by christiantosta** [comment]
Same problem here with PostgreSQL 12 which makes dbgate unusable. Tryed both AppImage and Docker install methods (Version 4.8.8).

**Comment by bjurtan** [comment]
Also experiencing slow db structure load, table imports etc, to the point where the tool is unuseable.

Running docker imgate dbgate/dbgate:alpine on an Azure App Service in an App Service Environment, connecting to MySQL 5.7 Flexible Server. Any ideas?

**Comment by janproch** [comment]
It is possible to send me dumped database structure, without data, to debug this behaviour?

**Comment by bjurtan** [comment]
> It is possible to send me dumped database structure, without data, to debug this behaviour?

In my case, I'm starting fresh, creating a new db. Think it's alpine or azure related..

**Comment by christiantosta** [comment]
> It is possible to send me dumped database structure, without data, to debug this behaviour?

Simple install a fresh Odoo database.

**Comment by janproch** [comment]
@christiantosta Odoo, you mean this https://www.odoo.com/ ? I am not familiar with this software. If you could provide me database dump of empty DB, it will be great.

I could try to play with it, but it will take longer time to be able to do this.

Thanks

**Comment by janproch** [comment]
@bjurtan Alpine should work OK. Probably there is problem with Azure App Service. It is possible to connect to some public MySQL database  on Azure to test it? Ir is it neccessary to create test Azure account?

**Comment by susnick** [comment]
[odoo.txt](https://github.com/dbgate/dbgate/files/8743732/odoo.txt)

I actually was doing a demo of this software for work. Here is schema with almost all the free modules included.

**Comment by janproch** [comment]
@christiantosta Thanks for the idea. I have tested it with database generated from Docker, dbgate analyses it in 2 seconds. Probably problem is, that analysing fails with unreported error

@susnick Thanks for the dump. I will test it and try to optimize this week with this

**Comment by janproch** [comment]
In latest BETA, there are several otimalizations:

PostgreSQL: improved loading foreign keys (on odoo DB, loading after this improvement was approx. 9x faster)
MySQL: improved loading views
MySQL, PostgreSQL, MS SQL: Loading structure feedback (you see, what is currectly loaded)

**Comment by janproch** [comment]
Optimalization released in version 5.0.3. If this doesn't help, please reopen this ticket
