### ISSUE TITLE
BUG: Exported SQL has table name undefined

### ISSUE THREAD

**Issue by RSWilli** [dbgate/dbgate#277]
**Describe the bug**
when exporting rows of a table, the `INSERT INTO` clauses have the table name `undefined`

**To Reproduce**
1. open a table
2. Click on "export" > SQL **at the bottom**
3. exported file has table name undefined

**Expected behavior**
If you use the export > SQL via right click on a table in the list of tables, it works flawlessly. Both exports should have the same functionality

**Screenshots**

output of the buggy export (values and columns are omitted here, but they are correct):
```sql
INSERT INTO undefined (...) VALUES (...);
INSERT INTO undefined (...) VALUES (...);
INSERT INTO undefined (...) VALUES (...);
INSERT INTO undefined (...) VALUES (...);
```

**Version Information (please complete the following information):**
 - OS: Archlinux
 - App Version 4.8.8
 - Install source Archlinux AUR
 - Type - Application
 - Database engine: MariaDB 10.1

**Comment by janproch** [comment]
Thanks for reporting, this should be fixed. I have seen insert into undefined somewhere and couldn't remember where

Small note, if you use export menu in table list, result could be different. Exporting from table data view should respect visible columns and filtered rows.
