### ISSUE TITLE
FEAT: Import files that was saved as diagram-file back to DbGate

### ISSUE THREAD

**Issue by dzavodnikov** [dbgate/dbgate#278]
**Describe the solution you'd like**
I can save ERP-diagram as diagram-file (JSON), but can not open again. Let's make inport such diagrams.

**Describe alternatives you've considered**
Let's make possible to export ERP-diagrams to drawio-files format.

**Comment by janproch** [comment]
Thwre was possibility to load saved ERD diagram, when saved to local files. From version 5.0.0, it is possible also load diagram files from disk.

Released in 5.0.0
