### ISSUE TITLE
BUG: Unable to drag on MacOS

### ISSUE THREAD

**Issue by susnick** [dbgate/dbgate#281]
**Describe the bug**
You are unable to drag the electron window on MacOS.

**Expected behavior**
Should be able to move the window to different locations

I made a pull request to at least allow dragging using the sidebar menu

**Comment by janproch** [comment]
PR merged, released in newest BETA

Does it work now?

On my Mac M1, it worked also in older version.

Thanks

**Comment by susnick** [comment]
On My Mac, There is no title bar. It kind of looks bad with the window buttons, but that a problem for another day. Here is screen recording showing that I am unable to move the window.

https://user-images.githubusercontent.com/1975526/169649023-29d7d534-a3ed-4a54-94be-5fa5a12430fe.mov

**Comment by janproch** [comment]
Thanks for video, now it is clear. This was problem for all Macs, unless you did't change Use native menu options.

It is fixed in newest BETA 5.0.0-beta.7

**Comment by janproch** [comment]
Released in 5.0.0
