### ISSUE TITLE
cant not move window [Mac]

### ISSUE THREAD

**Issue by yuhuihu** [dbgate/dbgate#283]
Mac 12.3.1

version:
Version: 4.8.8
Build date: 2022-04-29

Can Not Move Window after started.

**Comment by janproch** [comment]
This is solved in MR #282 . What part of window do you use for dragging? If you try to drag eg. title DbGate in title bar, does it work ?

**Comment by janproch** [comment]
Duplicate to #281

**Comment by janproch** [comment]
It is fixed in newest BETA 5.0.0-beta.7

**Comment by janproch** [comment]
Released in 5.0.0
