### ISSUE TITLE
FEAT: More Data Types

### ISSUE THREAD

**Issue by susnick** [dbgate/dbgate#285]
The data types should be more inline with the server being connected to. I know you can type whatever type in DataTypeEditor, but for those people that do not know all the option this would be handy. These should be provided by the plugin I would expect, rather than hard coded in the DataTypeEditor component. Have you given any thought to including fields for precision and scale? (eg MySQL Decimal(<precision>,<scale>))

**Comment by janproch** [comment]
More data types (specific for SQL dialect) are added in 5.0.0.

In dropdown, there are only predefined types, custom defined types are not offered.

Decimal precision can be edited directly in type (eg. choose decimal(10,2) , than update precision/scale for your needs)
