### ISSUE TITLE
BUG: Cant Click Sidebar Menu Item

### ISSUE THREAD

**Issue by Gwill** [dbgate/dbgate#287]
**Describe the bug**
Cant Click Sidebar Menu Item.

**To Reproduce**
1. Click on sidebar item.
2. No response

**Expected behavior**
change content page

**Screenshots**
![image](https://user-images.githubusercontent.com/692980/169939126-b6309499-648d-4665-9fa8-cdf5b26d26bb.png)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version Version: 5.0.0
 - Install source installer
 - Type - Application
 - Database engine: All

**Comment by janproch** [comment]
Hm, I didn't catch this bug in BETA... Will be solved today about 21:00 GMT

**Comment by janproch** [comment]
Fixed in version 5.0.1
