### ISSUE TITLE
Showing coordinates on a map

### ISSUE THREAD

**Issue by misustek** [dbgate/dbgate#288]
bylo by skvělé, kdyby db gate uměl při vybrání souřadnice jejich polohu vizualizovat v mapě (např. OpenStreetMap). Skvěle je takto funkce zpracována v dbmouse a hodně ji používám. Rád bych na dbgate přešel, ale tato funkce mi chybí:-(

**Comment by janproch** [comment]
Great idea!

Jde ti jen o zobrazení, kde na každém řádku je latitude/longitude, nebo může být součástí zobrazení v mapě i sloupec typu GEOGRAPHY, připadně GEOJSON?

**Comment by misustek** [comment]
přiznám se, že nevím jaký je mezi tím rozdíl. Tak jak je to v db mouse, je to úplně OK.

**Comment by janproch** [comment]
Released in BETA, documented here: https://dbgate.org/docs/maps.html

**Comment by janproch** [comment]
Released in version 5.0.5
