### ISSUE TITLE
BUG: Cannot use SSH Tunnel after update

### ISSUE THREAD

**Issue by kevinongko** [dbgate/dbgate#291]
**Describe the bug**
After updating to 5.0.1, DBGate seems always forget to use SSH tunnel when connecting to remote server

**To Reproduce**
1. add new connection (Mariadb)
2. input all usual data on general tab
3. open SSH tunnel tab and tick the "use SSH tunnel" checkbox
4. set SSH authentication to "key file"
5. add login user and private key
6. press "test" button and it show connection success "connected"
7. press save, connection saved
8. press connect, nothing happen and error shown "access denied for user user@host (using password: YES)"
9. edit said connection, go to SSH tunnel tab, the checkbox already unticked and all config gone in that tab

**Expected behavior**
Connected and show database on remote server

**Screenshots**
Test success
![DbGate_FAPfDbXhbR](https://user-images.githubusercontent.com/15880638/170722525-faa44a2d-635e-4677-8224-e6d00f0af9ee.png)

Error when connected
![2SNv7mXcMG](https://user-images.githubusercontent.com/15880638/170722740-6fa5941f-07f3-4633-85ee-9289d864e6b5.png)

SSH tunnel config gone
![DbGate_iZe19qOH2B](https://user-images.githubusercontent.com/15880638/170722765-1307e27f-a91a-451c-8f7a-2a66b398d13e.png)

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version 5.0.1
 - Install source installer
 - Type - Application
 - Database engine: Mariadb

**Comment by tvarsis** [comment]
I got the same issue. Just to add to your description, the port 22 is also hard to change on the SSH tunnel. If you try to use backspace, it will just revert to 22, so the only way is to enter a different port, and then in the end delete 22 part. But settings are not saved as per initial description.

**Comment by janproch** [comment]
Thanks, good catch!

Fixed in hotfix release 5.0.2

Problem with problematic editing of port 22 will be fixed in next regular release

**Comment by kevinongko** [comment]
It works now, thanks for the hotfix 👍
