### ISSUE TITLE
FEAT: Support caching_sha2_password plugin for MySQL 8

### ISSUE THREAD

**Issue by tamalsaha** [dbgate/dbgate#293]
**Is your feature request related to a problem? Please describe.**
mysql 8 use caching_sha2_password as default auth plugin . But I was able to login via native_mysql_password as a auth_plugin. So I had to create a user using native_mysql_password or I have to alter existing user to use native_mysql_password .

**Describe the solution you'd like**
Sounds like the mysql driver needs to be updated.

**Describe alternatives you've considered**

**Comment by janproch** [comment]
I have upgraded MySQL driver to newest version in BETA could you please test, whether it helped?

**Comment by janproch** [comment]
Upgraded mysql driver is released in version 5.0.3. If this doesn't help, please reopen this ticket

**Comment by tamalsaha** [comment]
We tested it. It works! Thanks for looking into this quickly.
