### ISSUE TITLE
Bottom bar does not correspond with active tab

### ISSUE THREAD

**Issue by superDuperCyberTechno** [dbgate/dbgate#294]
The bottom bar does not reflect the active tab's database. It represents the currently clicked database in the sidebar.

**To Reproduce**
1. Open a table.
2. Connect to a new database and open a table therein.
3. Select the tab for the previous table.

**Expected behavior**
When clicking the tab created in step 1, the bottom bar should represent its database.

**Version Information (please complete the following information):**
 - OS: Arch Linux
 - App Version: 5.0.2
 - Install source: AppImage (not through AUR)
 - Type: Application
 - Database engine: PostgreSQL

**Comment by janproch** [comment]
Fix released in 5.0.3
