### ISSUE TITLE
My operating system is Manjaro, the installed version of DBGate is as shown in the first picture, but when I call my file manager it is garbled, as shown in the second picture, what should I do?

### ISSUE THREAD

**Issue by huanzi94** [dbgate/dbgate#295]
![image](https://user-images.githubusercontent.com/31958917/172863777-a7e82e2e-c7dd-4553-a929-8d13ac909367.png)

![image](https://user-images.githubusercontent.com/31958917/172864048-7e140a5d-fad1-4b4c-84e6-9fd9ea82fb8d.png)

**Comment by superDuperCyberTechno** [comment]
Exactly how do you make this happen? Please explain the steps you took to make this happen.

**Comment by zerofill** [comment]
I'm on Manjaro and mine is normal. Xfce... I installed it from AUR though.
https://aur.archlinux.org/packages/dbgate-bin

**Comment by markovic-nikola** [comment]
Manjaro (Gnome) user here, everything works fine for me.
Looking from your screenshot, I see you have some custom theme, it might be related with that.

**Comment by janproch** [comment]
Still problem?

I am closing this, please reopen it if needed

**Comment by MrJuliuss** [comment]
Hi, i got the same problem on Ubuntu 23.10, Gnome 45.0. 
Installed with Snap

**Comment by ProjectInfinity** [comment]
> Hi, i got the same problem on Ubuntu 23.10, Gnome 45.0. Installed with Snap

Are you using any theme?

**Comment by MrJuliuss** [comment]
> > Hi, i got the same problem on Ubuntu 23.10, Gnome 45.0. Installed with Snap
> 
> Are you using any theme?

The default Ubuntu build-in theme

**Comment by ProjectInfinity** [comment]
Can you show your gnome tweaks appearance settings and the broken file picker?

**Comment by MrJuliuss** [comment]
Sure ! 

![image](https://github.com/dbgate/dbgate/assets/3630208/00887a76-c53a-4e67-b27e-56cef9a1af32)

![image](https://github.com/dbgate/dbgate/assets/3630208/68bcd617-03eb-4bea-9dc4-16885fabf82f)

**Comment by ProjectInfinity** [comment]
Thanks. What about the section regarding fonts in gnome tweak?

**Comment by MrJuliuss** [comment]
> Thanks. What about the section regarding fonts in gnome tweak?
> […](#)
> On 22 Nov 2023 at 16:55 +0100, Julien Richarte ***@***.***>, wrote: Sure ! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

![image](https://github.com/dbgate/dbgate/assets/3630208/b0bda9d4-a156-47c7-8c9b-a93eabf1ee8f)

**Comment by ProjectInfinity** [comment]
@MrJuliuss I installed Ubuntu 23.10 in a fresh virtual machine and experienced the same bug. It seems to be a snap related issue, I would suggest using either the Deb file or the AppImage (in which case you need to install fuse2fs and mark it as an executable to run it).

The issue does not seem to be DbGate related.
