### ISSUE TITLE
FEAT: Support for native SQL as default value inside yaml files 

### ISSUE THREAD

**Issue by otaprochazka** [dbgate/dbgate#296]
Would be nice to have it to be able to define defaut values like CURRENT_TIMESTAMP

**Comment by janproch** [comment]
Added into ALPHA version, can be expressed as:
default: current_timestamp 

Documentation to table YAML files is here:
https://dbgate.org/docs/dbdeploy.html

**Comment by janproch** [comment]
Released in version 5.0.5
