### ISSUE TITLE
FEAT: Publish Linux version as flatpak

### ISSUE THREAD

**Issue by rugk** [dbgate/dbgate#297]
**Is your feature request related to a problem? Please describe.**
A simple and easy way to install applications on Linux, which alos work cross-distro in a good way.

**Describe the solution you'd like**
It would be nice if you could publish this as a [flatpak](https://flatpak.org/) on [flathub](https://flathub.org/) e.g.

Flatpaks are a new software distribution mechanism for Linux distros, can thus installed on any distro and are easy to update. Thy are easy to install and work on all Linux distros.
Also, if you publish it on _FlatHub_ you may grow your user base given many distros include that and it is a common software source, so your app can be discovered more easily. 

Here is [how to get started](http://docs.flatpak.org/en/latest/getting-started.html).

**Describe alternatives you've considered**
There is also “snap“, but I would highly advise against using it.

I personally would prefer flatpak. Because in contrast to snap, you can also self-host it, so you stay in control, and it is widely supported. (snap is not so nice to setup in many distros and snap's security depends on AppArmor, which is not always available in many distros)
Also – in contrast to snaps – flatpaks do not only claim to be distro-independent, but [actually are](https://kamikazow.wordpress.com/2018/06/08/adoption-of-flatpak-vs-snap-2018-edition/)n [and they are widely adopted](https://kamikazow.wordpress.com/2017/02/09/adoption-of-flatpak-vs-snap/).
Furthermore even [Linux Mint criticizes snap](https://blog.linuxmint.com/?p=3906), because you cannot self-host a snap server as it is proprietary and (thus) also cannot modify the packages that are served centralized by Ubuntu.

**Comment by joaolucasgtr** [comment]
Totally agree with this.

Also, snaps takes forever to startup, which is annoying too!

**Comment by markovic-nikola** [comment]
+1

Currently, I'm using DbGate through the AUR, but the version is outdated (v5.0.6).

**Comment by asjur** [comment]
Is there an update on this? We have snap, but not flatpak. :grimacing:

**Comment by ProjectInfinity** [comment]
@janproch Any chance for either creating a flapak bundle or publishing on flathub?

Snaps really isn't widely supported and are potentially dangerous to use outside of Ubuntu.

**Comment by janproch** [comment]
@ProjectInfinity Thank you for trying it. I am working on it now

**Comment by janproch** [comment]
flathub integration PR https://github.com/flathub/flathub/pull/3955

**Comment by ProjectInfinity** [comment]
How is this going? What's the blockers?

**Comment by janproch** [comment]
The biggest problem is that fork() function doesn't work correctly when distributed as flatpak

**Comment by rugk** [comment]
Another tip as this uses Electron AFAIK: Many Electron apps (based on the Chromium engine) use [Zypak](https://github.com/refi64/zypak) for sub-sandboxing. I did not yet fully understand how it works, but maybe linking https://github.com/flathub/com.vscodium.codium/issues/55 may help and you can see the links/linked implementation there.

**Comment by rugk** [comment]
> The biggest problem is that fork() function doesn't work correctly when distributed as flatpak

I have no idea of Electron development and only a grasp of flatpak development, but [I've tried to ask ChatGPT about that](https://chat.openai.com/share/5d591717-90ca-4167-85f7-087fdf947355) ([before summary if you want to continue](https://chat.openai.com/share/5d591717-90ca-4167-85f7-087fdf947355)). It basically recommend other strategies for offloading work (IPC or so) or when regarding Electron it suggests Web Workers specifically e.g.

<details>
<summary>Summary by ChatGPT</summary>
Certainly, here's a summarized overview of the proposed solutions to handle the `fork()` issue in Electron-based applications within a Flatpak context:

1. **IPC Mechanisms**: Utilize Electron's IPC mechanisms to enable communication between the main process and renderer processes. This allows for parallelism and task distribution without relying on direct process forking.

2. **Background Processes and Workers**: Leverage background renderer processes and Web Workers to handle tasks that would have been suited for separate child processes created with `fork()`.

3. **Process Offloading**: Distribute tasks across existing processes using well-defined communication patterns instead of creating separate processes with `fork()`.

4. **Architectural Adaptation**: Design your application's processes and communication channels to be compatible with sandboxed environments, aligning with the constraints of platforms like Flatpak.

5. **Web Technologies**: Leverage modern web technologies like Web Workers, asynchronous programming, and event-driven architectures to handle background tasks and maintain application responsiveness.

6. **Task Delegation and Management**: Manage tasks by delegating them to appropriate components or modules, using asynchronous patterns, and coordinating tasks without relying heavily on traditional process-based concurrency.

By adopting these approaches, you can effectively work within the sandboxed environment of Flatpak while avoiding the use of the `fork()` function in your Electron-based application.
<details>

**Comment by ProjectInfinity** [comment]
The big issue I am finding is that the subprocesses seem to die, and I am not quite sure why. Maybe it is related to Zypak but I do not know enough about it to confirm.

**Comment by refi64** [comment]
Unfortunately I can't try this out myself, because Electron versions <18.3.2 don't work on my system due to lack of support for 16k kernels. That being said, is there anything interesting logged? If not, does setting `ZYPAK_DEBUG=1` show anything?

**Comment by ProjectInfinity** [comment]
> Unfortunately I can't try this out myself, because Electron versions <18.3.2 don't work on my system due to lack of support for 16k kernels. That being said, is there anything interesting logged? If not, does setting `ZYPAK_DEBUG=1` show anything?

Hi, sorry for the slow response it's been quite busy. Attached you will find the log file when running the built flatpak using ZYPAK_DEBUG=1. Unfortunately, I am not familiar enough with zypak to immediately tell you if there is an obvious problem with the log.

[zypak.log](https://github.com/dbgate/dbgate/files/13802663/zypak.log)

**Comment by janproch** [comment]
Second attempt to publish to flathub repo: https://github.com/flathub/flathub/pull/5240

**Comment by ProjectInfinity** [comment]
> Second attempt to publish to flathub repo: [flathub/flathub#5240](https://github.com/flathub/flathub/pull/5240)
> 
> Subprocess die issue seems to be fixed with upgrading electron

I can attest to the issues I experienced being fixed, so far it seems to work just like the AppImage.

Great that electron update fixed it because debugging zypak was not simple. :+1:

**Comment by janproch** [comment]
Flatpak version published on flathub: https://flathub.org/apps/org.dbgate.DbGate

**Comment by rugk** [comment]
Awesome! A download button on https://dbgate.org/ would be great, too.

**Comment by ProjectInfinity** [comment]
> Awesome! A download button on https://dbgate.org/ would be great, too.

Already is!
![image](https://github.com/dbgate/dbgate/assets/593870/906287cd-fd0c-4b20-9d63-7a129f583bd9)
