### ISSUE TITLE
BUG: Postgres boolean columns don't filter correctly

### ISSUE THREAD

**Issue by jamerst** [dbgate/dbgate#298]
**Describe the bug**
Postgres boolean columns can only be filtered by entering "0x0" or "0x1". Entering "false" or "true" results in the error "operator does not exist: boolean = integer".

**To Reproduce**
1. Open a Postgres table with a column of type "boolean"
2. Add a filter on the column of "true" or "false"

**Expected behavior**
The column should be filtered to only contain the value entered.

**Screenshots**
![image](https://user-images.githubusercontent.com/10601770/173197093-bfb29316-f636-4aae-af83-49671c6ca702.png)

**Version Information (please complete the following information):**
 - OS: Linux (Fedora)
 - App Version: 5.0.3
 - Install source: AppImage
 - Type - Application
 - Database engine: PostgreSQL 13.2

**Comment by janproch** [comment]
Fixed in version 5.0.5

Thanks for reporting
