### ISSUE TITLE
BUG: Can't change theme or font size in Editor Themes

### ISSUE THREAD

**Issue by EvandroLucas** [dbgate/dbgate#300]
**About the bug**
The Editor Theme section won't work. Neither the (editor) theme nor the Font Size settings change anything, and both will reset if you close the panel and open it again. 

**To Reproduce**

1. Go to 'View/Change Theme/ Editor theme'
2. Try to change the Theme or the Font Size
3. The changes won't be previewed nor applied.

**Expected behavior**
The editor theme and the font size should both change.

**Version Information:**
 - OS: Windows
 - App Version : 5.0.5, Build date: 2022-06-13
 - Install source : installer
 - Type - Application
 - Database engine: PostgreSQL

**Comment by mistermaxis** [comment]
I had the same issue. 
Version Information:
- OS: Linux Mint 20.3.
- App Version: Version: 5.0.5, build date: 2022-06-13
- Install source: installer
- Type: application
- Database engine: PostgreSQL
- Theme in use: dark theme

**Comment by janproch** [comment]
Fixed in last BETA

Thanks to all for alerting, I wasn't able to replicate this before

**Comment by janproch** [comment]
Fixed in 5.0.7
