### ISSUE TITLE
FEAT: Auto refresh, reload table every x second 

### ISSUE THREAD

**Issue by martinandersen3d** [dbgate/dbgate#303]
**Is your feature request related to a problem? Please describe.**
When I manipulate the database in my code editor or terminal and, I would like dbGate to automatic refresh, so I can see the changes - without hitting Alt+tab and refresh-hotkey (too many times a day)

**Describe the solution you'd like**

Need to have:
- It should autorefresh the table when "Auto-refresh" is enabled.
- User can specify the refresh interval in seconds/milliseconds 

Nice to have:
- hotkeys for the "Auto-refresh toggle"

**Describe alternatives you've considered**
- none

I use this often in other programs, where I get kind of a "live" experience when it reloads the table every second (usually just the first 1000 records).

This feature is in DBeaver, HeidiSql, NoSQLbooster and more...

Example from DBeaver:
![image](https://user-images.githubusercontent.com/19984581/175838666-8c871949-7975-4c70-9d18-426eaec7a206.png)

**Comment by janproch** [comment]
Good idea, thanks. Will be added into next version

**Comment by qlaffont** [comment]
Is it possible to add Ctrl + R to make refresh too ^^". Thanks !

**Comment by martinandersen3d** [comment]
Thanks 🙏

**Comment by janproch** [comment]
Implemented in newest BETA

Added shortcut Ctrl+R for refresh (now Ctrl+U is mapped for Revert row changes, which was formerly Ctrtl+R)

Ctrl+Shift+R is used for toggle auto refresh
Default auto refresh interval can be configured in settings

![Screenshot 2022-06-30 at 10 09 53](https://user-images.githubusercontent.com/2543891/176627083-0603a80c-2db4-4c81-9399-4158c064eca1.png)

**Comment by qlaffont** [comment]
Thanks a lot ! It will save me a lot of time ^^

**Comment by janproch** [comment]
Released in 5.0.7
