### ISSUE TITLE
QUESTION: Expressions in Query Designer

### ISSUE THREAD

**Issue by michaelhq** [dbgate/dbgate#306]
Hello

Thank you for DbGate! Your application is something I was looking for several years! I plan to use it for teaching economic students in creating simple SQL Select queries. Primarily with the query designer, the most important feature for me in that case in any database management software.

I have a question about the query designer. How can I put an expression in the first column of the designer (bottom part)? E.g. a multiplication of two numeric columns of a table. Or is it not possible currently and planned for a next release?

Further, when I switch to the SQL view in the query designer, there is no possibility to edit the code, correct?

Kind regards,
Michael

**Comment by janproch** [comment]
Hello

thank you for the feedback

Adding custom expressions is now not possible, but it is very reasonable feature, I will try to add it to next release

Editing generated query is not possible (query designer is one-way, two way designer, which is able to reflect changes in SQL code is much more complex task). You could use "Open SQL" button, which allows you edit the generated query, whithout propagating changes back to designer

**Comment by janproch** [comment]
Implemented in current BETA

**Comment by michaelhq** [comment]
Works like a charm! Thank you very much!

![grafik](https://user-images.githubusercontent.com/11134268/179393016-9d117473-9518-4f60-8192-26c3cccf077a.png)

![grafik](https://user-images.githubusercontent.com/11134268/179393018-a1048ae3-7e30-400d-bf7a-28da9e7018f0.png)

![grafik](https://user-images.githubusercontent.com/11134268/179393024-d6246636-b7f7-44da-881e-c16458e33fe1.png)

**Comment by janproch** [comment]
Thanks for the test!

**Comment by janproch** [comment]
Released in version 5.0.8
