### ISSUE TITLE
QUESTION: How to change font in SQL editor?

### ISSUE THREAD

**Issue by nickleeh** [dbgate/dbgate#308]
**Details:**
I'd like to change SQL editor font, the current font is "Fira Code", I'd like to change to "IBM Plex Mono". But didn't find any way to change in settings. Is it possible to change, without switching to another theme?

**Version Information [might be relevant to your issue]**
Operating System: macOS 12.4, M1
App Version [help -> about]: 5.0.6

**Screenshot [if appropriate]**:
A screenshot of the app if that helps

**Comment by nickleeh** [comment]
I just found that I can change the font by editing `~/.dbgate/plugins/dbgate-plugin-wg-theme-dark/dist/frontend.js`
=> themeCss => font-family.

This is a work around, but I hope there could be a setting option in menu or in `~.dbgate/settings.json`.

**Comment by janproch** [comment]
I added posibility to change font in theme settings (in BETA)

**Comment by janproch** [comment]
Released in version 5.0.8
