### ISSUE TITLE
FEAT: Ability to duplicate/clone entries

### ISSUE THREAD

**Issue by dcroal** [dbgate/dbgate#309]
It would be very helpful to be able to duplicate/clone existing table rows (preferably without keys) to speed up data entry.

I tried to use copy without headers, new row, paste as a workaround but in this case the NULL entries are not pasted correctly so I get many Incorrect date value: '(NULL)' errors, which can only be corrected by individually setting these to NULL.

Copy as SQL Insert works but I need to manually edit the primary key to NULL before running the query.

**Comment by dcroal** [comment]
I downloaded the v5.0.7-beta.4 today and this feature works perfectly.
Thank you so much.

Dave Croal
em: ***@***.***
ph: (416) 729-9450

**Comment by dcroal** [comment]
I downloaded the v5.0.7-beta.4 today and this feature works perfectly. Thank you so much.

**Comment by janproch** [comment]
Thanks for test

Released in version 5.0.7
