### ISSUE TITLE
BUG: Filtering with datetime-columns does not work with filter types after (>=) and before (<=)

### ISSUE THREAD

**Issue by michaelhq** [dbgate/dbgate#311]
**Describe the bug**
Filtering with datetime-columns does not work with filter types after (>=) and before (<=) etc.

**To Reproduce**
1. Open a table with a datetime column
2. Click on filter and select before, enter a date as described in the documentation
3. field with filter value is red and not green, data ist not filtered

**Expected behavior**
rows should be filtered

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11134268/177607981-0ef32230-c1b2-4bcd-b17f-1c9f98d4ba8b.png)

It works with a date only, without <= or any other operator
![grafik](https://user-images.githubusercontent.com/11134268/177608166-ed275bc3-e43e-4c4f-8e0e-596ae297af8d.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.06
 - Install source: Docker and Windows
 - Type - web and desktop
 - Database engines: MariaDB and Microsoft SQL

**Comment by janproch** [comment]
Good catch, thanks. Will be fixed in next version

**Comment by janproch** [comment]
Supported syntax is:

OP can be < <= > >=

OP YYYY
OP YYYY-MM
OP YYYY-MM-DD
OP YYYY-MM-DD HH:mm
OP YYYY-MM-DD HH:mm:ss

eg. filter >= 2000 will filter rows with year 2000 or bigger

**Comment by janproch** [comment]
Added in version 5.0.7
