### ISSUE TITLE
BUG: Mongo Query in web version not working

### ISSUE THREAD

**Issue by holotrack** [dbgate/dbgate#312]
I setup DBGate behind Caddy auth portal. For MySQL everything working properly but when i try to execute query for MongoDB query is starting but its never ends:

**To reproduce**

Setup DBGate on server
Connect via web browser
Click on mongodb connection
Try to execute query

**Expected behavior**
query is executed and giving back data

**Screenshots**
![image](https://user-images.githubusercontent.com/100580892/177777497-d4600312-ef09-41ac-a76a-aa7bef19deb3.png)

**Version Information (please complete the following information):**
 - official Docker image dbgate/dbgate i checked alpine version and its that same
 - Version: 5.0.6
 - Build date: 2022-06-27
 - Docker
 - Type - Web
 - Database engine: Mongo
 
 
 Dont know if its important but on desktop app same connection is working properly.

**Comment by janproch** [comment]
Fixed in version 5.0.7

**Comment by artem-zherdiev-ingio** [comment]
Hi, @janproch. In this setup currently we are getting other error. We are trying execute read query in readonly mode and getting "Connection without read-only sessions is read only". Could you help to understand why? Thank you!
