### ISSUE TITLE
[BUG] ssh tunnel not working

### ISSUE THREAD

**Issue by giancarloerra** [dbgate/dbgate#315]
Hi

I see someone else asked for something similar, anyway that issue has never been updated or closed. I'm trying a mysql connection via ssh tunnel, and it fails:

Creating SSH tunnel to ***, using local port 10000
(node:1253845) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `dbgate --trace-deprecation ...` to show where the warning was created)
Error
    at e.exports (/tmp/.mount_dbgatePuj8fl/resources/app.asar/packages/api/dist/bundle.js:9:85138)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async process.<anonymous> (/tmp/.mount_dbgatePuj8fl/resources/app.asar/packages/api/dist/bundle.js:187:409014)

Any hint? I do hope to get this working, by far best looking and lighter sql gui I found on Linux!

**Comment by giancarloerra** [comment]
UPDATE: I tried another one of my VPS, same provider and configuration, and it works perfectly, so is something about this specific case. I double checked and triple checked credentials. Is there any way to have some sort of more detailed logging and/or some more user friendly error message to understand at least at what point does this happen?

**Comment by giancarloerra** [comment]
More update: I did many more tests. Installing from .deb and I get same results. Installing from Snap, interesting enough neither SSH tunnels work, both producing same error about that bundle.
I then tried as a test running from root, and same result (to be noticed that snap I think sandboxes is, and root never connected to either SSH machines).
I then also tried running from docker, it would not start using docker-compose included file (after mapping to local folder) saying it couldn't find this bundle.js
Not sure if this helps, I hope so. I use Dbeaver as well, and it works without problems with SSH tunnel to same machines.

Is there a way to have dbgate producing a more verbose/useful output when executed? From tests I ran, it definitely seems the SSH connection is not handled correctly in some cases, but is impossible to know without a more verbose output.

**Comment by giancarloerra** [comment]
As a further testing, I'm running directly the development environment, and same problem happens, but hopefully more clear error for you:

0] Error
[0]     at connectUtility (/home/giancarloerra/Downloads/dbgate/packages/api/src/utility/connectUtility.js:55:13)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0]     at async process.<anonymous> (/home/giancarloerra/Downloads/dbgate/packages/api/src/proc/connectProcess.js:23:20)

I tried investigating but I'm no expert of JS. Tracing it back it seems to originale from sshTunnel.js where callForwardProcess gets a msgtype error.

**Comment by giancarloerra** [comment]
I've more testing. I see you use https://github.com/Stocard/node-ssh-forward for the ssh.

I tried connecting to same server with that package, and it works without problems. I did using only arguments endport, endhost, username, password (that is what I'm doing as well in dbgate, connecting with user/pass to a custom port ssh).

So the original package works, must be something (arguments?) in dbgate.

**Comment by janproch** [comment]
Hi @giancarloerra ,

thank you very much for you investigation.
Could you please provide me the testing script with node-ssh-forward, which works? Or if you see some differences between this script and dbgate SSH code in 
https://github.com/dbgate/dbgate/blob/master/packages/api/src/proc/sshForwardProcess.js , please let me know
I will also improve logging into next version

Thanks

**Comment by giancarloerra** [comment]
Hi just to let you know I tried today another db client made in Electron, Beekeper Studio. 

SSH tunnel to my VPS works over there as well. They have a community edition on github, maybe something to check

 how they do it? Your client looks much nicer and much more complete :-)

I also double checked the configuration of the servers, tcp forwarding is enabled in sshd config, so I just can't understand where is the problem...without a full detailed SSH output (the same as ssh -v) is going to be hard to understand.

**Comment by janproch** [comment]
Hi @giancarloerra,

I have added SSH tunnel error logging to master branch. If you run it from source again, there should be additional error message

Also, when you use `yarn start:api:debug:ssh` instead of `yarn start:api` or `yarn start:app:debug:ssh` instead of `yarn start:app`, there will be additional logging from SSH for node-ssh-forward package

Alternatively, `yarn start:api:debug` or `yarn start:app:debug` will enable all debugging messages

**Comment by giancarloerra** [comment]
That's brilliant, I already got finally some useful error message:

Error creating SSH tunnel connection: Handshake failed: no matching client->server HMAC

I'm investigating now and will report: I believe there's an option that must be enabled (or not disabled if enabled by default) for the connection to work. Will update once I have it fixed and verified.

**Comment by giancarloerra** [comment]
That's brilliant, I already got finally some useful error message:

Error creating SSH tunnel connection: Handshake failed: no matching client->server HMAC

HMAC need to be enabled in SSHD server, or DBgate cannot connect to it. Other clients can, is it because hmac is embedded as mandatory? Anyway the SSH debug option solved the problem, pointing out what was.

I can now connect to the VPS :-) Thanks a lot for your help!

**Comment by giancarloerra** [comment]
Thanks, I've now changed it and aligned it with others, but indeed is a good idea to not have it maybe mandatory :-) Thanks once again for your assistance, very happy to be using DBgate already.

**Comment by janproch** [comment]
Released in 5.0.7

Thanks for your help with making dbgate better
