### ISSUE TITLE
FEAT: Add multiple filter colums in query designer to create an OR between different rows of attributes

### ISSUE THREAD

**Issue by michaelhq** [dbgate/dbgate#321]
Thanks again for the really great software, I like it very much! 

**Is your feature request related to a problem? Please describe.**
With one filter column on the right bottom side of the query designer, only an AND filter statement is possible between different data columns.

**Describe the solution you'd like**
add two more filter columns to allow an OR between data columns, e.g. if you have filter criteria in the first filter column and in a second filter column on another row (different attribute) criteria, the two criteria are combined with an OR. all criteria in the same filter column are combined with an AND (as it is now)

**Describe alternatives you've considered**
add an (+) button to add more filter columns to the right in the query designer

**Comment by janproch** [comment]
Excelent idea, thanks!

I have implemented it into current BETA (variant 2)

**Comment by michaelhq** [comment]
Works perfectly! Thank you very much!

![grafik](https://user-images.githubusercontent.com/11134268/179393107-aca5d91e-64bb-4f82-a9ed-e621a0eb036e.png)

Perhaps add a button for group filter too, when a grouping is active.

**Comment by janproch** [comment]
Added also group OR filter

Thanks

**Comment by janproch** [comment]
Released in version 5.0.8
