### ISSUE TITLE
BUG: Query doesn't load after 1 hour idle (web version demo.dbgate.org)

### ISSUE THREAD

**Issue by janproch** [dbgate/dbgate#323]
When I am editing a query against Relational dataset repo for ~1 hour and click Execute, sometimes I do not get any result even though the query is something fast to evaluate like "select 1". The workaround that I use is to simply refresh the web page. My original hypothesis was that I have to adjust interactive_timeout or wait_timeout variables, but they are already set to 24 hours. Is there something that I can do to debug the issue and fix it?

**Comment by janproch** [comment]
Probably problem with event stream

![image](https://user-images.githubusercontent.com/2543891/179410169-83f8ffa5-63f5-4353-bf83-4ee426ff9e1f.png)

**Comment by jan-motl** [comment]
Yes. Console output:
<img width="1332" alt="sc" src="https://user-images.githubusercontent.com/96427190/179566351-241a1c5a-f78d-48b6-9d71-f68e6b4e9d8c.png">
On execute trigger, network tab didn't record any new traffic.

**Comment by janproch** [comment]
There was serious problem with SSE stream. This is now fixed. I hope it will solve also this issue.

Release in BETA, it is on demo.dbgate.org

**Comment by jan-motl** [comment]
I tested it on demo.dbgate.org and the issue is resolved. Thank you Jan!

**Comment by janproch** [comment]
Released in 5.0.9
