### ISSUE TITLE
BUG: Unsigned column doesn't work correctly.

### ISSUE THREAD

**Issue by zslucky** [dbgate/dbgate#324]
**Describe the bug**
Mysql create unsigned column got error, the generate SQL is 
`ALTER TABLE test_user ADD test INT AUTO_INCREMENT UNSIGNED NULL;`
which should worked as 
`ALTER TABLE test_user ADD test INT UNSIGNED AUTO_INCREMENT NULL;`

As `unsigned` should follow data type.

**To Reproduce**
1. Go to any table structure
2. Click add new column, and check the `is auto increment` and `is unsigned`
3. Save column and Save all.

**Expected behavior**
`unsigned` key word should follow the data type, then it can work correctly.

**Screenshots**
<img width="617" alt="image" src="https://user-images.githubusercontent.com/15725589/179757807-e8cf5692-534d-4dc0-965b-20006b8ce39b.png">

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version Version: 5.0.6
 - Install source: NPM
 - Type - Web
 - Database engine: mysql 5.7

**Comment by janproch** [comment]
Good catch, thanks. Will be fixed in next bugfix release

**Comment by janproch** [comment]
Fixed in 5.1.0
