### ISSUE TITLE
FEAT: Option to skip Save changes dialog

### ISSUE THREAD

**Issue by dcroal** [dbgate/dbgate#329]
Would it be possible to have the option to skip the Save changes dialog when saving? This would save one keyboard press or mouse click during data entry. Thanks.

**Comment by janproch** [comment]
Good idea, I will add checkbox to not show this dialog again and also option in settings dialog. Probably I will deal with this after currently developed big feature is released.

**Comment by janproch** [comment]
Released in 5.1.0
