### ISSUE TITLE
FEAT: Dropdown columns in import

### ISSUE THREAD

**Issue by giancarloerra** [dbgate/dbgate#330]
To make the IMPORT procedure a bit more straightforward, would be nice, when mapping columns from source to destination, to have a dropdown of the fields available.

Or in alternative to have a preview where I can choose if I want to see the Source or Destination (to check column names without leaving the script window).

But dropdown sounds probably like the better choice. Otherwise one has to remember the names of all the columns.

Thanks for your amazing software!

**Comment by janproch** [comment]
Nice idea, thanks for it.

I will surely implement it (the dropdown variant), but not with the highest priority
