### ISSUE TITLE
FEAT: Keyboard navigation suggestions

### ISSUE THREAD

**Issue by dcroal** [dbgate/dbgate#331]
Pressing Enter while the current cell is highlighted moves down to the next row. I would prefer Enter to put the cell into edit mode instead but others may prefer the current behavior.

Editing a row using the keyboard is difficult for me. After changing data in a cell, pressing Tab does not advance to the next cell. Right-arrow does not advance to the next cell either. It is necessary to click on the next cell in order to edit the information. Is it possible to have Tab advance to the next cell while editing a row?

**Comment by janproch** [comment]
Thanks for the suggestion

I implemented it as you suggested, it will be released in next version, probably next week

**Comment by janproch** [comment]
Released in 5.1.0
