### ISSUE TITLE
FEAT: UX improvement - connect on click?

### ISSUE THREAD

**Issue by markovic-nikola** [dbgate/dbgate#332]
**Is your feature request related to a problem? Please describe.**

Currently, clicking on one of the connections in the (top) left sidebar will open a connection edit tab if DbGate is not connected yet.
I find it unnecessary to always open this additional tab on start, or having to right-click and then click connect in order to bypass this behavior.

**Describe the solution you'd like**

Instead of opening edit connection tab, app should connect on single click.
Users still have option to edit a connection by using right-click -> _Edit_.

**Describe alternatives you've considered**

Or maybe improve a double click which already works, but it should not open edit connection tab in this case.

**Comment by janproch** [comment]
Thanks fir this feedback!

I have several times changed behaviour of this, to achieve the best UX.

Now there is posibility to configure behaviour which you describe, in menu View/Settings/Actions/Connection click.
I will surely implement alternative which you proposed, no to open connection tab after double click (opening connection tab must be delayed)

However, I am not sure, which setting is better as default option when clicking connection:
- open tab with connection
- connect to database server

For advanced user it is surely better to connect server after clicking connection. But from my point of view, this could be confusing for beginner, especially if there are problems with connection and connect to server fails.
And on opened connection tab, there is "Connect" button, which has clear meaning.

Any feedback on this is welcome!

**Comment by vishnu-buildd** [comment]
Thank you the awesome tool. The 'Connections' screen is a little annoying for me. I would like to make it go away after I make a connection. Currently it shows the connections configs and a Disconnect button. A empty workspace with a message to pick a DB would be better I fell. This just adds a tab/noise when I ultimately end up choosing a DB i want after establishing connection.

**Comment by markovic-nikola** [comment]
@janproch  _View/Settings/Actions/Connection_ and/or _double click_ definitely fulfills my need as a daily user 👍.
Regarding default option on single click, I will leave that up to you, or perhaps some other users can chime in.
If someone is using a database manager app, is that person really a beginner? 🤔
But I guess that's my subjective view at the end.

---

> Thank you the awesome tool. The 'Connections' screen is a little annoying for me. I would like to make it go away after I make a connection. Currently it shows the connections configs and a Disconnect button. A empty workspace with a message to pick a DB would be better I fell. This just adds a tab/noise when I ultimately end up choosing a DB i want after establishing connection.

@vishnu-buildd  The tool itself needs to be universal - what works for you doesn't mean it's working for me.
For example, I like it being shown there, as I'm constantly switching between different connections (different server environments).
In my mind, this could be solved by adding a settings option where people can toggle that part.
But I don't think it's related with this current issue, so feel free to create a _FEAT_ suggestion separately. 🙂

**Comment by vishnup95** [comment]
Understood. I thought it was mostly related to connection UX. I will start a seprate thread if needed.

**Comment by janproch** [comment]
@vishnu-buildd You would like to hide connection widget (1) or connection tab (2)?
You could hode connection widget by clicking on "Connections" title

![image](https://user-images.githubusercontent.com/2543891/181876585-cd796dcc-1b51-45aa-acc2-5f080eab7314.png)

**Comment by vishnu-buildd** [comment]
> @janproch _View/Settings/Actions/Connection_ and/or _double click_ definitely fulfills my need as a daily user +1. Regarding default option on single click, I will leave that up to you, or perhaps some other users can chime in. If someone is using a database manager app, is that person really a beginner? thinking But I guess that's my subjective view at the end.
> 
> > Thank you the awesome tool. The 'Connections' screen is a little annoying for me. I would like to make it go away after I make a connection. Currently it shows the connections configs and a Disconnect button. A empty workspace with a message to pick a DB would be better I fell. This just adds a tab/noise when I ultimately end up choosing a DB i want after establishing connection.
> 
> @vishnu-buildd The tool itself needs to be universal - what works for you doesn't mean it's working for me. For example, I like it being shown there, as I'm constantly switching between different connections (different server environments). In my mind, this could be solved by adding a settings option where people can toggle that part. But I don't think it's related with this current issue, so feel free to create a _FEAT_ suggestion separately. slightly_smiling_face

Understood @markovic-nikola . I thought I would keep the discussion here as it was UX of connection, but will make a separate issue if needed. 

@janproch The connections tab. I think it's mildly annoying to have it there after I make a connection. It's not a major issue in any way.

**Comment by janproch** [comment]
Thanks for your opinions

I changed default action on connection click to connect

**Comment by janproch** [comment]
Released in 5.1.0
