### ISSUE TITLE
BUG: Not the intent WHERE clause in the generated UPDATE SQL for updating any primary key value

### ISSUE THREAD

**Issue by donnySYG** [dbgate/dbgate#334]
**Describe the bug**
When updating a primary key, generate SQL feature should not use the modified value showed on screen in the where clause of the generated `UPDATE` SQL.

**To Reproduce**
1. Create a table with primary keys: `pk1`, `pk2`.
2. Insert a row of `pk1` = 1, `pk2` = 2
3. Modify `pk2` to 1
4. Generate SQL with `pk2` selected
5. The window "Generate SQL from data" shows the preview `UPDATE` SQL below

```sql
UPDATE `table` SET `pk2`=1 WHERE `pk1`=1 AND `pk2`=1;
```
---
**Expected behavior**
The generated SQL should like below, so I can update the exact row I expect.

```sql
UPDATE `table` SET `pk2`=1 WHERE `pk1`=1 AND `pk2`=2;
```

---
**Version Information (please complete the following information):**
 - OS: Windows
 - 5.0.9
 - installer
 - Type - Application
 - Database engine: MariaDB

**Comment by janproch** [comment]
Sorry, I can' replicate this. It works as expected for me

Just for clarification, you mean complex primary key with 2 columns (pk1, pk2)? As I know, all database systems allow only one primary keys per table

**Comment by donnySYG** [comment]
You can try the example below

```
CREATE TABLE `twopk` ( 
  `pk1` VARCHAR(11) NOT NULL,
  `pk2` VARCHAR(11) NOT NULL, 
  CONSTRAINT `PRIMARY` PRIMARY KEY (`pk1`, `pk2`)
);
```

![image](https://user-images.githubusercontent.com/60507988/183350823-1fbc6756-fa09-4a0c-9d52-2d8e608d6aef.png)

**Comment by janproch** [comment]
You used command "Generate SQL from data", which shoudl generate SQL from data, which you see. If you want to generate UPDATE script with your modifications, just click Save (Ctrl+S), there is dialog with update SQL

![image](https://user-images.githubusercontent.com/2543891/183495631-f549355a-0de8-4ef4-9a63-4f55eeaa9845.png)

**Comment by donnySYG** [comment]
Got it. Thanks for replying.
