### ISSUE TITLE
BUG: filter expressions samples table in documentation is broken

### ISSUE THREAD

**Issue by opensas** [dbgate/dbgate#339]
**Describe the bug**
The filter expressions samples table in documentation is broken.

**To Reproduce**
1. navigate to https://dbgate.org/docs/data-filtering.html
2. scroll down to Filter expressions - Examples section

**Screenshots**
![image](https://user-images.githubusercontent.com/481687/183678034-95c93029-08a9-4c02-8fc2-4387e7766b60.png)

**Comment by janproch** [comment]
fixed. Thanks for info
