### ISSUE TITLE
BUG: MySql Table Count is Incorrect

### ISSUE THREAD

**Issue by susnick** [dbgate/dbgate#342]
**Describe the bug**
table says "0 rows". There is 1 row

**Expected behavior**
Expect to be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/1975526/184464235-3cae2ff0-2222-4998-95db-bfa92e2eb217.png)

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version: 5.0.0-alpha.1
 - Install source: source
 - Type - Web/Application
 - Database engine: MySQL

**Comment by janproch** [comment]
This is only approximate number of rows obtained from information_schema.tables. Exact number of rows requires query (SELECT COUNT(*)), which could be slow and cannot be executed for all tables.

Maybe some notification, taht row count is not exact, could be added...

`
The number of rows. Some storage engines, such as MyISAM, store the exact count. For other storage engines, such as InnoDB, this value is an approximation, and may vary from the actual value by as much as 40% to 50%. In such cases, use SELECT COUNT(*) to obtain an accurate count.
`
