### ISSUE TITLE
BUG: Build Date is incorrect

### ISSUE THREAD

**Issue by susnick** [dbgate/dbgate#344]
**Describe the bug**
While getting the version to provide for bug report, I noticed that the Build date is wrong. I just built it, and it has a date over a year old. 

**Expected behavior**
I would expect the build date to be when the application is built.

**Screenshots**
![image](https://user-images.githubusercontent.com/1975526/184465201-7a982eee-f58f-431a-a550-5decd8e2bf95.png)

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 5.0.0-alpha.1
 - Install source Master branch
 - Type - Web/Application

**Comment by janproch** [comment]
This information is filled in build script in GitHub actions CI, https://github.com/dbgate/dbgate/blob/master/setCurrentVersion.js

If you run dbgate from sources, there is hardcoded value
