### ISSUE TITLE
BUG: The font size is too small

### ISSUE THREAD

**Issue by amirandev** [dbgate/dbgate#345]
The font size is too small I can't even change it more than 17px even manualy. 
It's unpossible to work that
![image](https://user-images.githubusercontent.com/73018912/184496323-5be7ebb3-c64a-42dd-a2db-ceb48e8257dc.png)

At least I need to set the font size manually
![image](https://user-images.githubusercontent.com/73018912/184496362-4a7cc6e2-3b17-472c-a815-bb20daf75c30.png)

**Comment by amirandev** [comment]
I tried to increase font size this way but it doesn't work. 
![image](https://user-images.githubusercontent.com/73018912/184496634-e3ec444f-4797-4f49-98c4-e646df776405.png)

**Comment by janproch** [comment]
Of course it is not problem to add bigger sizes. But you really need to enlarge only SQL editor font? 

If you want to enlarge all fonts in app, you could use menu Window/Zoom in

**Comment by amirandev** [comment]
> Of course it is not problem to add bigger sizes. But you really need to enlarge only SQL editor font?
> 


Yes sir, I need to enlarge only ediror font size. 

> If you want to enlarge all fonts in app, you could use menu Window/Zoom in
Zooming the whole windows doesn't make sense. That it will be worst to use. 

So I highly recoment to add an option to just set the editor font size as soneone wish.

**Comment by janproch** [comment]
OK, I will add options to make text yet bigger (custom size or just adding options, I will see)
