### ISSUE TITLE
QUESTION: Missing arguments in stored procedure

### ISSUE THREAD

**Issue by jameandreu** [dbgate/dbgate#348]
I don't know if I'm just noob or am I  just doing something wrong but I encounter this while using dbgate, I just downloaded and tested dbgate last week.

The parameters are missing whenever I view the stored procedure in dbgate, this has been the same case in all of the procedures in current and other databases but when I view the procedures in other apps like datAdmin the arguments are present. 

The upper image is in dbgate, the bottom one is in datAdmin.

![dbgate](https://user-images.githubusercontent.com/31077320/185909555-7a535135-e903-4633-9ff5-e6247eb40578.jpg)
![datadmin](https://user-images.githubusercontent.com/31077320/185909572-3b8f1c09-a1ab-43e4-a2b7-b61b764bc816.jpg)

**Comment by janproch** [comment]
Thanks for the feedback

Analysing of procedure parameters is not yet implemented, I will add it in future release, approx. in 2-3 months

**Comment by jeremy-hise** [comment]
Any ETA on this? It is the one thing that drove me back to WB.
Thanks for the software.
