### ISSUE TITLE
QUESTION: How to open .qdesign file?

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#349]
**Details:**
I create a new query design, I designed the query, I saved it to disk as test.qdesign, but I cann't open it again. File Open, doesn't have a .qdesign type.

**Version Information [might be relevant to your issue]**
Operating System: Windows 11
App Version [help -> about]:  5.1.0

**Screenshot [if appropriate]**:

Save
![image](https://user-images.githubusercontent.com/757749/186202502-32880645-f9ba-4466-bef3-2dcf2af3799a.png)

Open
![image](https://user-images.githubusercontent.com/757749/186201803-238303f2-3bfa-49bc-a308-14153e645454.png)

**Comment by janproch** [comment]
Now can be opened only when saved to .dbgate folder. I have added posibility open qdesign and perspective friles from open dialog and using drag & drop file from any location. Will be released in next version

**Comment by janproch** [comment]
Fixed in 5.1.1
