### ISSUE TITLE
FEAT: Hotkey support for Clear Filter

### ISSUE THREAD

**Issue by dcroal** [dbgate/dbgate#352]
I frequently need to clear all filters from a table, done now via right-click "Clear Filter". A hotkey for this would be useful. Thanks.

**Comment by dcroal** [comment]
Sorry for not being thorough, it was easy to set it myself using Help > Keyboard Shortcuts.

**Comment by janproch** [comment]
I have assigned default hotkey Ctrl+Shift+E for this, however, if you have configured your own hotkye, it has bigger priority.

Will be release next week

**Comment by janproch** [comment]
Added in 5.1.1
