### ISSUE TITLE
BUG: MariaDB SQL Generator: INSERT not working

### ISSUE THREAD

**Issue by venantiusgalih** [dbgate/dbgate#353]
**Describe the bug**
No generated SQL for INSERT statement in mariadb.

**To Reproduce**
1. Connect to MariaDB database
2. Right click on table > select SQL Generator: INSERT

**Expected behavior**
Generate SQL for INSERT statement

**Screenshots**
![image](https://user-images.githubusercontent.com/20768516/187006811-40497ab4-3c87-4ab3-88c3-df0df87832d8.png)

**Version Information (please complete the following information):**
 - OS: Windows 10 21H2 x64
 - App Version: 5.1.0
 - Install source: Installer
 - Type: Application
 - Database engine: MariaDB 10.6.7-3 (skysql online database)

**Comment by janproch** [comment]
In the screenshot, the table note has 0 rows. This number is approximate, so if you have some rows in this table and MariaDB stats don't reflect this, it is really dbgate bug. If the table is empty, no SQL INSERT statement should be generated

**Comment by venantiusgalih** [comment]
Ohh, I see. Okay. Thank you for the explanation.
