### ISSUE TITLE
BUG: Open Structure Sqlserver computed columns not recognized

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#354]
**Describe the bug**
Sqlserver computed columns are not recognized in Open Structure.

![image](https://user-images.githubusercontent.com/757749/187219666-7497ee15-e97c-4fd0-aac0-5f56891fa810.png)

![image](https://user-images.githubusercontent.com/757749/187218808-803b4550-a3e9-43c1-9902-44b0e0586643.png)

In Azure Data Studio I got:
![image](https://user-images.githubusercontent.com/757749/187219181-009d7439-ddc9-42ca-bb13-cd0a0ec570ba.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.1.0
 - Install source Installer
 - Type - Application
 - Database engine: SQL Server

**Comment by janproch** [comment]
fix pushed into GIT, will be released next week

**Comment by janproch** [comment]
Fixed in 5.1.1
