### ISSUE TITLE
BUG: Sqlserver not filtering NULL or NOT NULL on datetime columns

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#356]
**Describe the bug**
Sqlserver not filtering NULL or NOT NULL on datetime columns

**To Reproduce**
1. Select a table, and open data
2. Filter a column of type datetime2 or datetime with NULL or NOT IS NULL
3. Filter is showed in red color, and data is not filtered.

**Expected behavior**
Do the filter

**Screenshots**
![image](https://user-images.githubusercontent.com/757749/187781045-2a72519e-d040-41f2-a8d6-990b356cd826.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.1.0
 - Install source Installer
 - Type - Application
 - Database engine: SQL Server

**Comment by janproch** [comment]
Thanks, fix is pushed in GIT, will be released next week

**Comment by janproch** [comment]
Fixed in 5.1.1
