### ISSUE TITLE
FEAT: connect via socket

### ISSUE THREAD

**Issue by mbrevda** [dbgate/dbgate#358]
Allow connecting to db via socket. Currently, a host/IP address must be used to connect. It would be great if there was an option to connect via socket for DB's that support that such as [mysql](https://github.com/sidorares/node-mysql2/blob/6d3460946da9bd8ced862c355f8d4bb06f87e0b5/lib/connection.js#L47)

**Comment by mbrevda** [comment]
What is the env var for sockets?

**Comment by mbrevda** [comment]
@janproch can we get an env var to enable this, please?

**Comment by janproch** [comment]
Sorry, this was not implemented

I have added env variable SOCKET_PATH_connectionId

It is also described in [docs](https://dbgate.org/docs/env-variables.html)

The feature is pushed into GIT, but not yet released

**Comment by mbrevda** [comment]
Thanks 🙏🙏
