### ISSUE TITLE
FEAT: Show affected rows after UPDATE/DELETE/INSERT

### ISSUE THREAD

**Issue by markovic-nikola** [dbgate/dbgate#361]
**Is your feature request related to a problem? Please describe.**
From experience of using other DB managers, most of them show number of rows that were affected after running SQL query (UPDATE/DELETE/INSERT).

**Describe the solution you'd like**
(If possible) Add a column in the _Messages_ tab section with showing count of affected rows.
![image](https://user-images.githubusercontent.com/16388545/188886870-edc2e958-27eb-4070-bdf4-49722244b989.png)

**Describe alternatives you've considered**
Putting count in the _Messages_ tab makes sense for me, but if you have a better solution - fine by me.

**Comment by janproch** [comment]
Fixed affected rows logging for MySQL.
Added for POstgreSQL.

For SQLite and SQL server it already works

**Comment by spance** [comment]
I didn't find any information about the number of affected rows in the window.
Second, I hope to echo the executed SQL in the log window.

Version: 5.2.1
Platform: windows & Mac

**Comment by savissimo** [comment]
> For SQLite and SQL server it already works

I don't think it works for SQL Server. Here is what I get after running a DELETE:

![image](https://github.com/dbgate/dbgate/assets/6923738/98085ac9-38ad-42ed-872a-eccf291ee30c)
