### ISSUE TITLE
BUG: Query designer, open a saved query lost sort order

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#363]
**Describe the bug**
I write a query designer, I set the sort order, I saved it (.qdesign file), when I reopen the sort order is lost

**To Reproduce**
Write a query
Set the sort order

![image](https://user-images.githubusercontent.com/757749/189162786-5c6eeabe-e08b-4db9-98ab-c52bb1feefa0.png)

Save the query as .qdesign file
Open the query
The query designer lost the sort order, but the SQL view show it.

![image](https://user-images.githubusercontent.com/757749/189162539-5f280a2c-5164-4989-9e95-50983595db58.png)

![image](https://user-images.githubusercontent.com/757749/189162483-93ab87c1-0515-40fd-9e26-10ee7ba1e4e6.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.1.1
 - Install source Installer
 - Type - Application
 - Database engine: I tested on MySQL and SQL Server

**Comment by janproch** [comment]
Thanks, good catch, fixed in GIT
