### ISSUE TITLE
FEAT: Form View move between records

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#370]
In the form view would be nice to have buttons to move to next, previous, first, last record. 

![image](https://user-images.githubusercontent.com/757749/190410773-a3f8c798-6004-46fe-aa7b-b77f05dc7dab.png)

Actually you have to return to Switch to table view, move to next record, and Switch to form again.

**Comment by janproch** [comment]
This was already implemented in context menu, I added it also into toolbar.
