### ISSUE TITLE
FEAT: Query Designer short order more flexibility

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#372]
The app has a limitated set of short options, I have very complex querys with even 10 order fields.

I suggest to split the sort order field in two fields, one for Position #, and one for Direction.
![image](https://user-images.githubusercontent.com/757749/190414802-6000623d-34b4-4143-a512-ea83872ede93.png)

And Alternative could be expand the options to at least 10, 4 ascending, 4 descending, 5 ascending,5 descending, etc...

**Comment by janproch** [comment]
I implemented the simplest solution for now (add variants to 10)
