### ISSUE TITLE
FEAT: New version notification

### ISSUE THREAD

**Issue by diegomesata** [dbgate/dbgate#375]
It would be nice that in the about dialog box, you could be notified if there is a new version, and update from there. You could have the release channel and the beta channel to separate the main two releases.

![image](https://user-images.githubusercontent.com/757749/191031137-5fefb411-c237-468d-80a3-0471ee01c775.png)

As alternative the update button could redirect to the download page.

At the moment of open dbgate could be nice to see the new version notification.

Thank you

**Comment by janproch** [comment]
Notification was added to status bar

Also beta (and premium-beta) auto-update channel was introduced
