### ISSUE TITLE
FEAT: Key Separator

### ISSUE THREAD

**Issue by azhe403** [dbgate/dbgate#379]
**Another Redis Desktop Manager** has feature to separate redis key

![image](https://user-images.githubusercontent.com/17938038/191872290-a2f6dd0f-c263-42b3-8733-bfe962d2b36d.png)

May can be considered to add feature like this to dbgate?

![image](https://user-images.githubusercontent.com/17938038/191872657-ee29aaf6-df33-4fd1-9e26-e1e29a5edf3d.png)

**Comment by janproch** [comment]
Thanks for that idea, solved
