### ISSUE TITLE
BUG: Broken Windows download links

### ISSUE THREAD

**Issue by rmed1na** [dbgate/dbgate#382]
**Describe the bug**
When trying to download the installer for Windows it throws a Github 404 on all flavors (zip, arm, etc.)

**To Reproduce**
1. Go to https://dbgate.org/download/
2. Click on any Windows download
3. See error

**Expected behavior**
Should download the requested installer

**Screenshots**
![image](https://user-images.githubusercontent.com/30838319/192352804-78a81395-61d5-48cd-9f3f-1d6d928ca8ee.png)

**Comment by janproch** [comment]
I am releasing new version, there is problem with GitHub action workers for Windows platforms

Please use older version (1 week): https://github.com/dbgate/dbgate/releases/download/v5.1.2/dbgate-5.1.2-win_x64.exe

New version will be installed thanks to electron autoupdate after build process will be fixed

**Comment by janproch** [comment]
All platforms are built now, so it is fixed, thanks

Maybe time to make more robust build process...
