### ISSUE TITLE
docker image - add arm support

### ISSUE THREAD

**Issue by niradler** [dbgate/dbgate#383]
Hi, can we update the workflow of building the images to build image to arm
[https://github.com/dbgate/dbgate/blob/master/.github/workflows/build-docker.yaml](https://github.com/dbgate/dbgate/blob/master/.github/workflows/build-docker.yaml)

we can use 
`docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7`
to build to multiple platform

**Comment by janproch** [comment]
Hi, please create pull request for this. Docker images are built on beta version channel, so we could try it with beta version

**Comment by janproch** [comment]
I made refactor of docker build jobs, multiplatform docker images are included
