### ISSUE TITLE
BUG: Unable to drop Database in postgres

### ISSUE THREAD

**Issue by santhoshsubbiah** [dbgate/dbgate#384]
**Describe the bug**

Drop option is not provided for postgres Database

**To Reproduce**

1. Select Database
2. do right click on it.
3. no option available regards delete

**Expected behavior**

Please give drop/delete option for DB.

**Screenshots**

![Screenshot at Sep 26 10-56-21](https://user-images.githubusercontent.com/46211134/192696618-3baaea0a-eb7b-49b1-a2b0-8ab816c5da22.png)

**Version Information (please complete the following information):**

 - Database engine: [PostgreSQL]

**Comment by janproch** [comment]
Thanks for the idea, feature is implemented in version 5.1.4

**Comment by santhoshsubbiah** [comment]
Thank you :)
