### ISSUE TITLE
demo.dbgate.org - beta version crash  5.1.5-beta.3

### ISSUE THREAD

**Issue by PlkMarudny** [dbgate/dbgate#386]
**Describe the bug**
Immediate crash on ER diagram creation from the Mongo 'Chinook' database

**To Reproduce**
1. Go to demo.dbgate.org
2. Click on 'Mongo' to list collections
3. Choose File -> New ER diagram
4. Drag the 'Album' collection into the diagram creation area
5. Crash

**Expected behavior**
No crash.

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.1.5-beta.3
 - Install source: demo.dbgate.org
 - Type - Web
 - Database engine: Mongo

**Comment by janproch** [comment]
Diagrams are not supported of noSQL databases. I disabled this option, unless SQL database is selected,
