### ISSUE TITLE
QUESTION: How can I see the definition of a view? (MS SQL Server)

### ISSUE THREAD

**Issue by savissimo** [dbgate/dbgate#391]
**Details:**
If I connect to a MS SQL Server instance and I have a view, how can I obtain its definition? Ideally, I'd like to get an ALTER VIEW script, but the definition itself would be fine as well. 

**Version Information [might be relevant to your issue]**
Operating System: Windows 10
App Version [help -> about]: 5.1.4 (2022-10-02)

**Comment by diegomesata** [comment]
Hello, the only way I found was in the context menu select SQL: CREATE VIEW

![image](https://user-images.githubusercontent.com/757749/194656691-0155433b-9f94-4abd-b3c8-2e188c7345bf.png)

The sql contains the definition, but you have to rewrite it to convert it to an alter.

It would be nice to have the SQL: ALTER VIEW option, similar to azure data studio Script as Alter.

![image](https://user-images.githubusercontent.com/757749/194657868-e648b59b-8ecb-4a04-adc3-39c40de303eb.png)

**Comment by savissimo** [comment]
You're right, I even did that, but the view was so simple that I mistakenly thought that was just a query to ´select´ the view. 

It would be great to have the ALTER VIEW ready, but it's easy enough to edit the CREATE VIEW. Thank you!
