### ISSUE TITLE
FEAT: Split Windows

### ISSUE THREAD

**Issue by marcocavanna** [dbgate/dbgate#394]
**Is your feature request related to a problem? Please describe.**
Best feature I'm missing while using DbGate is the possibility of placing two windows side by side

**Describe the solution you'd like**
just like with any text editor or code ide, it would be very convenient and useful to be able to arrange multiple windows side by side so as not to jump.

**Describe alternatives you've considered**
Nothing...

**Comment by jamescze** [comment]
Please, add this functionality. I am thinking about migrating (after many years) from DBevaer to somewhere else and DB Gate looks VERY promising so far. This functionality is very important to me, I am using it on daily bases.

**Comment by marcocavanna** [comment]
👍

**Comment by LanHikari22** [comment]
Probably should have horizontal splits here as well for consistency.

Thanks,
Mohammed
