### ISSUE TITLE
FEAT: keyboard shortcut to hide result window and show/hide the side toolbar

### ISSUE THREAD

**Issue by opensas** [dbgate/dbgate#406]
I would like to have a kwyboard shortcut to

show/hide the result panel of a query

![image](https://user-images.githubusercontent.com/481687/198224509-332a0df7-8f8e-4285-9d89-d5eb3b47bc84.png)

and to show/hide the side bar (ctrl-b in vscode)

![image](https://user-images.githubusercontent.com/481687/198224839-ffe4b22d-9702-4dbc-8284-663c29800eee.png)

**Comment by janproch** [comment]
implemented:

Ctrl+B - show/hide sidebar
Ctrl+Shfit+R - show/hide result pane
