### ISSUE TITLE
BUG: MongoDB missing type support / changes field type on update

### ISSUE THREAD

**Issue by notz** [dbgate/dbgate#413]
**Describe the bug**
On update or creating an entry the type is either changed or can't be defined. 

Especially date & number fields are converted to strings.

**To Reproduce**
1. Open a mongo collection with either a date field or number field
2. Edit the field and press save
3. Check the output of the generated update statement

**Expected behavior**
Keep the type of the field and give a option to change the type

**Version Information (please complete the following information):**
 - OS: Linux
 - App Version 5.6.1
 - Install source: deb package
 - Type:  Application
 - Database engine: MongoDB

**Comment by kelp404** [comment]
I have the same problem.
After I update the Date value, it actually write a String.

**Comment by daniel-sc** [comment]
This problem makes this tool rather useless for working with MongoDB (except for read-only or trivial update cases..).
Is this something that can/will be fixed, or would this be a bigger problem needing an architectural change?

(I'd love to use dbgate, and I think it would be a nice replacement for the barely maintained https://github.com/mongo-express/mongo-express if this issue can be addressed!)

**Comment by mikila85** [comment]
@daniel-sc For sure.. 100% useless.. just working with it creates bugs in the DB of wrong types..

**Comment by mikila85** [comment]
@daniel-sc For sure.. 100%!.. just working with it creates bugs in the DB due to wrong types.. at least if you opened a "boolean" keep it boolean... i change from true to "false" LMFAO

**Comment by mikila85** [comment]
@daniel-sc For sure.. 100%!.. just working with it creates bugs in the DB due to wrong types.. at least if you opened a "boolean" keep it boolean... i change from true to "false" LMFAO

Guys please can we fix this?
@janproch

**Comment by mikila85** [comment]
@daniel-sc For sure.. 100%!.. just working with it creates bugs in the DB due to wrong types.. at least if you opened a "boolean" keep it boolean... i change from true to "false"

Guys please can we fix this?
@janproch

this tool is by far superior over anything found on the internet especially open source... 
but this bug makes it useless for mongo :(

a simple fix would be a radio button for "String" / Object...
if object leave the value as is without wrapping it with \" \"

**Comment by mikila85** [comment]
i tried fixing it my self but i cant even get it to install right
![image](https://github.com/dbgate/dbgate/assets/3965957/3748a460-79e2-456b-95bf-f835052d53ed)

**Comment by mikila85** [comment]
Thank you!! and if editing a "Boolean" field from false to true it will remain Boolean or change to string like before?

**Comment by janproch** [comment]
In this case, boolean will be stored.

If you type "true", "false", "null", number, ObjectId or date, proper types will be used, no matter what was the cell content before.

I believe this behaviour is better than try to keep data type of cell. You could easily convert cell to string, if you really want string. Only in cas of date-times could be reasonable to keep string, if datetime was stored as string before.

It is quite a large change (this merge commit: https://github.com/dbgate/dbgate/commit/e97787113c133dfb7e73ad0f70269d02bf4c6dda ), so lot of NoSQL data editing stuff was changed

**Comment by mikila85** [comment]
I tried it and it's awesome 💯💯!! Thank you very much finally it's working properly!
