### ISSUE TITLE
BUG: Error when resuming computer from sleep

### ISSUE THREAD

**Issue by petr6** [dbgate/dbgate#414]
**Describe the bug**
When i put computer to sleep with DbGate running, after waking up computer from sleep i get error described on screenshot.

**To Reproduce**
1. Start DbGate
2. Put computer to sleep
3. Wake computer from sleep

**Expected behavior**
No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/73128826/200387047-ba366ce7-c8b3-4f4a-8262-4ad14c1c2d21.png)

**Version Information (please complete the following information):**
 - OS: Windows 11 Home 22621.674
 - App Version: 5.1.5
 - Install source Installer
 - Type - Application
 - Database engine: -

**Comment by dataspun** [comment]
Similar to above conditions is this error:

![image](https://user-images.githubusercontent.com/32719032/200710356-674df16a-8adb-482f-b361-41844cd22811.png)

**Comment by janproch** [comment]
Closing - see duplicate issue #458
