### ISSUE TITLE
QUESTION: How to build my own docker image from source

### ISSUE THREAD

**Issue by csnelsonchu** [dbgate/dbgate#415]
**Details:**
I will like to build my own docker image from source similar to the image at https://hub.docker.com/r/dbgate/dbgate
Which command should I use to build?

**Comment by janproch** [comment]
It is defined in docker github action: https://github.com/dbgate/dbgate/blob/master/.github/workflows/build-docker.yaml

it could something like:
```sh

yarn install
yarn setCurrentVersion
yarn run prepare:docker
docker build ./docker

```

**Comment by csnelsonchu** [comment]
Thanks @janproch 
Works great!!!
