### ISSUE TITLE
FEAT: Padding for SQL editor?

### ISSUE THREAD

**Issue by superDuperCyberTechno** [dbgate/dbgate#422]
**Is your feature request related to a problem? Please describe.**
It isn't really. This is purely quality-of-life.

**Describe the solution you'd like**
A customizable padding for the SQL editor so the text isn't mashed all the way to edge.

**Describe alternatives you've considered**
No alternatives are necessary. I can live without it.

**Comment by janproch** [comment]
I added a bit bigger margin (without configuration). Hopefully it will look better
