### ISSUE TITLE
BUG: structure not being refreshed after adding/removing column

### ISSUE THREAD

**Issue by opensas** [dbgate/dbgate#428]
**Describe the bug**

after adding removing a column, from outside or from a query, the table view is not refreshed

**To Reproduce**

click on a table

open a query window (CTRL-T)

create a new column

```sql
ALTER TABLE table1
  ADD COLUMN column1 boolean DEFAULT TRUE NOT NULL;
```

refresh view, the new column will not appear

same thing happens removing a column

pressing CTRLF5 doesn't refresh the view either

the only way to update structures seems to be to close the application (ctrl-F4) and open it again

**Expected behavior**

the view is refreshed after pressing F5

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version 5.1.6
 - Install source installer
 - Type - Application
 - Database engine: PostgreSQL/SQL Server]

**Note**

Same thing happens when I completely drop the database and recreate it (I'm running the db from docker, and when I stop and recreate  the container ctrl-f5 also wont work) Perhaps solving this issue would also solve the aforementioned problem.

**Comment by janproch** [comment]
Thanks for the feedback

You could refresh database structure, this is not done after each query execution, event not after pressing F5 in data view. You could refresh DB structure manually, using this icon

![image](https://user-images.githubusercontent.com/2543891/207919576-6ab7fc76-5364-442f-b45a-03560bedb52c.png)

Also it is possible to setup automatic structure refreshing, in settings, General, Connection

However, very good idea is to allow refreshing structure and data with Ctrl+F5 in data view

**Comment by opensas** [comment]
thanks a lot for the tip!

I agree, running 'refresh structure' on Ctrl+F5 would be great, and also adding a configurable keyboard whortcut to refresh structure.

more over, it would be great if you could show the currently assign keyboard shortcut on the on hover tooltip of each icon, here:

![image](https://user-images.githubusercontent.com/481687/208112044-180560f3-1eed-464c-a3d3-389651188583.png)
