### ISSUE TITLE
QUESTION: open db connection via commandline

### ISSUE THREAD

**Issue by mpprdev** [dbgate/dbgate#430]
**Details:**
Does DBGate standalone app (MacOs) support passing connection parameters (URL) via commandline?

This will greatly help launching URLs that need to be constructed dynamically (via some script).

**Comment by janproch** [comment]
DbGate has no possibility to define connection in commandline parameters
However, you can use configuration via env variables 

Eg.
 (on linux or mac)
CONNECTIONS=con1 ENGINE_con1=sqlite@dbgate-plugin-sqlite FILE_con1=file-to-sqlite-database dbgate

for Windows, you could use eg. set command in cmd or bat file

For all possibilities, how to use env variables, see docs:
https://dbgate.org/docs/env-variables.html
