### ISSUE TITLE
BUG: system-versioned tables in mariadb don't show up in dbgate 

### ISSUE THREAD

**Issue by clarity99** [dbgate/dbgate#433]
**Describe the bug**
Once you add system versioning to a table in mariadb, it is no longer visible in dbgate.

**To Reproduce**
CREATE TABLE t (
   x INT
) WITH SYSTEM VERSIONING;

**Expected behavior**
These kind of tables should behave as normal tables.

**Version Information (please complete the following information):**
 - OS: MacOs Ventura
 - App Version 5.1.6
 - Install source - installer
 - Type -Application
 - Database engine: MariaDB

**Comment by janproch** [comment]
Thanks, fix pushed in GIT

**Comment by clarity99** [comment]
Hi, this bug (or sth similar) seems to be still around in 5.2.1. What happens now is the following:
I open the db, i now see all the tables. then I click on one table, it opens. I do descending sort on id field, it shows ok.
then the table tab starts showing "Waiting for structure" and on the left side all the tables that have system versioning on disappear.
