### ISSUE TITLE
SQLServer alter store procedure

### ISSUE THREAD

**Issue by fredericoregateiro** [dbgate/dbgate#435]
**Describe the bug**
First awesome project, i'm really enjoy using this program.
I've seen this only on a alter sp script, the create sp script works ok.
If we have a `SET NOCOUNT ON;` the db gate splits the stored procedure into multiple scripts and display a error:
`Incorrect syntax near 'ON'`.

**To Reproduce**
1. create the sp
``` SQL
CREATE PROCEDURE [dbo].[SpName]
	@documentId	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 'ONE';
END
```

2. change the sp
``` sql
ALTER PROCEDURE [dbo].[SpName]
	@documentId	INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT 'ONE';
END
```

**Expected behavior**
When altering a sp, the script should run all together.

**Screenshots**
![image](https://user-images.githubusercontent.com/6304701/206549922-4e94c364-97d8-46ef-80d1-3ae93800f924.png)

**Version Information (please complete the following information):**
 - OS: Win11
 - App Version:5.1.6
 - Install source installer
 - Type - Application
 - Database engine: SQL Server

**Comment by janproch** [comment]
Thanks, fix pushed in git
