### ISSUE TITLE
BUG: view sort

### ISSUE THREAD

**Issue by subtle99** [dbgate/dbgate#436]
CREATE TABLE [novel] ( 
  [id] INTEGER AUTO_INCREMENT NULL,
  [title] NTEXT(100) NULL,
  [line] NTEXT NULL,
  [line_index] INTEGER(500) NULL,
  [url] NTEXT(100) NULL,
   PRIMARY KEY ([id])
);

query1 :
SELECT
  `novel`.title,
  GROUP_CONCAT(`novel`.line, x'0D' || x'0A') AS lines
FROM
  `novel`
GROUP BY
  `novel`.url
ORDER BY
  `novel`.id ASC,
  `novel`.line_index ASC;

query2:
CREATE VIEW `view_novel` AS
SELECT
  `novel`.title,
  GROUP_CONCAT(`novel`.line, x'0D' || x'0A') AS lines
FROM
  `novel`
GROUP BY
  `novel`.url
ORDER BY
  `novel`.id ASC,
  `novel`.line_index ASC;

bug:Query result 1 is different from query result 2.

Table data are as follows：
![bug1 1](https://user-images.githubusercontent.com/59327126/206880536-c2a7728d-b7e8-4e40-9867-aa04ed0ee10b.png)
![bug1 2](https://user-images.githubusercontent.com/59327126/206880547-7deb4a9e-3804-4fd5-869c-8c77fba8512a.png)

Query result：
![bug_select_result](https://user-images.githubusercontent.com/59327126/206880566-5d89a8be-9135-4c17-9961-250b1565776b.png)

View Query result（Result error）:
![bug_view_result](https://user-images.githubusercontent.com/59327126/206880591-c5390e01-ad92-48b5-9f99-d637902e703d.png)

**Comment by janproch** [comment]
You have not written DB engine used, butas I know, in most DB engines views could not have ORDER BY clause.

So the recond result is result of query: SELECT * FROM view_novel ORDER BY title. 
As title is string value and not number, the outcome is obvious

Maybe sorting of result could be omited in table and view data grid, if it is not mandatory for DB server
