### ISSUE TITLE
testing dbgate web with docker container in cloud platform

### ISSUE THREAD

**Issue by bangouraboulaye** [dbgate/dbgate#438]
Hi,
many thanks for a great job regarding dbgate!
my question is if there is a way to test dbgate web in the cloud like aws or other platform?
how to handle this using docker container in aws?

thanks and regards

**Comment by janproch** [comment]
Hi,

thanks for feedback
I have received (probably from you) email with a little more information about error, if you could provider eg. screenshot with dbgate configuration in AWS and more detailed error information, it would be great.

DbGate could be run as docker container, no matter whether in AWS or in different container provider. Error message in e-mail could mean incorrect configuration.

**Comment by bangouraboulaye** [comment]
Hi Ja,
many thanks and here are some error:[](url)
![not_found_error](https://user-images.githubusercontent.com/107928058/207941795-44431e2a-228e-49b8-ac47-778f70dc0962.png)

- [ ]

**Comment by janproch** [comment]
Hi, and which image do you use?

It seems, that the file bundle.js is missing in that image.

Image dbgate/dbgate:latest should contain that file

**Comment by bangouraboulaye** [comment]
Hi Jan, i'd to use dbgate/dbgate:latest and it's working :-) 
Super job 👍 !

**Comment by janproch** [comment]
Great, thanks for info
