### ISSUE TITLE
Support viewing blob as string

### ISSUE THREAD

**Issue by charlozard** [dbgate/dbgate#439]
**Describe the issue**
When viewing the content of a field with type blob the raw bytes are shown. Sometimes, for example when storing json you want to be able to see the value as a string.

**To reproduce**
- Create column with type blob
- Edit the new column field and save a string e.g. ````{"test": "This is an example json string"}````
- After saving the value you will see the raw bytes. e.g. ````0x7B2274657374223A20225468697320697320616E206578616D706C65206A736F6E20737472696E67227D````

**Version Information (please complete the following information):**

* OS: Windows
* App Version: 5.1.6
* Install source: installer
* Type: Application
* Database engine: MariaDB

**Comment by janproch** [comment]
DbGate assumes, that blob columns holds blob data.

However, if you want to show text values instead, you could use perspectives, "Design perspective query" in table context menu and than in column menu, Change Display=>Force Text. Force Text option was added now, so it will be available in next version.

**Comment by robinbertram** [comment]
Any new opinions about this issue, @janproch?

We store UUIDs as BINARY/VARBINARY. For us it's necessary to be able to read the UUIDs sometimes. Your suggestion regarding setting up perspectives would be a time consuming hassle for us. We would have to do that for almost every table at some point.

> Standard table view now doesn't support custom formatting, but maybe in future it will be added also to table view

The future is now! 😎

**Comment by smiling-watermelon** [comment]
Any update on the issue? It's not possible, for example, to view UUID values in MongoDB for two reasons:
1. Connection doesn't support UUID representation [parameter](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.uuidRepresentation)
2. Selecting "Force Text" doesn't help in this particular case

## Details for the first point:
```
MongoParseError: option uuidrepresentation is not supported
    at t.parseOptions (/tmp/.mount_DBGatesBR2yq/resources/app.asar/packages/plugins/dbgate-plugin-mongo/dist/backend.js:9:215949)
    at new m (/tmp/.mount_DBGatesBR2yq/resources/app.asar/packages/plugins/dbgate-plugin-mongo/dist/backend.js:9:110063)
    at Object.connect (/tmp/.mount_DBGatesBR2yq/resources/app.asar/packages/plugins/dbgate-plugin-mongo/dist/backend.js:9:461958)
    at e.exports (/tmp/.mount_DBGatesBR2yq/resources/app.asar/packages/api/dist/bundle.js:11:86984)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async process.<anonymous> (/tmp/.mount_DBGatesBR2yq/resources/app.asar/packages/api/dist/bundle.js:456:325634)

Error JSON: {}

Connection: {
  "server": "***",
  "engine": "mongo@dbgate-plugin-mongo",
  "useDatabaseUrl": "***",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "databaseUrl": "***"
}

Platform: linux
```

## Details for the second point
This is how a progressive query looks like with Force Text option:
![image](https://github.com/dbgate/dbgate/assets/146741211/0e2f3441-97df-4cbb-948d-a321509cb296)

Example from another solution for viewing database data (but specific to Mongo), Mongo Express:
![image](https://github.com/dbgate/dbgate/assets/146741211/18684ca7-3358-4760-aba5-0111201dba23)


Should I create a separate issue for `dbgate-plugin-mongo`, with the hope of implementing UUID representation parameter?

**Comment by robinbertram** [comment]
Sad to see that this hasn't changed in the last two years.
