### ISSUE TITLE
FEAT: File extension *.sql

### ISSUE THREAD

**Issue by leuchte** [dbgate/dbgate#445]
Hello

If i try to import a database dump and browse my folder, my sql file are not present.
The file extension in the file dialog has a default of
```
SQL Files *.*.sql
```
dbGate assumes a file with a specific pattern and so i have to change to **All Files (\*.\*)** to select my dump.

I think it makes more sense, to set the default to
```
SQL Files *.sql
```

Thank you

**Comment by janproch** [comment]
Sorry, I am unable to reproduce this, it behaves as expected on Mac

What OS do you use?

**Comment by leuchte** [comment]
Sorry, forgot to mention. Its on Windows (10)

 
![dbgate-file](https://user-images.githubusercontent.com/357271/210137876-cc2f0bbf-d927-49a7-9730-f7b70081e4ff.png)
 Its german, but you get the idea.

**Comment by janproch** [comment]
Thanks for claryfying, fixed
