### ISSUE TITLE
FEAT: Drop all tables of a database

### ISSUE THREAD

**Issue by leuchte** [dbgate/dbgate#446]
Hello,

maybe i missed this. If not, it would be helpful, to get a option in the context menu, to drop all tables of a database. Right now, i have to drop every single table by its own.

Thanks

**Comment by janproch** [comment]
Hello,

you could use SQL generator, with checked "Drop tables" and "Drop references"

![image](https://user-images.githubusercontent.com/2543891/216593552-f856905d-d9e6-4f37-86bc-f603e4057fc1.png)

**Comment by leuchte** [comment]
Hello Jan,

this is a neat solution to this request.

Thank you.
