### ISSUE TITLE
BUG: "SQL:CREATE TABLE" generated SQL default value syntax errors

### ISSUE THREAD

**Issue by Kugaaa** [dbgate/dbgate#455]
For example, I create a table，just have one field
```SQL
CREATE TABLE `test` ( 
  `str` VARCHAR(250) NOT NULL DEFAULT "Hello World" 
);
```

Then I save it, use the function named "SQL:CREATE TABLE"
It will return
```SQL
CREATE TABLE `test` ( 
  `str` VARCHAR(250) NOT NULL DEFAULT Hello World 
);
```
![image](https://user-images.githubusercontent.com/99192047/211307397-39ea75d1-bf2a-454d-9795-7651abf0da7f.png)

This should be a mistake DDL, the quotation after "DEFAULT" marks disappear
If the default value is a empty string, the "DEFAULT" will also be omitted, like
```SQL
CREATE TABLE `test` ( 
  `str` VARCHAR(250) NOT NULL
);
```

![image](https://user-images.githubusercontent.com/99192047/211307398-1a6caff4-c631-49aa-a24b-e89edc0d8541.png)

**Comment by janproch** [comment]
It is neccessary to fill valid SQL expression into Default value textbox, eg. 'Hello World'
This is necessary so that SQL expressions could be inserted into default value

Sorry for confusion, I added helper text to make it more clear

![image](https://user-images.githubusercontent.com/2543891/213913197-718ae6ad-f9c0-4818-b52b-e421a82a612f.png)

**Comment by Kugaaa** [comment]
Sorry to bother you, but I may not understand what you mean
I fill valid SQL expression into Default value textbox as shown below
<img width="712" alt="image" src="https://user-images.githubusercontent.com/99192047/215262524-b430833a-b550-4733-be61-f235779d0c2a.png">

The save changes
```SQL
START TRANSACTION;
CREATE TABLE `test` ( 
  `str` VARCHAR(250) NOT NULL DEFAULT 'Hello World' 
);
COMMIT;
```

Clicking "SQL:CREATE TABLE" after saving still appeared the result
```SQL
CREATE TABLE `test` ( 
  `str` VARCHAR(250) NOT NULL DEFAULT Hello World 
);
```

**Comment by janproch** [comment]
This depends on SQL engine used, so which SQL engine are you using? I tried it with PostgreSQL and MariaDB and it seems to work correctly

MariaDB:
```sql
CREATE TABLE `defvaltbl` ( 
  `id` INT AUTO_INCREMENT NOT NULL,
  `val` VARCHAR(250) NULL DEFAULT 'Hello world' ,
  CONSTRAINT `PRIMARY` PRIMARY KEY (`id`)
);
```

**Comment by Kugaaa** [comment]
The "Connection type" is MySQL

**Comment by janproch** [comment]
Thanks, solved in GIT.

I tested it under MariaDB, it worked here, but this is one of rare incompatibilities between MySQL and MariaDB.
