### ISSUE TITLE
BUG: ON windows 11 error after system goes in suspend mode

### ISSUE THREAD

**Issue by michelebukovitz** [dbgate/dbgate#458]
**Describe the bug**
In Windows 11, after resuming from suspend mode a runtime error occurs and it's shown multiple times after pressing OK. 
It's annoying since user have to click on ok button multiple times. 
After the application seems to continue working. 

**To Reproduce**
1. Open a query window or a table
3. Place computer in screen saver or suspend mode
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/122700814/212497377-cdf09ac1-8ffe-4d6b-8ca8-c0345af4881f.png)

**Version Information (please complete the following information):**
 - OS: WIndows 11 Home
 - App Version 5.2.1
 - Install source Installer
 - Type - Application
 - Database engine: Any (for now MySQL and PostgreSQL)

**Comment by janproch** [comment]
Duplicate with #414 

I am trying to replicate this, without success yet

**Comment by janproch** [comment]
I implemented logging system into DbGate (now in BETA), which should help to solve this problem.

**Comment by janproch** [comment]
I have fixed many situations, which could lead to this problem. These fixes are released in version 5.2.2

If this problem persists, please reopen this issue
