### ISSUE TITLE
FEAT: Export and Import Option

### ISSUE THREAD

**Issue by seon22break** [dbgate/dbgate#469]
**Is your feature request related to a problem? Please describe.**
Hi all , I love the application and use it daily in my work. I would like to suggest an improvement that I think may be complicated, but would be great to implement.
Context:
When you change computer work it is very common to use the same programs and therefore, we all like that everyone has the same configurations, since in dbgate is not logged in with Github (something that I do not know if this raised in the future) could be implemented the way to export and import the configurations (including connections) from one computer to another.   

**Describe the solution you'd like**
One option to export configuration (connection,snippets,queries, history) in a json and include one option to import this file.

**Comment by janproch** [comment]
Hi, thanks for this idea

You could use simple workaround, find files connections.jsonl and .key in data folder (accessible from menu Tools/Open data folder) and copy it to data folder of new installation

Storing connection on cloud (eg. with GitHub login) is not planned now, but I will consider this

**Comment by seon22break** [comment]
> 

Thanks for your answer.
