### ISSUE TITLE
FEAT: Any plans for releasing a Windows installer for the ARM-version?

### ISSUE THREAD

**Issue by david-nordvall** [dbgate/dbgate#473]
I have a Surface Pro 9 5G Windows on ARM PC. I am currently using the portable Windows on ARM version of dbgate. While it works perfectly fine, I would prefer if an installer would be available (as it is for the x64 platform), for start menu icon, etc. Is it possible to provide this? Note that the _installer_ doesn't need to be an ARM executable, only the _installed application_. 🙂

If possible, it would be great if the installer for the ARM version could be distributed through winget (as the x64 version currently is). As a bonus. 😄

**Comment by janproch** [comment]
ARM 64 windows executable is released in latest BETA, https://github.com/dbgate/dbgate/releases/tag/v5.2.3-beta.1

I have no machine available to test this, so you could try it

**Comment by david-nordvall** [comment]
The installer is an x86 program, as I'm sure you're aware. But that's fine; installing the ARM version works great with the x86 installer. I haven't tested the functionality of the actual program, only that it installs, starts and is, in fact, a native ARM program. 🙂
![image](https://user-images.githubusercontent.com/25451628/216759807-9f99b85f-198d-412d-85fb-7bb68e38f46c.png)
![image](https://user-images.githubusercontent.com/25451628/216759829-b38ee082-808c-49e3-a10d-debd7f5e62f1.png)
Everything looks great!

**Comment by janproch** [comment]
Great, thanks for the test!

**Comment by david-nordvall** [comment]
No problem. Please let me know if you need me to perform any more tests on ARM hardware. I have used the beta version some more and haven't run inte to any issues at all (working against a MySQL database and a Mongodb database).
