### ISSUE TITLE
Detect As Virus

### ISSUE THREAD

**Issue by arihs77** [dbgate/dbgate#475]
Detect as virus by avg and avast

**Comment by janproch** [comment]
I tried to install Avast on my Windows computer, and no virus was detected in dbgate. Could you please provide exact download link, which was positive for virus test?

DbGate is built on GitHub build server in container, which is installed from scratch every build cycle. So there is practically no way, how it could be infected by virus

**Comment by asjur** [comment]
https://www.virustotal.com/gui/file/57063813388072fdb483d50b172200971bbbc206a047ffe7bc28f2a1fc572ca2/detection
https://www.virustotal.com/gui/file/66b73120673ca44fccea433bfa8aba1b2efb8246560f07e9eb3069ceede34a8d/detection

It sounds like you have a false positive if you downloaded from GitHub.

**Comment by arihs77** [comment]
Dear alexander,

 Yes, i think this is false alarm from my antivirus. After reinstall them,
no virus detected when i trying to install dbgate again.

Thanks for your fast support.

And thanks for your dbgate app.



Pada tanggal Jum, 3 Feb 2023 16.38, Aleksander ***@***.***>
menulis:
