### ISSUE TITLE
BUG: mongo, Namespace * is a view, not a collection

### ISSUE THREAD

**Issue by subtle99** [dbgate/dbgate#476]
![mongo-bug](https://user-images.githubusercontent.com/59327126/216265008-c45d49c9-4aed-4ad9-923e-ab367ec2bf77.png)

**Comment by subtle99** [comment]
Bugs still exist

**Comment by janproch** [comment]
Did you try it in BETA version? This fix is not yet released in stable version.

**Comment by subtle99** [comment]
Yes I use new BETA version, 
I used python and some code like:
view1 = [{"$group": {"_id": {"url": "$url", "author": "$author", "name": "$name", },
                                   "sum_status": {"$sum": "$status", }, "count_status": {"$sum": 1, }, }, }, ]

db_mongo.command({
                    "create": "vbook",
                    "viewOn": "book",
                    "pipeline": view1
                }) 

after that,I can open and view the 'vbook' by MongoDB Compass,but can't open with dbgate.

**Comment by janproch** [comment]
Could you please try it with released version 5.2.3 ?
