### ISSUE TITLE
FEAT: Connect via CLI

### ISSUE THREAD

**Issue by skurfuerst** [dbgate/dbgate#483]
**Is your feature request related to a problem? Please describe.**

I often want to integrate DB management tooling into external CLI tools which build tunnels to foreign hosts and extract DB credentials...

**Describe the solution you'd like**

I'd like to have a way to open DbGate with a given database and credentials, like:

`/Applications/DbGate.app/Contents/MacOS/DbGate open --host "...." --db "..."` (etc). It should start dbgate if not running; and if it is running it should open the given database.

**Describe alternatives you've considered**

Alternatively I'd probably use the dbgate docker image to archive this.

Thanks for this great tool ❤️ 
All the best,
Sebastian

**Comment by janproch** [comment]
You could use configuration with environment variables (https://dbgate.org/docs/env-variables.html )

If you use SINGLE_CONNECTION and SINGLE_DATABASE variables, only selected database will be available, and it will be connected after DbGate start.

Full command-line looks like this:


```
CONNECTIONS=con1 SERVER_con1=localhost ENGINE_con1=mysql@dbgate-plugin-mysql USER_con1=root PASSWORD_con1=**** SINGLE_CONNECTION=con1 SINGLE_DATABASE=Chinook /Applications/DbGate.app/Contents/MacOS/DbGate
```

**Comment by skurfuerst** [comment]
Ah really cool 😎 thanks so much! That solves the issue!

All the best,
And keep up the great work,
Sebastian
