### ISSUE TITLE
BUG: Connect to default Oracle database

### ISSUE THREAD

**Issue by martinpruska** [dbgate/dbgate#489]
**Describe the bug**
It's not possible to connect to an Oracle database if no default service name is specified in the DB configuration. I would expect the field "Default database" would be used for that, but it's not working. It's also not possible to connect via database URL option.

**To Reproduce**
1. Create a new connection
2. Select OracleDB connection type
3. Use 'Fill database connection details'
4. Fill in all the required fields, also include 'Default database' ('Use only database ...' checkbox doesn't influence the result)
5. Test connection
6. Results in error: "_Connect failed:  ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA_"

**To Reproduce 2 - URL connection**
1. Create a new connection
2. Select OracleDB connection type
3. Use 'Use database URL'
4. Fill in the DB URL
5. Test connection
6. Results in error: "_Connect failed:  ORA-12560: TNS:protocol adapter error_"
7. Note: I've tried various formats of the URL and also tested them in _sqlplus_ cmd line tool
    - user/password@localhost:1521/DEFAULT_DATABASE_NAME  (works in slqplus)
    - oracledb://user/password@localhost:1521/DEFAULT_DATABASE_NAME  (does not work in sqlplus)
    - user:password@localhost:1521/DEFAULT_DATABASE_NAME  (does not work in sqlplus)
    - oracledb://user:password@localhost:1521/DEFAULT_DATABASE_NAME  (does not work in sqlplus)

**Expected behavior**
The connection to a DB server should be established.

**Screenshots**
![image](https://user-images.githubusercontent.com/61323630/217802140-5f676d75-d8a3-40c8-b336-b997d00f34c7.png)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version: 5.2.2
 - Install source: installer
 - Type - Application
 - Database engine: Oracle

**Comment by janproch** [comment]
In new version should work with database URL - localhost:1521/DEFAULT_DATABASE_NAME (in GIT but not yet release)

**Comment by AxelRHD** [comment]
Running into the same problem. Does not work with field input or URL. Always getting the ORA-12504 error.

A pitty... I really love the application.
