### ISSUE TITLE
Db Connection Error - Set Encrypt Option to true

### ISSUE THREAD

**Issue by austinwilcox** [dbgate/dbgate#490]
I am getting an error when trying to connect to an instance of SQL Server that is hosted on Azure and is encrypted. Here is the error modal that I am getting.

![DbEncryptError](https://user-images.githubusercontent.com/43357911/217903568-a6aca876-2569-43e7-9756-d0d5bff3a89a.png)

 I would be happy to create a PR to add an option for encrypt, so we can send that with the connection information if there is not already a solution for this.

**Comment by janproch** [comment]
At first, you could try to check "Use SSL" on SSL tab, it should set the encrypt flag.

If you it doesn't help and you could run DbGate with sources, you could try play with connection options here:

https://github.com/dbgate/dbgate/blob/87c29faaddc22b33d2f75820dbf2f226655c4745/plugins/dbgate-plugin-mssql/src/backend/tediousDriver.js#L28

**Comment by austinwilcox** [comment]
@janproch setting the useSSL checkbox fixed the issue. Thank you for that. Hopefully having this issue in the mix help others find the same solution.
