### ISSUE TITLE
FEAT: Include macOS-specific app icon

### ISSUE THREAD

**Issue by blakegearin** [dbgate/dbgate#494]
**Is your feature request related to a problem? Please describe.**
DbGate on macOS looks out of place in the dock because it doesn't follow [Apple's app icon guideline](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#macos/).

**Describe the solution you'd like**
Include a version of the icon that follows the guideline.

Here's a version I made, though the logo is an embedded PNG so it's not particularly high quality.

![DbGate](https://user-images.githubusercontent.com/17950836/218326134-07a71649-1ac3-4005-b0ef-fe45adf4d9f5.png)

**Describe alternatives you've considered**
N/A

**Comment by janproch** [comment]
Great thanks for this

You are right, it looks more like other apps now. Maybe the blue icon inside could be a bit bigger

Is there any place, where background "button" image could be downloaded? Or if you could provide your template without dbgate icon. Maybe I could add it to icon generating script

<img width="234" alt="image" src="https://user-images.githubusercontent.com/2543891/222799422-64c7a856-661c-4614-9226-c10ae2435f9a.png">

**Comment by blakegearin** [comment]
Sure, here's just the background image as a PNG and SVG exported from Figma.

![button](https://user-images.githubusercontent.com/17950836/222891350-a6649bf3-36d4-4838-abdf-93a705f26610.png)

![button](https://user-images.githubusercontent.com/17950836/222891379-017e7eef-4ae5-4f21-8918-adebf2424c0a.svg)

**Comment by janproch** [comment]
Thanks!
