### ISSUE TITLE
BUG: Crash when viewing release changes

### ISSUE THREAD

**Issue by savissimo** [dbgate/dbgate#507]
After every update, a new tab with release changes is shown. However, as soon as it is activated DbGate crashes. The Inspector shows the error in the screenshot below. 

Upon reloading, if the tab was active when DbGate closed, it is activated again and the application crashes again. To escape the loop, you either need to:
- close all tabs as suggested by the repeated crashes alert, then reopen them one by one from the history. If you accidentally reopen the changes tab, it crashes again;
- open the inspector, click on another tab, close DbGate. On reopening, the changes tab won't be the active one and you'll be able to close it. 

**To Reproduce**
1. Update DbGate and receive the changes tab. 
2. Click on it. 
3. See issue. 

**Expected behavior**
The release changes can be read and the application does not crash. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6923738/221841630-b4d2aa21-7495-4b2e-a377-98a4257469c2.png)

**Version Information (please complete the following information):**
 - OS: Windows 10
 - App Version: 5.2.3 (but it has been happening also in previous versions)
 - Install source: installer
 - Type: Application
 - Database engine: SQL Server (not important)

**Comment by janproch** [comment]
I was unable to replicate this, it was working for be both on Windows and Mac. Dou you have still this problem? Has anybody other the same experience?

Changelog could be shown on demand with menu - Help/Changelog.

BTW good catch, how to closed crashing tab :-) Maybe there could be also an option to close only current tab, when crash occurs

Thanks

**Comment by janproch** [comment]
Thanks, probably CHANGELOG page was in inconsistent state temporarily and markdown component did not handle it correctly. I am closing it for now.

**Comment by savissimo** [comment]
Just for the record, it happened again with version 5.2.5. Here is the usual Javascript error:
![image](https://user-images.githubusercontent.com/6923738/226878199-492e59ea-955a-4b9d-b03f-c7d6407343a6.png)
