### ISSUE TITLE
excel export not working Version: 5.2.3

### ISSUE THREAD

**Issue by sretenD** [dbgate/dbgate#511]
Excel export is not working. When exported no file can be found.
Version: 5.2.3
Build date: 2023-02-27

**Comment by janproch** [comment]
Could you please provide additional info? It works for me.

I have one point to this, Excel exports/imports don't support streaming for now, so it will not work for tables with many rows. In that case, please export data as CSV, which has no size limitation

**Comment by LukasDotEU** [comment]
Same problem after update.
When exporting as an Excel file there is no file in the specefied folder.

Export tried with an SQLite Database

Version: 5.2.4
Build date: 2023-03-05

**Comment by LukasDotEU** [comment]
In the WebApp the Issue is not happening, because you can't choose where to store the file there.
