### ISSUE TITLE
QUESTION: how to check the index is desc  or asc?

### ISSUE THREAD

**Issue by s-chance** [dbgate/dbgate#514]
**Details:**
I use this to create an index
```sql
CREATE INDEX "desc_index_cno" 
ON "courses" (
  "cno" DESC
);
```
but when I open the structure about the table, I find that the index is describe as a "ASC" index.
is something wrong here？

**Version Information**
Operating System: `archlinux x86_64`
App Version: `5.2.2-1`

**Screenshot**:
![图片](https://user-images.githubusercontent.com/91258620/223367883-a9dbb3ef-08ee-41c7-a95c-19daed9a854a.png)

**Comment by s-chance** [comment]
I have tried to restart it again and agian, but it seemd to work not very well.
I have to configure it manually without using sql.

**Comment by janproch** [comment]
Which SQL engine are you using?

**Comment by s-chance** [comment]
> Which SQL engine are you using?

I'm not sure the default engine.I'm using an opensource database `openGauss` which based on postgresql.

**Comment by s-chance** [comment]
I make a test: I execute this sql in dbgate and check the table struct in other DBMS.  
The result show that the sql is execute successfully.  
I get the expected index type in other DBMS, but I can't get the right index type when I trying to create an "DESC" index in dbgate. So maybe it's a page display issue?

**Comment by janproch** [comment]
There was missing detecting of ASC/DESC flag on postgres
