### ISSUE TITLE
BUG: dbgatePluginExcel not working

### ISSUE THREAD

**Issue by sasulnik** [dbgate/dbgate#520]
Dear all,

I'm using last version of DbGate 5.2.4 on Windows 11 Pro (x64 based processor) and dbgate script for exporting a view from SQLite database into the excel stopped working. See the attached screenshot. Any thoughts what it can be? 
Excel export was working for me last time in version 5.2.2. The csv export is still working.

BR,
Alex

![dbgate_2023-03-13 091626](https://user-images.githubusercontent.com/127728018/224644485-cc83c14f-73af-464d-8d33-d19c0ffa689e.png)

**Comment by janproch** [comment]
Probably the same problem as https://github.com/dbgate/dbgate/issues/511

I have replicated it, it should be solved now. I have downgraded xlsx package version to version used in 5.2.2. I tried to upgrade this because of other excel related problem, but it did't solve it anyway.

**Comment by sasulnik** [comment]
Thanks for information.

**Comment by sasulnik** [comment]
BTW. When plugin was exporting data to the excel in earlier versions the size of the excel was not compressed (xlsx). I usually opened the file and saved it then xlsx/zip compression started to work.
