### ISSUE TITLE
QUESTION: Cancel query

### ISSUE THREAD

**Issue by leonardochen** [dbgate/dbgate#521]
**Details:**
Is there a way to cancel a query?
I launched a query and it was taking too long to complete. I could not find a way to abort it.
The bottom right shows that the query is executing, and it's been running for a minute. I failed to add a LIMIT clause in a pretty large database.

**Version Information [might be relevant to your issue]**
Operating System: MacOS
App Version [help -> about]: Version: 5.2.3

**Comment by janproch** [comment]
Yes, you can use "Kill" button - query will be canceled and query session closed

**Comment by leonardochen** [comment]
Oops, I did not see that button on the results panel.... thank you!
![image](https://user-images.githubusercontent.com/495515/227252678-2bb373b3-110c-4c9f-9a42-da86e956f18b.png)
