### ISSUE TITLE
BUG: operator does not exist: uuid ~~* unknown

### ISSUE THREAD

**Issue by egoan82** [dbgate/dbgate#522]
**Describe the bug**
Searching through the filter for a uuid throws this error
operator does not exist: uuid ~~* unknown
per sql query works fine

**To Reproduce**
1. I enter the table and the filter I write the uuid

**Expected behavior**
When entering the uuid value in the filter, I expect it to return the rows that contain that value

**Screenshots**
![image](https://user-images.githubusercontent.com/29617555/227639134-d36d9d77-259d-4f65-8d99-c77f3bb34b67.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu 22.04
 - App Version 5.2.5
 - Install source package .deb
 - Type - Application
 - Database engine: PostgreSQL

**Comment by blakegearin** [comment]
I have having this issue as well on every table.

OS: macOS 13.4.1 (22F82)
App Version 5.2.6
Install source Homebrew
Type - Application
Database engine: PostgreSQL

**Comment by twcyao** [comment]
+1 for this

**Comment by egoan82** [comment]
Hello,

I can confirm that the filter search by uuid is functional.

![image](https://github.com/user-attachments/assets/29bf27d5-b1d9-4a34-823d-535c09160fb5)

**Comment by twcyao** [comment]
Confirm this issue still exist in Version: 5.5.6, not in the direct filter, but in the popup window after you click 3 dot button

Steps to reproduce:
1. click the 3 dots button next to the Filter (see screenshot)
2. enter uuid in Search box
3. error `operator does not exist: uuid ~~* unknown` is shown

<img width="800" alt="image" src="https://github.com/user-attachments/assets/dd07fac8-6e43-43cd-9dec-9c68013b8b04">
