### ISSUE TITLE
FEAT: Load all the result data of query at the same time.

### ISSUE THREAD

**Issue by KeshariPiyush24** [dbgate/dbgate#527]
**Is your feature request related to a problem? Please describe.**

Suppose a query returns 1000 rows. In Workbench, all the rows are loaded at once and scrolling is continuous. However, in DBgate, new data takes time to load when scrolling down, making the process time-consuming and irritating.

**Video FYR**

https://user-images.githubusercontent.com/18307180/227777807-7b8e097c-268e-4e05-a1e7-86dffaa40797.mov

<br>

**Describe the solution you'd like**

I would prefer to have all the rows loaded simultaneously so that I don't have to wait for more data to load when scrolling down.

**Describe alternatives you've considered**

Workbench already has this functionality, where all rows are loaded at once to enable continuous scrolling.

**Comment by janproch** [comment]
Loading all rows is not good solution, it will make browsing bigger tables (eg. with millions rows) impossible. However, you could change "Page size" in "Data grid" settings. If you enter very big number (eg. million), it will work as you want, but you will wait very long when working with big tables

![image](https://github.com/dbgate/dbgate/assets/2543891/46155a90-8386-4cfa-a8f7-7f20f356b4de)
