### ISSUE TITLE
Clickhouse feature

### ISSUE THREAD

**Issue by sretenD** [dbgate/dbgate#532]
Is there any chance to connect to Clickhouse or create a connection to Clickhouse db?

**Comment by ProjectInfinity** [comment]
As of version 5.2.5 it is not possible to connect to Clickhouse.

Clickhouse while using a SQL-like query language, is not fully compliant with ANSI SQL.

It would likely require its own driver.

Until such a driver is available in DbGate you can use DBeaver to connect to Clickhouse.

**Comment by janproch** [comment]
The first version of ClickHouse support is implemented in latest BETA version, https://github.com/dbgate/dbgate/releases/tag/v5.4.5-beta.2

ClickHouse support is available in Community (Free and opensource) edition
