### ISSUE TITLE
BUG: cannot filter by uuid field in psql

### ISSUE THREAD

**Issue by opensas** [dbgate/dbgate#538]
**Describe the bug**

 cannot filter by uuid field in psql

**To Reproduce**

open a query and execute

```
CREATE TABLE IF NOT EXISTS "test" (
  id uuid DEFAULT gen_random_uuid () PRIMARY KEY,
  name varchar NOT NULL
);

insert into test (name) values ('my name');

select * from test
```

copy the value of id field

![image](https://user-images.githubusercontent.com/481687/231280071-4ac61e31-630b-47fe-8b97-7401cd90f455.png)

fitler by that value

![image](https://user-images.githubusercontent.com/481687/231280190-e85c6943-6dc7-42f8-9d9e-e85b7cde12b8.png)

error:
![image](https://user-images.githubusercontent.com/481687/231280229-d3767a52-d7c2-4f47-8c80-9cf6bcc90eba.png)

open query
![image](https://user-images.githubusercontent.com/481687/231280254-2dd9f98c-618d-407c-82a1-9eed0fbeb020.png)

if you replace the ILIKE with `=` it just works

![image](https://user-images.githubusercontent.com/481687/231280413-07213fcf-0ab4-48e8-98ac-b0308efd261d.png)

**Expected behavior**
to correctly filter by id

**Screenshots**
already did

**Version Information (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - App Version [5.2.5]
 - Install source [e.g. installer]
 - Type - Application
 - Database engine: [e.g. PostgreSQL]

**Comment by gustavobittencourt** [comment]
👀
