### ISSUE TITLE
DB Gate Crash

### ISSUE THREAD

**Issue by joshishobhit** [dbgate/dbgate#542]
Hello DB Gate Contributor/s,
                    This is my first writeup here. Firstly conguratulation for building such a great product. Recently with my latest DB Gate becomes unresposive and keep crashing indicating that connection is lost and some other javascript errors. Please help.

Version: 5.2.5
Build date: 2023-03-17

![image](https://user-images.githubusercontent.com/63454045/233995136-f4dcf5f3-bf69-4d37-92f9-6dfa6947938a.png)

![image](https://user-images.githubusercontent.com/63454045/233995268-5341c59d-6efa-4651-9c8e-b5507c3e8857.png)

This error comes multiple times and makes DB Gate GUI as non-resposive.

**Comment by joshishobhit** [comment]
![image](https://user-images.githubusercontent.com/63454045/233996019-4e083877-0165-4d83-ac4b-6831b5ba2a66.png)

**Comment by CircleShift** [comment]
I'm getting this error too

Version: 5.2.6
Build date: 2023-06-02
Operating system: Windows 11

It specifically happens often when my laptop falls asleep.  I'm usually connected to a localhost MySQL server, and when I re-awaken and log back in to my computer, this error will pop up a few times.

**Comment by CircleShift** [comment]
Also doesn't seem isolated.  See gorbach's comment on #272

**Comment by Zeroes1** [comment]
have trouble too, 
dbgate 5.2.6 win10 postgres DB
