### ISSUE TITLE
BUG: 5.2.6 version don's support sqlite3, 5.2.5 is ok

### ISSUE THREAD

**Issue by jony4** [dbgate/dbgate#571]
**Describe the bug**
Error: dlopen(/Applications/DbGate.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node, 0x0001): tried: '/Applications/DbGate.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/DbGate.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node' (no such file), '/Applications/DbGate.app/Contents/Resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/Applications/DbGate.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64)

Error JSON: {
  "code": "ERR_DLOPEN_FAILED"
}

Connection: {
  "engine": "sqlite@dbgate-plugin-sqlite",
  "databaseFile": "***",
  "_id": "***",
  "unsaved": false,
  "singleDatabase": true,
  "defaultDatabase": "***",
  "parent": "***"
}

Platform: darwin

**To Reproduce**
3. See error

**Expected behavior**
5.2.6 version don's support sqlite3, 5.2.5 is ok

**Screenshots**
<img width="1236" alt="image" src="https://github.com/dbgate/dbgate/assets/13718575/9aca34d3-3672-44f3-94e7-b4b05018630c">
<img width="900" alt="image" src="https://github.com/dbgate/dbgate/assets/13718575/b055284a-078f-4770-8fa8-db036cd904b2">

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version 5.2.6
 - Install source github release
 - Type - Web/Application
 - Database engine: sqlite3

**Comment by catfishlty** [comment]
I got same problem with error log in Web UI:
```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/dbgate-docker/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
```

**Comment by ProjectInfinity** [comment]
I tested right now and it is OK for me on 5.2.6 running on Linux. 

I have added a extremely basic database that I tested with, does this open correctly for you?

[test.db.zip](https://github.com/dbgate/dbgate/files/11798414/test.db.zip)

**Comment by catfishlty** [comment]
@ProjectInfinity 
I tested your `test.db` file on `5.2.6` in Docker, but I got same error message. T_T

**Comment by jony4** [comment]
> > @ProjectInfinity I tested your `test.db` file on `5.2.6` in Docker, but I got same error message. T_T
> 
> The issue is separate from macOS. I recommend making another issue as it is related to glibc and the docker image.
> 
> @jony4 Your issue seems to be that your client is failing because of you being on a Apple Silicon mac. Make sure to download the "universal" package and not the one named x64.

@ProjectInfinity thanks! I download dbgate-5.2.6-mac_x64.dmg and It's OK.

**Comment by cgxxv** [comment]
version 5.3.0, shows the same message when opening a sqlite3 database file.

**Comment by cgxxv** [comment]
version 5.3.0, shows the same message when opening a sqlite3 database file on macos x86_64.

**Comment by janproch** [comment]
@cgxxv for completeness, could you please upload error gist (Tools/Upload error to gist)?

**Comment by cgxxv** [comment]
@janproch While with version 5.3.1-beta.2 these errors disappear.
