### ISSUE TITLE
BUG: Oracle driver doesn't work on Docker version 5.2.6

### ISSUE THREAD

**Issue by emmanuel-confrere** [dbgate/dbgate#576]
**Describe the bug**
We installed the containerized DbGate application on a Linux RedHat 8.6 server.
Opening an Oracle session causes a connection error in NodeJS: NJS-045.
Oracle Instance is an RDBMS 11.

**To Reproduce**
Open a connexion on Oracle instance server.

**Expected behavior**
nothing to report

**Screenshots**
![DbGate_Oracle_cnx](https://github.com/dbgate/dbgate/assets/104738804/9f18ed0d-7d57-4955-972b-e31d172accc9)
![DbGate_Oracle_cnx_error](https://github.com/dbgate/dbgate/assets/104738804/4a5b27b5-697a-4336-876c-10693b93cef1)
![DbGate_version](https://github.com/dbgate/dbgate/assets/104738804/ee565f98-c2b8-40c4-ab57-e2800c9d2014)
![DbGate_Oracle_cnx_error_details](https://github.com/dbgate/dbgate/assets/104738804/cf0f14a3-23df-46b0-94c1-783ea98595f8)

**Version Information (please complete the following information):**
 - OS: Linux 5.4.17-2136.310.7.1.el8uek.x86_64 (Oracle Linux 8.6 - which is equivalent to RedHat 8.6)
 - Docker : Docker version 23.0.0, build e92dd87
 - App Version 5.2.6
 - Install source Docker
 - Type - Web
 - Database engine: Oracle

**Comment by janproch** [comment]
Fixed in latest BETA

https://github.com/dbgate/dbgate/releases/tag/v5.2.10-beta.2
