### ISSUE TITLE
QUESTION: What is the environment Variable for MSSQLserver trustServerCertificate option ?

### ISSUE THREAD

**Issue by bartleboeuf** [dbgate/dbgate#600]
**Details:**
I need to enable the "trustServerCertificate" option on an MSSQL Server connection. But I can't find the environment variable to automate it in Docker startup. my AWS RDS SQLServer won't allow me to connect if this option is not active.

**Version Information [might be relevant to your issue]**
Operating System: 
App Version : 5.2.6 and previous

**Screenshot [if appropriate]**:
![image](https://github.com/dbgate/dbgate/assets/4746399/1fc8c95d-5664-4aca-9b19-548f1ae6837e)

**Comment by frenchtoasters** [comment]
@bartleboeuf were you ever able to figure this one out? Im having the same issue, I found this https://github.com/dbgate/dbgate/blob/715c6f7f29cf03b24d2b6a6f3f3fe083fea0f95f/packages/api/src/controllers/config.js#L88 where its loading all the `SETTINGS_` envs and ive tried `SETTINGS_trustServerCertificate` and `SETTINGS_trustServerCertificate_${id}` but no luck on either of those. I also found here https://github.com/dbgate/dbgate/blob/715c6f7f29cf03b24d2b6a6f3f3fe083fea0f95f/packages/api/src/controllers/connections.js#L52 where it seems to be loading all the noted ENVs and the `SETTINGS_` ones are not loaded there from what I can tell. So i wonder if there is regression that this setting isnt currently working with ENVs.
