### ISSUE TITLE
FEAT: Configurable Keyboard Shortcuts

### ISSUE THREAD

**Issue by navmed** [dbgate/dbgate#63]
**Is your feature request related to a problem? Please describe.**
I guess. I'd like to be able to write a query and execute it directly from the keyboard, without having to use the mouse.

**Describe the solution you'd like**
Configurable keyboard shortcuts. I personally like Ctrl+Enter to execute queries.

**Describe alternatives you've considered**
No alternatives I can think of

**Additional context**
N/A

**Comment by janproch** [comment]
Thank you for useful feedback. In current version, it is already possible run query with shortcut, F5 .In query editor is missing context menu now, so user cannot know available shortcuts, it will be also fixed.
I will add also shortcut Ctrl+Enter to execute query into next version.

About configurable shortcuts, it is a bit more work, but I will probably add it to release after currently developed release, but I am not promising it.

**Comment by janproch** [comment]
Ctrl+Enter is now supported in 3.9.6 release

Version 4.0.0 will bring command palette like in VSCode, there is only small step to configurable keyboard shortcuts, this step is planned to 4.1.0

**Comment by navmed** [comment]
Awesome! Thanks!

**Comment by janproch** [comment]
12fd5f6

**Comment by navmed** [comment]
Awesome! Looking forward to trying it out.

**Comment by janproch** [comment]
Released in version 4.1.0

**Comment by janproch** [comment]
done
