### ISSUE TITLE
BUG: Export - Download Unauthorized in DOCKER

### ISSUE THREAD

**Issue by davidfernandoza** [dbgate/dbgate#636]
**Describe the bug**
I am exporting a database in docker and when I click to download it appears unauthorized

**To Reproduce**
1. Go to Export wizard > download

**Expected behavior**
Download file

**Screenshots**
![image](https://github.com/dbgate/dbgate/assets/24618177/82b3b9ef-fcd7-4f26-9574-fe9fd6a4cbc7)
![image](https://github.com/dbgate/dbgate/assets/24618177/dd4ed653-1d42-4952-88b2-2db22c4db258)

**Version Information (please complete the following information):**
 - OS: WSL2 - Ubuntu 22.04
 - App Version 5.2.7
 - Install source Docker
 - Type - Web
 - Database engine: MongoDB

**Comment by gdumee** [comment]
Hello,

I have the same issue.

The file is correctly created and present in the file tab, but download button in backup page doesn't work. Docker logs shows :
app_dbgate    | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
app_dbgate    |     at new NodeError (internal/errors.js:322:7)
app_dbgate    |     at ServerResponse.setHeader (_http_outgoing.js:561:11)
app_dbgate    |     at ServerResponse.E.set.E.header (/home/dbgate-docker/bundle.js:577:6822)
app_dbgate    |     at ServerResponse.E.send (/home/dbgate-docker/bundle.js:577:2440)
app_dbgate    |     at h (/home/dbgate-docker/bundle.js:610:100609)
app_dbgate    |     at authMiddleware (/home/dbgate-docker/bundle.js:610:102476)
app_dbgate    |     at s.handle_request (/home/dbgate-docker/bundle.js:417:784)
app_dbgate    |     at /home/dbgate-docker/bundle.js:403:2982
app_dbgate    |     at /home/dbgate-docker/bundle.js:403:3004
app_dbgate    |     at Function.m.process_params (/home/dbgate-docker/bundle.js:403:3517)
