### ISSUE TITLE
FEAT: support variable in sql

### ISSUE THREAD

**Issue by wonb168** [dbgate/dbgate#662]
Like this:
Select * from id=${id} and date='${dt}'

**Comment by ProjectInfinity** [comment]
Variables are something most SQL servers already support. 
For example in MySQL:

```sql
SELECT @start := 1, @finish := 10;

SELECT * FROM places WHERE place BETWEEN @start AND @finish;
```

those are user defined variables, and then there's server variables like so:
```sql
SHOW VARIABLES LIKE '%wait_timeout%';

SELECT @@sort_buffer_size;
```

Supporting variables in DbGate sounds therefore a bit unnecessary.

**Comment by wonb168** [comment]
different！
use python to run sql，and variable in python like this:
```
sql=f"select  * from id={id} and date='{dt}'
```
and `dbeaver` support ${var} format, sql like this:
```
 select * from id=${id} and date='${dt}'
 ```
and I developed a tool to replace $ in python, so this sql can run both in deaver and python,
but dbeaver too cost memory,
and I want to change to dbgate,
but dbgate can't support this.
