### ISSUE TITLE
View logs in plugin

### ISSUE THREAD

**Issue by guiguan** [dbgate/dbgate#670]
Hi, I am trying to write a plugin for DBGate. Where can I find the logs for `console.log` or `getLogger().info` invocations within a plugin, saying `connect` func? They didn't appear in either devtools console or log files.

**Comment by guiguan** [comment]
okay, if I clone this repo and use `yarn start` to run the app, I could see the logs in terminal. Still not sure how to view them if a standalone app is running

**Comment by ProjectInfinity** [comment]
Hi, what if you press F1 and enter Toggle Dev Tools in the command palette?

Click then console, is this the log you are looking for?

**Comment by guiguan** [comment]
Nope, the extension logs are not available in devtools. I had to clone the project and use yarn commands to see those logs

**Comment by ProjectInfinity** [comment]
Thanks for confirming. Closing this as you have found the solution to your problem.
