### ISSUE TITLE
Unable to select all in input field

### ISSUE THREAD

**Issue by HafeezRai** [dbgate/dbgate#673]
**Describe the bug**
When i try to select all in any input field it doesn't select all text it should select all if i wanted to clear text i use backspace to clear text 

**To Reproduce**
1. Go to any input field
2. Write some text 
3. Press Command + a to select whole text 

**Expected behavior**
it should select whole text and remove all text on backspace

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Mac
 - App Version : 5.2.7
 - Install source installer
 - Type - Application
 - Database engine: NA

**Comment by ProjectInfinity** [comment]
Hi, I am unable to replicate this issue on Linux. We use CTRL instead of Command but as you can see it works just fine.
[Screencast_20231206_140326.webm](https://github.com/dbgate/dbgate/assets/593870/b708d228-dee1-4c32-9058-c8cf25db0abb)
