### ISSUE TITLE
BUG: That could be a problem about openedTabs    /packages/web/src/utility

### ISSUE THREAD

**Issue by ymz805** [dbgate/dbgate#695]
**Describe the bug**
localforage.setItem('openedTabs', openedTabs); and localforage.setItem('openedTabs', JSON.stringify(openedTabs)); 
Save in different ways。

**Screenshots**
![1](https://github.com/dbgate/dbgate/assets/115245547/c0c2ed47-d693-4314-a402-05c7a331229c)

![2](https://github.com/dbgate/dbgate/assets/115245547/6b1288a8-952a-4657-aa51-6f3fc9488800)

**Comment by KKishikawa** [comment]
@ymz805 Your point would be correct.

When the DbGate application is started, the `localStorageGarbageCollector` is called and the following error occurs.

<img width="830" alt="image" src="https://github.com/dbgate/dbgate/assets/40572953/e2104a5d-2a70-414a-848b-d03f727ccf40">

The fix should be to not do JSON conversion.
The following processes, which use the 'openedTabs' key and are called from the main process, do not perform the conversion.

https://github.com/dbgate/dbgate/blob/1e1c26a16f3eee8ca36af9978c352f24cd214eda/packages/web/src/stores.ts#L88
https://github.com/dbgate/dbgate/blob/1e1c26a16f3eee8ca36af9978c352f24cd214eda/packages/web/src/stores.ts#L33-L44

Therefore, users currently using DbGate are considered to be stored without JSON.stringfy.

## Reproduction procedure

Environment: any kind

1. Open DbGate
2. Open some tabs (e.g., Query Editor)
3. Close DbGate
4. Relopen DbGate
