### ISSUE TITLE
import mysqldump sql file error

### ISSUE THREAD

**Issue by dcto** [dbgate/dbgate#702]
import mysqldump sql file error

Error running script: undefined 
<img width="840" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/975d3e06-eec1-431d-b94e-baf524aeae42">

**Comment by ProjectInfinity** [comment]
Hi. Which version are you running of DbGate and MySQL? Also are you able to disclose anything that could help trigger this issue?

**Comment by dcto** [comment]
> Hi. Which version are you running of DbGate and MySQL? Also are you able to disclose anything that could help trigger this issue?

running at macOS sonoma 14.2.1 with  DbGate 5.2.7 and mysql 8.0.35

<img width="280" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/3c0f5a0b-a0da-45f8-9b5f-f2a7400337bd">
<img width="610" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/7d8ef442-cace-43d5-80c1-96c6bb66e93c">

**Comment by 99Arrzel** [comment]
Same error, may be something between mysql versions?

**Comment by tomasvanagas** [comment]
Had the same issue when used a regular mysql user. When switched to mysql root password to make a connection then no problems restoring the database.

**Comment by lamualfa** [comment]
It means the user that you used doesn't have enough permissions. Switch to `root` user is the easiest solution.
