### ISSUE TITLE
QUESTION: How to set permission to acess particular connection only?

### ISSUE THREAD

**Issue by joelwuwk** [dbgate/dbgate#717]
I try to create the user and limit the user to some connection, but I no matter how to set, the permission is not work, user can still see all connection, does anyone know what is wrong?

PERMISSIONS=~widgets/app,~widgets/plugins

CONNECTIONS=user1,user2

LABEL_user1=RedShift-User1
SERVER_user1=redshift.aws.com:5439/db_external
ENGINE_user1=redshift@dbgate-plugin-postgres
PORT_user1=5439
USER_user1=user1
PASSWORD_user1=*********
DATABASE_user1=db_external
URL_user1=redshift.aws.com:5439/db_external

LABEL_user2=RedShift-User2
SERVER_user2=redshift.aws.com:5439/dh_external
ENGINE_user2=redshift@dbgate-plugin-postgres
PORT_user2=5439
USER_user2=user2
PASSWORD_user2=*******
DATABASE_user2=dh_external
URL_user2=redshift.aws.com:5439/db_external

LOGINS=user1,user2

LOGIN_PASSWORD_user1=12345
LOGIN_PERMISSIONS_user1=~*,~connections/user1

LOGIN_PASSWORD_user2=23456
LOGIN_PERMISSIONS_user2=~*,~connections/user2

**Comment by rmueller7480** [comment]
Hi,
I have the same problem - more or less, permission restriction with LOGIN_PERMISSIONS_[login] isn't working at all. All users always have all permissions. Maybe there is something documented wrong or there may be a bug. Could you verify, if other restrictions (i.e. settings) work for you?
THX! :-)
