### ISSUE TITLE
FEAT: Copy in Rightclick Context

### ISSUE THREAD

**Issue by martinandersen3d** [dbgate/dbgate#722]
**Is your feature request related to a problem? Please describe.**
In the Rightclick context menu, the "Copy" is often missing. If you use VsCode a lot, you are naturally missing theese features.

See screenshots:

**Text Selection - Copy/Paste Missing in Query Editor:**
![image](https://github.com/dbgate/dbgate/assets/19984581/f200b0dd-3c13-4fe3-b5ed-c3ef605804e0)

**Be able to Copy Just the Name of the Database**
![image](https://github.com/dbgate/dbgate/assets/19984581/ad3b66fe-3c5c-4ee3-898c-f55091a551fb)

**Be able to Copy Just the Name of the Table**
![image](https://github.com/dbgate/dbgate/assets/19984581/b124b2e0-b672-4364-b2c4-927db40c0355)

**Be able to Copy Just the Name of the Table**
![image](https://github.com/dbgate/dbgate/assets/19984581/b317572e-a249-4aa7-a8fb-86f218fd3484)

**Be able to Copy Just the Name of the Field**
![image](https://github.com/dbgate/dbgate/assets/19984581/cdbb8eb4-debd-4c5f-bb4c-762a4d14ac89)

**Describe the solution you'd like**
- That the copy option is visible as shown in screenshots

**Describe alternatives you've considered**
- I'm not sure what the best name is for the "Copy/Copy Table Name/Copy Field Name/Copy Database Name"
- Maybe there should be a "Copy" subcategory, where you you can specify more explicit what to copy.

**Comment by ProjectInfinity** [comment]
Makes sense to me to include this option in several places. I will look into it.

**Comment by stefnnn** [comment]
+1, just wanted to create a feature request, but there it already is 👌
My main use case is «Copy table name» from the «TABLES, VIEWS, FUNCTIONS» list in the left bottom pane. But the other ones definitely make sense as well.

My appreciation for the very usable tool, I really like dbGtae!

**Comment by ProjectInfinity** [comment]
I've started adding copy/paste to the following branch. Feel free to build it if you would like to test.

https://github.com/dbgate/dbgate/tree/copy-paste-improvements

**Comment by martinandersen3d** [comment]
What is the steps to get this into the program? Do we need to file a pull request or what is the steps? 

Thanks

**Comment by ProjectInfinity** [comment]
It needs to be finished. A few of the suggestions have been implemented in a feature branch but have not been merged into master yet.
