### ISSUE TITLE
can`t connect to  oracledb

### ISSUE THREAD

**Issue by Lightofwang** [dbgate/dbgate#726]
connectString: useDatabaseUrl ? databaseUrl : port ? `${server}:${port}` : server,

when i use Fill database connection details   input current server , port,  user, password 
then connect fail :
 ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA

when Use database URL
example:1521/xxxx
also  connect fail :  
ORA-01017 : invail  username/password :  login denied 

how can  i connect to oracle

**Comment by LawrenceJiang** [comment]
Me too.

**Comment by janproch** [comment]
Fixed in latest BETA

https://github.com/dbgate/dbgate/releases/tag/v5.2.10-beta.2

**Comment by Lightofwang** [comment]
thank you ! ,
