### ISSUE TITLE
BUG: Unable to see all the result tabs

### ISSUE THREAD

**Issue by cesarValdivia** [dbgate/dbgate#730]
**Describe the bug**
Unable to see all the result tabs

**To Reproduce**
1. Open a new DB connection.
2. Run a new Query that will generate more than 20 result tabs.
3. See error

**Expected behavior**
Be able to see all the result tabs.

**Screenshots**
![image](https://github.com/dbgate/dbgate/assets/33098181/729de09c-da54-4b4e-a9c4-c7ffbacbd528)

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.2.7
 - Install source: installer
 - Type - Web/Application
 - Database engine: SQL Server

**Comment by ProjectInfinity** [comment]
Confirmed, tab bar needs to be scrollable when the window is too small to fit results.

**Comment by ProjectInfinity** [comment]
This is fixed in master and will be in a beta near you soon.

**Comment by janproch** [comment]
Changed - now only tabs bar is scrolled, tab content remains fixed
