### ISSUE TITLE
BUG: Clicking on fields in table view doesn't work.

### ISSUE THREAD

**Issue by ApproachingApathy** [dbgate/dbgate#733]
**Describe the bug**
I can't click on most fields in table view.

**To Reproduce**
1. Open any table with 4+ fields.
2. Try to click on field 4.

**Expected behavior**
The field should respond to my click.

**Version Information (please complete the following information):**
 - OS: Arch Linux (AUR)
 - App Version: 5.2.7
 - Install source: AUR
 - Type - Web/Application
 - Database engine: Postgres

**Comment by ApproachingApathy** [comment]
The issue was my window manager.

**Comment by ProjectInfinity** [comment]
@ApproachingApathy Which window manager did this issue occur under out of curiosity?

**Comment by ApproachingApathy** [comment]
Hyprland, it seemed like my monitor layout was bugged.
