### ISSUE TITLE
FEAT: Need more detail message

### ISSUE THREAD

**Issue by yutent** [dbgate/dbgate#737]
![image](https://github.com/dbgate/dbgate/assets/11972650/9cf47198-8804-43e4-90a4-fca2a8478287)

Connect failed, but it did not return any useful information. I hope it can correctly return useful information about the failure.
On the same target machine, I can connect normally using `Sequel Ace`, and I can also connect normally using Python libraries

**Comment by ProjectInfinity** [comment]
Which password authentication plugin do you use on your MySQL database?

**Comment by yutent** [comment]
5.3.0 works well now.
