### ISSUE TITLE
QUESTION: Deactivate MongoDB Profiler?

### ISSUE THREAD

**Issue by aschr** [dbgate/dbgate#745]
We have some problems with the profiler for MongoDB. As we do not need this function, we would like to deactivate it. Is this possible, for example with environment variables?

**Comment by janproch** [comment]
There is new permission dbops/profiler, which could be revoked

Or use permission administration in PRO version

![image](https://github.com/user-attachments/assets/c89d3043-6ad4-498c-b875-c67473920a68)

It is in master, it will be available in few days in BETA
