### ISSUE TITLE
BUG: an "a javascript error occurred in the main process" error dialog poped after pc wake from sleep

### ISSUE THREAD

**Issue by GeeMing** [dbgate/dbgate#746]
**Describe the bug**
a error dialog will poped after my pc wake from a sleep

**To Reproduce**
1. open DBGate
2. make pc into sleep mode 
3. wait for a while
4. wake the pc up and login to Windows, the error dialog poped

**Screenshots**
![image](https://github.com/dbgate/dbgate/assets/11847282/5dc30470-bc18-4cd7-b3ec-107695168190)

**Version Information:**
 - OS:  Windows 11
 - App Version 5.2.7
 - Install source: installer

**Comment by yaojingdeweiba** [comment]
I have the same bug too.

**Comment by janproch** [comment]
Maybe better, but still active with the new electron

Will try this:
https://github.com/electron/electron/issues/2479
