### ISSUE TITLE
unable to run DBGate in Ubuntu

### ISSUE THREAD

**Issue by vsoong889** [dbgate/dbgate#748]
I am using Ubuntu 22.04.4 LTS.

I had installed DBGate via "sudo snap install dbgate".

After installation, I tried to run it. There is nothing, Just a blank white screen.

Am I missing something?

**Comment by ProjectInfinity** [comment]
Try using the deb file found here:
https://github.com/dbgate/dbgate/releases/tag/v5.2.8-beta.10
