### ISSUE TITLE
Horizontal scrolling in with touchpad is too quick. It's difficult to scroll sensitively.

### ISSUE THREAD

**Issue by crypto-yus** [dbgate/dbgate#754]
**Describe the bug**
Horizontal scrolling with touchpad is too quick. It's difficult to scroll sensitively.

**To Reproduce**
Open a table with more columns that needs to be scrolled horizontally.

**Expected behavior**
In MacOS, with touchpad, I can smoothly scroll in table view,  both horizontal and vertical directions.

**Version Information (please complete the following information):**

OS: Mac
App Version: 5.2.7
Install source:installer
Type - Application
Database engine: MySQL

**Comment by ProjectInfinity** [comment]
Hi, we are aware as this is because it scrolls the headers as opposed to the view. Closing the ticket as duplicate.
