### ISSUE TITLE
FEAT: Display comments into TABLES and COLUMNS lists

### ISSUE THREAD

**Issue by dcto** [dbgate/dbgate#755]
Perfect database tool, i hope add comment into that's

**Display Table comment in the TABLES list**
<img width="287" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/89b8a2e6-7dd9-4ba4-82c5-7119277260b0">

**Display field comment in the COLUMNS list**
<img width="321" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/52759a60-09b1-449d-9619-2d62a01b9249">

**Comment by photowey** [comment]
I'm looking forward to this feature too!

**Comment by mutecamel** [comment]
Me too!

**Comment by mutecamel** [comment]
Or, a tooltip, that supports search

**Comment by dcto** [comment]
my dream came true in the Dbgate v6.1.0,  thanks for [janproch](https://github.com/janproch) love dbgate
