### ISSUE TITLE
BUG: Macros Execute button not working

### ISSUE THREAD

**Issue by abhi-deshpande** [dbgate/dbgate#765]
**Describe the bug**
Whenever a macro is used to let's say change data type or text replacement, the output is previewed correctly in the table, but clicking execute does not actually change anything and the data remains as is.

**To Reproduce**
1. Open a table you wish to perform cleanups.
2. Select a columns and expand macro section.
3. Select a macro and press execute.
4. Nothing happens.

**Expected behavior**
The data should be manipulated as macro says.

**Screenshots**
![IMG-20240502-WA0014](https://github.com/dbgate/dbgate/assets/56992370/686522a9-c65c-4f37-827c-5505fe7d87a4)

Worker fails to load.

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version 5.2.7
 - Install source : installer provided on GitHub release page
 - Type - Application
 - Database engine: MariaDB

**Comment by janproch** [comment]
I cannot reproduce this, for me it works. Which macro are you testing? These errors in logs are normal, they should be fixed in future by redesigning macros, but it shoulod work event with these errrors

**Comment by abhi-deshpande** [comment]
I was using the "Search & Replace Text" macro when I discovered the error. Then I tested other macros and found that they also were not working. See this short clip :

https://github.com/user-attachments/assets/e05eb6f5-dcad-4a42-8256-2adaf259d8b6

See, when I selected the columns to edit, and then clicked on a desired macro, it previews correctly, but after clicking on execute, those changes were not done in-place.
This time, the version is 5.3.1 and is being used along with MariaDB 11.4.2 on Windows 11 23H2 (22631.3880 build)

**Comment by abhi-deshpande** [comment]
I am experiencing this same issue on Debian as well. This time I suspected mariadb to be a culprit and installed postgres side by side. But found both the mariadb and postgres connections have this issue. I don't know if these are related to the issue, but -

- The data is loaded from a `.csv` file.
- The connection is local.
- Database credentials are locally saved in dbgate.
- Querying works fine, but macro changes are not stored.
- I don't know if I am doing anything incorrect while loading data.

**Comment by abhi-deshpande** [comment]
Hey..! After I upgraded all my instances of dbgate to Version 5.4.4, it is now saving the changes made through macros into the database. Many things seem to have changed and macros seem to be fixed. This issue can be closed now.

**Comment by janproch** [comment]
OK, thanks for info
