### ISSUE TITLE
Website dbgate.org down?

### ISSUE THREAD

**Issue by abcnow** [dbgate/dbgate#766]
I have been trying to ope dbgate website but I can't access the site...I wonder if this project is dead?

**Comment by abhi-deshpande** [comment]
Yes. The website is down. I was also trying yesterday.

But the project is certainly not dead. It seems a technical glitch.

**Comment by ProjectInfinity** [comment]
Yes it seems that dbgate.org is not resolving.

I have alerted @janproch about it

**Comment by ProjectInfinity** [comment]
This has been resolved.
