### ISSUE TITLE
BUG: SSH Tunnel does not work 

### ISSUE THREAD

**Issue by dcto** [dbgate/dbgate#778]
Mac os M2 14.4.1 

<img width="389" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/aace164f-4569-485c-aeee-a6e1dce592dc">

<img width="790" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/6775cc0e-795c-453e-a224-8beafb3537c1">

<img width="475" alt="image" src="https://github.com/dbgate/dbgate/assets/5618679/50d3f946-02e3-4f59-b6c4-f6298b55f69c">

**Comment by dcto** [comment]
> I have the same issue. Have you solved it?

no,  already try any beta version of 5.2.8,  the same question.    i'm rollback to 5.2.7

**Comment by ProjectInfinity** [comment]
Please try the following Beta https://github.com/dbgate/dbgate/releases/tag/v5.2.9-beta.1

**Comment by dcto** [comment]
> Please try the following Beta https://github.com/dbgate/dbgate/releases/tag/v5.2.9-beta.2

thx,  work for me.
