### ISSUE TITLE
FEAT: Add option to disable automatic updates

### ISSUE THREAD

**Issue by pgp** [dbgate/dbgate#782]
**Is your feature request related to a problem? Please describe.**

After silent update from 5.2.7 to 5.2.8, my postgres local connection won't show me tables anymore.

**Describe the solution you'd like**

I hate automatic updates, I want to decide whether and when to perform an application update - especially when such updates cause problems like this (so I'm compelled either to temporarily switch to Dbeaver, or to redownload old version 5.2.7 from GH Releases page, and use it offline).
Please add a button or an option to disable automatic updates. Thanks.

**Comment by janproch** [comment]
I created hotfix https://github.com/dbgate/dbgate/releases/tag/v5.2.7-beta.100
This version is identical as 5.2.7, only --disable-auto-upgrade was added

You can run it as following:
./dbgate-5.2.7-beta.100-linux_x86_64.AppImage --disable-auto-upgrade

Disable flag is saved to config, next time, you run appimage, auto-upgrade is not fired, until you use arg --enable-auto-upgrade

**Comment by pgp** [comment]
Thank you very much sir. It is very annoying to have things get suddenly broken while working.

**Comment by janproch** [comment]
In newest version, option --disable-auto-upgrade was removed

There is new option in settings handling this

![image](https://github.com/user-attachments/assets/5f70d836-2fd8-42e4-8c7e-540c4c18f66f)
