### ISSUE TITLE
Changing project license from MIT to GPL?

### ISSUE THREAD

**Issue by datgausaigon** [dbgate/dbgate#785]
Hi, 
What do you think about changing the License of this project from MIT to GPL?
Thanks ❤️

**Comment by ProjectInfinity** [comment]
Personally I have no interest in moving from a permissive to a restrictive license.

**Comment by datverse** [comment]
> Personally I have no interest in moving from a permissive to a restrictive license.

Hi, Thanks for your reply.
Love your project. ❤️

**Comment by blurayne** [comment]
GPLv3 is a "legal hack" for protection of free software. Companies could basically do whatever they like with MIT. So the question is by which perspective you see "restricted".

But OK, author's choice. Just my 5cents.

**Comment by ProjectInfinity** [comment]
> GPLv3 is a "legal hack" for protection of free software. Companies could basically do whatever they like with MIT. So the question is by which perspective you see "restricted".
> 
> But OK, author's choice. Just my 5cents. Don't want to spark a discussion here.

The sole reason I started contributing to dbgate was because it was MIT and GPL is hostile towards companies (which is where I use dbgate).

GPL is a restrictive license per its definition, it promotes OSS by strong arming everyone to conform. MIT is more libre in that sense, use however you want. Personally I like that.

**Comment by datverse** [comment]
Hi @blurayne , @ProjectInfinity 
Thanks for your reply. Your explanations are very helpful. ❤️

**Comment by janproch** [comment]
License changed, more context here: https://dbgate.org/development/2024/06/25/premium.html
