### ISSUE TITLE
BUG: Remove Connection

### ISSUE THREAD

**Issue by datgausaigon** [dbgate/dbgate#789]
Hi, in latest version of DbGate I can not find the way to remove/delete a Connection.
Please check
Thanks ❤️

**Comment by datverse** [comment]
Hi, 
Current I delete Connection by this way:
- In macOS go to: /Users/{username}/.dbgate
- Edit file connections.jsonl
- Find and Remove the Connection want to remove. ---> delete it.

**Comment by ProjectInfinity** [comment]
You can just right click the connection.

![image](https://github.com/dbgate/dbgate/assets/593870/69350cab-4a47-4297-a6d8-0b2ba81f7134)

**Comment by datgausaigon** [comment]
Hi @ProjectInfinity ,
My "Right Click" don't like you.

![Screenshot 2024-05-20 at 10 17 13](https://github.com/dbgate/dbgate/assets/2121900/1d1b1e65-4611-4b0d-bfbf-0efdb3a9a3e5)

**Comment by janproch** [comment]
Click "Disconnect" first. Connected connection could not be removed

**Comment by datgausaigon** [comment]
@janproch Thank you very much ❤️.
@ProjectInfinity I got it. I think the steps for this need to be noted in the wiki and instructions of DbGate. ❤️

![Screenshot 2024-05-20 at 13 53 56](https://github.com/dbgate/dbgate/assets/2121900/ad44dc85-9398-4d60-b197-2ddc487f9b24)
