### ISSUE TITLE
FEAT: Wayland support

### ISSUE THREAD

**Issue by VosaXalo** [dbgate/dbgate#792]
Hello, 
I have just installed this software and I see that it is still running on X11 protocol.
It would be nice to migrate to, or add, the Wayland protocol too.

Thank you for your excellent work 👍.

**Comment by ProjectInfinity** [comment]
Hi. How did you install dbgate?

**Comment by VosaXalo** [comment]
Hi @ProjectInfinity ,

I installed with the flatpak package.
In the flatpak permissions there is the "X11 windows manager" activated. If instead I try to activate the "Wayland windows manager" the app doesn't open at all.

**Comment by VosaXalo** [comment]
Yes, this way it works.
Question: this is the only way to go, or in a future release this could be included "automatically" in the flatpak package, so everyone could run DbGate straightforward?

Thank you for your support.

**Comment by ProjectInfinity** [comment]
For now this is how you must do it. You can edit the environment variable for dbgate using flatseal and that should persist so you just continue to use the desktop file.

**Comment by janproch** [comment]
I created PR with new flathub configuration, which should choose wayland by default: https://github.com/flathub/org.dbgate.DbGate/pull/3

Could you please test the build?

```flatpak install --user https://dl.flathub.org/build-repo/105059/org.dbgate.DbGate.flatpakref```

**Comment by VosaXalo** [comment]
Hi @janproch ,

the updated build works perfectly.
Thank you very much for your very quickly and kind support 😊 👍 👏
