### ISSUE TITLE
BUG: PostgresSQL doesn't show tables when connected

### ISSUE THREAD

**Issue by stomper013** [dbgate/dbgate#793]
**Describe the bug**
I have tried re-install application many times to fix this problem but can't resolve it.

**Screenshots**
![Screenshot from 2024-05-20 10-05-35](https://github.com/dbgate/dbgate/assets/76610072/f059a235-a799-4130-8518-d31ef1f9dbd1)

**Version Information:**
 - OS: Ubuntu
 - App Version: Latest/stable 5.2.8
 - Install source: SNAP
 - Type - Web/Application
 - Database engine: PostgreSQL (15.7-1.pgdg120+1)

**Comment by hadanhtuan** [comment]
me too

**Comment by janproch** [comment]
What version of PostgreSQL are you using? I was unable to replicate this

**Comment by ashishkpoudel** [comment]
> What version of PostgreSQL are you using? I was unable to replicate this

postgres:13-alpine local running on docker
postgres 15.5 running on RDS (PostgreSQL 15.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-12), 64-bit)

**Comment by janproch** [comment]
I am trying the same version postgres:13-alpine and it works...

Could you please send me logs (Tools/Open logs) ?
Or a dump of database structure?

Probably there is anything in your DB, that causes the DbGate analyzer to fail

**Comment by ashishkpoudel** [comment]
> I am trying the same version postgres:13-alpine and it works...
> 
> Could you please send me logs (Tools/Open logs) ? Or a dump of database structure?
> 
> Probably there is something in your DB, that causes the DbGate analyzer to fail

I can share you the logs

**Comment by stomper013** [comment]
> What version of PostgreSQL are you using? I was unable to replicate this

I using Postgres in Docker version 15.7-1.pgdg120+1

**Comment by janproch** [comment]
@ashishkpoudel in the logs, there is no info about DB connection. Could you please try attach the console output?

**Comment by emmanuelpineda** [comment]
Is there a way to disable automatic update, The previous version (5.2.7) works fine, but it automatically updates to version 5.2.8

**Comment by janproch** [comment]
Another disable update workaround:

Use this hotfix: https://github.com/dbgate/dbgate/releases/tag/v5.2.7-beta.100
This version is identical as 5.2.7, only --disable-auto-upgrade was added

You can run it as following:
./dbgate-5.2.7-beta.100-linux_x86_64.AppImage --disable-auto-upgrade

Disable flag is saved to config, next time, you run appimage, auto-upgrade is not fired, until you use arg --enable-auto-upgrade

However, this is critical issue, which must be solved also in new version. I was unable to replicate it, with my databases it works also on 5.2.8. I will try to add more logging.

Could someone please try these following queries on databases, which shows no tables? If these queries return reasonable data, it is OK, it they return no rows, we found the problem!

This should return all tables:
```sql
 select infoTables.table_schema as "schema_name", infoTables.table_name as "pure_name", 
 (
     select md5(string_agg(
         infoColumns.column_name || '|' || case when (infoColumns.data_type = 'USER-DEFINED' OR infoColumns.data_type = 'ARRAY') then infoColumns.udt_name::regtype::text else infoColumns.data_type end || '|' || infoColumns.is_nullable::varchar(255)  || '|' || coalesce(infoColumns.character_maximum_length, -1)::varchar(255) 
             || '|' || coalesce(infoColumns.numeric_precision, -1)::varchar(255) ,
         ',' order by infoColumns.ordinal_position
     )) as "hash_code_columns"
     from information_schema.columns infoColumns 
     where infoColumns.table_schema = infoTables.table_schema and infoColumns.table_name = infoTables.table_name
 ),
 (
     select md5(string_agg(
         infoConstraints.constraint_name || '|' || infoConstraints.constraint_type ,
         ',' order by infoConstraints.constraint_name
     )) as "hash_code_constraints"
     from information_schema.table_constraints infoConstraints 
     where infoConstraints.table_schema = infoTables.table_schema and infoConstraints.table_name = infoTables.table_name
 )
```
 
And this should return all columns:
```sql
select infoTables.table_schema as "schema_name", infoTables.table_name as "pure_name"
from information_schema.tables infoTables 
where infoTables.table_type not like '%VIEW%' 
  and ('tables:' || infoTables.table_schema || '.' ||  infoTables.table_name) is not null
and infoTables.table_schema <> 'pg_catalog'
and infoTables.table_schema <> 'information_schema'
and infoTables.table_schema <> 'pg_internal'
and infoTables.table_schema !~ '^pg_toast'


select 
	table_schema as "schema_name", 
	table_name as "pure_name", 
	column_name as "column_name",
	is_nullable as "is_nullable",
	case
		when (data_type = 'USER-DEFINED' OR data_type = 'ARRAY') then udt_name::regtype::text
		else data_type
	end
	as "data_type",
	character_maximum_length as "char_max_length",
	numeric_precision as "numeric_precision",
	numeric_scale as "numeric_scale",
	column_default as "default_value"
from information_schema.columns
where 
		table_schema <> 'information_schema' 
		and table_schema <> 'pg_catalog' 
		and table_schema !~ '^pg_toast' 
		and (
			('tables:' || table_schema || '.' || table_name) is not null
			or
			('views:' || table_schema || '.' || table_name) is not null
		)
order by ordinal_position
```

The following query is not used on new postgres, but for completeness, it should also return all tables
```sql
select infoTables.table_schema as "schema_name", infoTables.table_name as "pure_name"
from information_schema.tables infoTables 
where infoTables.table_type not like '%VIEW%' 
  and ('tables:' || infoTables.table_schema || '.' ||  infoTables.table_name) is not null
and infoTables.table_schema <> 'pg_catalog'
and infoTables.table_schema <> 'information_schema'
and infoTables.table_schema <> 'pg_internal'
and infoTables.table_schema !~ '^pg_toast'
```

**Comment by janproch** [comment]
@kyleli666 thanks, could you please test it again? Pasting in github somehow mixed the queries, so first one was incomplete, now they are correct
Sorry for that

**Comment by janproch** [comment]
I did some tests and this is still mystery for me

@kyleli666 as I understood, query "select * from information_schema.columns" returns error "type compressed_data does not exist", it seems to problem in postgreSQL installation

I added some logging to postgreSQL analyser, if someone could try it with BETA 5 https://github.com/dbgate/dbgate/releases/tag/v5.2.9-beta.5

You could use new diagnostic function "Tools/Upload error to gist", which uploads logs and your platform configuration to Gist.
Here is uploaded error gist sample: https://gist.github.com/janproch/6a3d7aa251a2a454b8d9e51cb995f4a5

Also in BETA 5 I fixed a bug, that many logs are missing in log file, these logs were only in console output

**Comment by janproch** [comment]
@kyleli666 Thanks, now I see in logs, that there are errors when processing queries loading tables and table columns. 

I have released new BETA https://github.com/dbgate/dbgate/releases/tag/v5.2.9-beta.6 , which hopefully fixes this, could you please try this?
