### ISSUE TITLE
BUG: Unable to open SQL files

### ISSUE THREAD

**Issue by cesarValdivia** [dbgate/dbgate#797]
**Describe the bug**
I recently installed the v5.2.8 and now I'm unable to open any SQL file using the "File->Open" action.

**To Reproduce**
1. Go to File
2. Click on Open (Ctrl + O)
3. Select a SQL file to open
4. The file doesn't open in the Editor

**Expected behavior**
The file selected should be opened in the Editor.

**Screenshots**
If applicable, add screenshots to help explain your problem

https://github.com/dbgate/dbgate/assets/33098181/d9250334-285e-4884-8d41-1a69503ceafb

.

**Version Information (please complete the following information):**
 - OS: Windows
 - App Version 5.2.8
 - Install source installer
 - Type - Application
 - Database engine: SQL Server

**Comment by janproch** [comment]
OK, I replicated it, this should be fixed soon

**Comment by agranera** [comment]
same problem in my side
