### ISSUE TITLE
BUG: Database postgres is empty or structure is not loaded MacOS

### ISSUE THREAD

**Issue by bikeDevs** [dbgate/dbgate#805]
In the new version (5.2.8), when you try to load the database structure, it does not load and only the following message is displayed.

![Captura de pantalla 2024-05-28 a la(s) 11 55 35 a m](https://github.com/dbgate/dbgate/assets/25216368/d6936e96-1055-4b73-93f4-4426c80f6426)

The previous version (5.2.7) does not have this problem.

I install version 5.2.7 but when I close and reopen it updates automatically.

Has anyone been able to fix this error or disable automatic updating?

**Version Information:**
 - OS: MacOS Sonoma
 - App Version 5.2.8
 - Database engine: PostgreSQL

**Comment by janproch** [comment]
I am solving this in issue https://github.com/dbgate/dbgate/issues/793

In the meantime, you could use old version with this workaround:

Use this hotfix: https://github.com/dbgate/dbgate/releases/tag/v5.2.7-beta.100
This version is identical as 5.2.7, only --disable-auto-upgrade was added

You can run it as following:
./dbgate-5.2.7-beta.100-linux_x86_64.AppImage --disable-auto-upgrade

Disable flag is saved to config, next time, you run appimage, auto-upgrade is not fired, until you use arg --enable-auto-upgrade

**Comment by janproch** [comment]
I have released new BETA https://github.com/dbgate/dbgate/releases/tag/v5.2.9-beta.6 , which should have this fixed

**Comment by bikeDevs** [comment]
This beta version resolved the bug.
I will wait for the stable version.

Thanks.

**Comment by janproch** [comment]
Fix released in 5.2.9
