### ISSUE TITLE
Oracle database connection

### ISSUE THREAD

**Issue by dc-da** [dbgate/dbgate#809]
Hi!

where I can set service_name or sid in the create new connection panel when I try to connect to an oracle database?

Thanks a lot

**Comment by janproch** [comment]
Service name is supported in latest BETA

https://github.com/dbgate/dbgate/releases/tag/v5.2.10-beta.2

**Comment by krisgh** [comment]
I think can be used v$version instead of v$instance to get the version, since not all users have permissions.

**Comment by janproch** [comment]
@krisgh thanks for the idea. I changed it to use product_component_version, v$version as fallback. Also when none of these views is accessible, it works, only without version info
