### ISSUE TITLE
BUG: Redshift doesn't show tables when connected

### ISSUE THREAD

**Issue by minayaserrano** [dbgate/dbgate#816]
**Describe the bug**
It is the same issue as #793 and #805 but on a Redshift connection.

**To Reproduce**
1. Connect to a Redshift database.
2. See error on TABLES, VIEWS, FUNCTIONS

**Expected behavior**
It should show the tables of the database.

**Screenshots**

**Version: 5.2.9**
![Screenshot from 2024-06-03 17-17-17](https://github.com/dbgate/dbgate/assets/638574/f4b346b7-358b-41fd-9d89-bfdda67a6353)

**Version: 5.2.10-beta.4**
![Screenshot from 2024-06-03 17-20-21](https://github.com/dbgate/dbgate/assets/638574/8ca88a9c-5388-4d13-8c50-64b81d6d326a)

**Version Information (please complete the following information):**
 - OS: Ubuntu 22.04
 - App Version: Version: 5.2.9 / Version: 5.2.10-beta.4
 - Install source: SNAP
 - Type: Application
 - Database engine: Redshift

**Comment by janproch** [comment]
Could you please attach logs from console output? Or even better, you could upload error to gist. from menu Tools/Upload error from gist

Thanks

**Comment by janproch** [comment]
Thanks, could you please add screenshot from 5.2.10-beta.4 with dev console output (from menu View/Toggle dev tools)

**Comment by minayaserrano** [comment]
Here it is. There doesn't seem to be anything unusual...

![dbgate-dev-tools](https://github.com/dbgate/dbgate/assets/638574/f703522b-c6fb-4307-87be-55cb0d23128f)

**Comment by janproch** [comment]
It should be fixed in newest BETA: https://github.com/dbgate/dbgate/releases/tag/v5.3.1-beta.1

**Comment by minayaserrano** [comment]
Yes, I confirm this is fixed on v5.3.1-beta.1. Thank you so much!
