### ISSUE TITLE
BUG: Column sorting on query tab not working

### ISSUE THREAD

**Issue by vJoN4** [dbgate/dbgate#819]
**Description**
After running a query, when trying to use these column sorting option: '**Sort Ascending**' or '**Sort Descending**', it throws the follwing error: 

> API error:uuidv1 is not defined

**Steps to reproduce the behavior**:
1. Click-open a 'New Query' tab
2. Run a query
3. On the result section, try to use one of the mentioned sorting options
4. See the error appear

**Expected behavior**
Sort the values ascending or descending with no error.

**Screenshots**
![image](https://github.com/dbgate/dbgate/assets/56328863/f88cf3c6-8425-4a48-b138-ebc1753a26d0)
![image](https://github.com/dbgate/dbgate/assets/56328863/1dd8248a-ceff-4021-91bc-20a339666c38)

**Version Information :**
 - OS: Windows 10
 - App Version: 5.2.9
 - Install source: installer
 - Type: Application
 - Database engine: MySQL and PostgreSQL

**Comment by timharris777** [comment]
I am experiencing this same exact issue. I run a query and then in the results try to sort by a column desc and get `uuidv1 is not defined`

**Version Information :**
OS:  OSX 14.5 (23F79)
APP Version: 5.3.0
APP Build date: 2024-05-29
APP install source: brew install dbgate
Database engine: PostgreSQL
