### ISSUE TITLE
BUG: When Write a sql in query ，but it can not show the colum of the table 

### ISSUE THREAD

**Issue by yaojingdeweiba** [dbgate/dbgate#820]
![image](https://github.com/dbgate/dbgate/assets/9206224/8b2a6ac2-17fe-4111-9381-a0e5c64e8eea)

**Comment by ProjectInfinity** [comment]
It's showing the column in the screenshot though?

**Comment by yaojingdeweiba** [comment]
i know when write some world of the column,then press  enter key ,can find then match column.thank you
