### ISSUE TITLE
BUG: Cannot read properties of undefined (reading 'length') on Tables

### ISSUE THREAD

**Issue by lenardlopezticketek** [dbgate/dbgate#824]
**Describe the bug**
not displaying the Tables under Connections
error: Cannot read properties of undefined (reading 'length')

**To Reproduce**
1. Click a database in Connections
3. See error

**Expected behavior**
should display the tables

**Screenshots**
<img width="153" alt="image" src="https://github.com/dbgate/dbgate/assets/125524006/e732b21e-9c5b-4e07-bbf7-bf1368aa4bfe">

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version 5.3.0
 - Install source portable zip
 - Type - Application
 - Database engine: Redshift

**Comment by janproch** [comment]
Duplicate to #816
