### ISSUE TITLE
BUG: Postgres Connection stays in "Loading database structure" until reloading the page

### ISSUE THREAD

**Issue by timvandruenen** [dbgate/dbgate#826]
**Describe the bug**
Since 5.2.9 my Postgres databases won't load anymore after clicking on them. When I click on a Postgres database, it keeps on "Loading database structure" in the "TABLE, VIEWS, FUNCTIONS" tab. 

In version 5.2.8 it still listed the tables etc.

The logs from server side don't throw any error, the dbAnalyser just say everything is loaded properly.

**To Reproduce**
1. use the dbgate 5.2.9 or 5.3.0 docker image
2. configure a Postgres database via ENV variables
3. click on your Postgres database in the WebUI

Once I refresh the page and click the Postgres database again, it actually works for some time.

**Expected behavior**
All tables, views etc are loaded and displayed

**Screenshots**
dbgate 5.2.8
<img width="364" alt="image" src="https://github.com/dbgate/dbgate/assets/97021856/bac6db62-36c5-4dfd-b22c-e7385c3c174b">

dbgate 5.2.9 - 5.3.0
<img width="366" alt="image" src="https://github.com/dbgate/dbgate/assets/97021856/fe398450-9fec-419e-803a-7ce55811d00e">

Chrome Developer Tools Network (dbgate 5.2.8)
<img width="750" alt="image" src="https://github.com/dbgate/dbgate/assets/97021856/6c1d40b1-a720-466f-8fda-0db94ca9e91a">

Chrome Developer Tools Network (dbgate 5.2.9)
<img width="746" alt="image" src="https://github.com/dbgate/dbgate/assets/97021856/87b148c3-c542-46ec-b538-e05f1318e86c">

**Version Information (please complete the following information):**
 - OS: Linux
 - App Version: 2.5.9 and up
 - Install source: Docker
 - Type - Web
 - Database engine: Postgres

**Comment by janproch** [comment]
Could you please attach also log from console? Or even better error gist (Tools/Upload error from gist)
Also there is bugfix in last BETA (https://github.com/dbgate/dbgate/releases/tag/v5.3.1-beta.1), which could theoretically also fix this

**Comment by timvandruenen** [comment]
Here are the logs from the server (did you mean that with console?)
[dbgate.log](https://github.com/user-attachments/files/15872408/dbgate.log)

**Comment by janproch** [comment]
Thanks, it should be fixed in newest BETA: https://github.com/dbgate/dbgate/releases/tag/v5.3.1-beta.2

**Comment by timvandruenen** [comment]
Verified, it works! Thanks.

**Comment by mthmcalixto** [comment]
Version: 6.3.3:
![Image](https://github.com/user-attachments/assets/b6c6ac65-c2ae-4811-9cee-c271dbc317c6)

Error:
![Image](https://github.com/user-attachments/assets/811ef584-714b-43b4-9f4a-ea4fa46e1612)
