### ISSUE TITLE
FEAT: Request to Add Traditional Chinese Translation

### ISSUE THREAD

**Issue by elf168** [dbgate/dbgate#842]
Dear Jan Prochazka,

Hello!

I am writing to you from Taiwan, and I would like to start by expressing my gratitude for developing such an excellent database tool. This tool has significantly benefited our work, and our team relies on it daily.

However, we have noticed that the tool currently lacks a Traditional Chinese interface. For us, having the option to use the tool in Traditional Chinese would greatly enhance our user experience and work efficiency.

Our team includes several members proficient in both English and Traditional Chinese, and we are very willing to contribute our efforts to help translate this tool into Traditional Chinese. We hope to receive your permission and guidance to begin this work.

If you have any questions or need further information about our background and plans, please feel free to contact us. We are very much looking forward to the opportunity to collaborate with you and help more Traditional Chinese users benefit from this tool.

Thank you again for your hard work, and we look forward to your response.

Best regards,

Eddie Yang
Email：ch168@elf.com.tw
MY Github Team Name： ELF INTERNATIONAL EXPRESS

**Comment by ProjectInfinity** [comment]
Hi. I've suggested adding localization in the past but it's not been a priority. 

Out of curiosity, you say you and your team rely on the tool, if we had localization support would you or your team be able to contribute towards translations?

**Comment by elf168** [comment]
Dear Jan Prochazka
Thank you for your response. Your tool is the best we have seen so far, and our team is very willing to help you with the translation. Would you prefer to do this using an i18n approach or through language packs?

**Comment by ProjectInfinity** [comment]
Hi. I am not Jan, I'm just a contributor.

It would be better left to @janproch to answer whether or not localization is important enough to focus on.

**Comment by elf168** [comment]
Dear my friend
Thank you for your response. I apologize for not mentioning earlier, but as a local resident of Taiwan, my English might not be perfect. However, I am always willing to help translate great works to benefit more Taiwanese engineers and help them appreciate this tool even more.
