### ISSUE TITLE
oracle version is too old, The thin mode is not supported

### ISSUE THREAD

**Issue by acracker** [dbgate/dbgate#843]
How to solve this problem

Oracle version : 11.2
error:
Connect failed:  NJS-138: connections to this database server version are not supported by node-oracledb in Thin mode Show detail

Error: NJS-138: connections to this database server version are not supported by node-oracledb in Thin mode
    at Object.h [as throwErr] (D:\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-oracle\dist\backend.js:2:253451)
    at t.exports.connect (D:\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-oracle\dist\backend.js:2:369839)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.<anonymous> (D:\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-oracle\dist\backend.js:2:318608)
    at async Object.connect (D:\dbgate\resources\app.asar\packages\plugins\dbgate-plugin-oracle\dist\backend.js:2:664500)
    at async e.exports (D:\dbgate\resources\app.asar\packages\api\dist\bundle.js:2:2118145)
    at async process.<anonymous> (D:\dbgate\resources\app.asar\packages\api\dist\bundle.js:2:2076719)

Error JSON: {
  "code": "NJS-138"
}

Connection: {
  "server": "***",
  "engine": "oracle@dbgate-plugin-oracle",
  "sshMode": "userPassword",
  "sshKeyfile": "***",
  "serviceName": "***",
  "user": "***",
  "password": "***"
}

Platform: win32

**Comment by ProjectInfinity** [comment]
That version is from 2013. Is it not time to update? :)

**Comment by acracker** [comment]
> That version is from 2013. Is it not time to update? :)
yes, Government enterprise. 
If it is not necessary,  will not upgrade the version

**Comment by acracker** [comment]
> That version is from 2013. Is it not time to update? :)



yes, Government enterprise.
If it is not necessary, will not upgrade the version

**Comment by acracker** [comment]
This link may be the solution, but I don't know how to fix it

https://github.com/oracle/node-oracledb/issues/1587

**Comment by paulovnas** [comment]
I was supposed to comment on this at the beginning of the month, then I saw that someone else went through this too.

I even tried the `oracledb.initOracleClient()` solution
However, it still didn't work here, since you need to have instantClient configured, but I have it configured and it still doesn't work correctly.

I loved dbgate, I really wanted it to work with Oracle too 💔

**Comment by acracker** [comment]
I prefer dbgate to dbeaver, but dbgate seems a little more problematic

**Comment by acracker** [comment]
> I was supposed to comment on this at the beginning of the month, then I saw that someone else went through this too.
> 
> I even tried the `oracledb.initOracleClient()` solution However, it still didn't work here, since you need to have instantClient configured, but I have it configured and it still doesn't work correctly.
> 
> I loved dbgate, I really wanted it to work with Oracle too 💔

Hello, how did you modify it? I'll try it, too.

**Comment by paulovnas** [comment]
> > I was supposed to comment on this at the beginning of the month, then I saw that someone else went through this too.
> > I even tried the `oracledb.initOracleClient()` solution However, it still didn't work here, since you need to have instantClient configured, but I have it configured and it still doesn't work correctly.
> > I loved dbgate, I really wanted it to work with Oracle too 💔
> 
> Hello, how did you modify it? I'll try it, too.

I made a clone of the project here, at the code level I inserted `oracledb.initOracleClient()` in the file that I don't remember the name of now, but it is the file responsible for the connection, I built the project in my local environment

**Comment by acracker** [comment]
> > > I was supposed to comment on this at the beginning of the month, then I saw that someone else went through this too.
> > > I even tried the `oracledb.initOracleClient()` solution However, it still didn't work here, since you need to have instantClient configured, but I have it configured and it still doesn't work correctly.
> > > I loved dbgate, I really wanted it to work with Oracle too 💔
> > 
> > 
> > Hello, how did you modify it? I'll try it, too.
> 
> I made a clone of the project here, at the code level I inserted `oracledb.initOracleClient()` in the file that I don't remember the name of now, but it is the file responsible for the connection, I built the project in my local environment

ok. thank you.

**Comment by ProjectInfinity** [comment]
> I was supposed to comment on this at the beginning of the month, then I saw that someone else went through this too.
> 
> I even tried the `oracledb.initOracleClient()` solution However, it still didn't work here, since you need to have instantClient configured, but I have it configured and it still doesn't work correctly.
> 
> I loved dbgate, I really wanted it to work with Oracle too 💔

@paulovnas Are you able to direct me to perhaps a docker image or something similar for such an old version of Oracle DB? I tried finding an image for it but I could not find such an old version and without one available it is very hard to test.

**Comment by acracker** [comment]
@paulovnas  After I add this code, I can connect to oracle 11g. 
![image](https://github.com/user-attachments/assets/1e379957-3c89-4854-83bf-3c8956d42e78)

**Comment by janproch** [comment]
There is one additional problem, in addition to instant client installation and initialization is also native part of node-oracledb NPM package needed. It will work for you, if you have debug version of DbGate (run locally from sources), but not in installation, because bundling of native modules as a bit problematic. I will try to handle this, but probably Oracle instant client support will go into DbGate Premium edition

**Comment by acracker** [comment]
> There is one additional problem, in addition to instant client installation and initialization is also native part of node-oracledb NPM package needed. It will work for you, if you have debug version of DbGate (run locally from sources), but not in installation, because bundling of native modules as a bit problematic. I will try to handle this, but probably Oracle instant client support will go into DbGate Premium edition

Ok, I see

**Comment by janproch** [comment]
Oracle thick mode is supported in latest BETA, https://github.com/dbgate/dbgate/releases/tag/v5.3.5-beta.3
If you have Oracle instant client installed locally, you could use DbGate Community edition. Only you have to configure client library path - folder with instant client installation

![image](https://github.com/user-attachments/assets/58a163d4-04db-46b2-b9d3-b9ebace84169)
