### ISSUE TITLE
BUG: "Cannot read properties of undefined (reading 'count')" when loading MongoDB database structure

### ISSUE THREAD

**Issue by jacobokeeffe-ow** [dbgate/dbgate#851]
**Describe the bug**
When trying to read some of my mongodb databases I see the error "Cannot read properties of undefined (reading 'count')". Other databases connections I have configured connect fine with no issue.

**Screenshots**
<img width="324" alt="CleanShot 2024-07-08 at 11 07 37@2x" src="https://github.com/dbgate/dbgate/assets/142221431/ff4ab2fe-3175-4ba1-9584-deee366f4414">

**Version Information (please complete the following information):**
 - OS: dbgate/dbgate:latest
 - App Version: 5.3.1
 - Install source: Docker
 - Type - Web
 - Database engine: MongoDB

**Comment by jacobokeeffe-ow** [comment]
I think I've found the cause of the issue here: https://github.com/dbgate/dbgate/blob/ebcad6ededf47b312fc5de7f9b6895a39cdb49cf/plugins/dbgate-plugin-mongo/src/backend/Analyser.js#L36

Looks like it still tries to acess `stats[index].count` even when `$collStats` is not supported and `stats` is set to an empty object. I'll make a quick PR so that it's instead `stats[index]?.count` which would mean `tableRowCount` is returned as undefined. That seems to work locally for me at least but I'm not sure if that might cause issues elsewhere

**Comment by jacobokeeffe-ow** [comment]
Doesn't seem like I have permission to push a branch to the repo

**Comment by ProjectInfinity** [comment]
Hi, you have to fork the project, push your changes and submit a pull request. :)

**Comment by jacobokeeffe-ow** [comment]
Great, I see that's been merged now. Would it be possible to get a beta release with that fix included?

**Comment by bxy200502367** [comment]
I have the same problem.So I use mongodb compass instead.I look forward to the revision in the future.
![image](https://github.com/user-attachments/assets/fdb2b7f6-93a9-4c0d-be98-f215a3538956)

**Comment by janproch** [comment]
This fix is already released in 4.3.4. Thanks for PR

**Comment by bxy200502367** [comment]
That's great！
The new version has indeed been fixed.
