### ISSUE TITLE
BUG: Multi column filter is broken for Postgresql

### ISSUE THREAD

**Issue by AnisRouane67** [dbgate/dbgate#855]
Hi there,

I've been using the multi-column filter feature extensively with MySQL and everything was fine, but it seems that it does not work correctly with PostgreSQL. When I search for a term, I encounter the following error: `operator does not exist: integer ~~* unknown (at line 7).`

Here is the code generated by the multi-column filter:

```
SELECT 
  "basetbl"."id" AS "id",
  "basetbl"."email" AS "email",
  "basetbl"."event" AS "event",
  "basetbl"."happenedAt" AS "happenedAt"
  FROM "public"."DraftBooking" "basetbl" 
WHERE (("basetbl"."id" ILIKE '%222%') OR ("basetbl"."email" ILIKE '%222%') OR ("basetbl"."event" ILIKE '%222%') OR ("basetbl"."happenedAt" ILIKE '%222%'))

ORDER BY "basetbl"."happenedAt" DESC
```

where "id" is an integer, "email" is a varchar, "event" is text, and "happenedAt" is a timestamp. I understand that it wants a cast for the "id" column, but I don't know if there is a way to fix that...

Thanks for your help!

EDIT : I investigated a little bit and it seems that the problem is located in postgresql plugin, in frontend/driver.js. We need to add casts (or ::TEXT) to columns that does not support text comparison like int, bigint, ...

I tried something but it seems that it does not work correctly because it breaks single column filter (I reproduced the same logic as for geometry type which is already in the driver.js file).

Can someone give me some help to figure this out?

THanks :)

**Comment by janproch** [comment]
Thanks for the analysis, it is solved now - https://github.com/dbgate/dbgate/commit/315c0670d0ff3ea8a594a128afb84e42f2196127

Instead of changing type to ::TEXT, filters are compiled according to column type

**Comment by AnisRouane67** [comment]
Thank you @janproch for the fix! I may check it this weekend locally. Do you know when will it be a part of an official release maybe? Thanks again for your work.

**Comment by janproch** [comment]
I suppose that the nearest release will be next week

**Comment by AnisRouane67** [comment]
Hello,
I tested the fix you provided, and it works well for tables without enum columns (those with "user-defined" types). I plan to investigate the enum issue further tomorrow. If you have any additional advice or insights on addressing this, I'd appreciate your input.
Thank you for your help so far.
