### ISSUE TITLE
The application Window is not visible when openning after changing monitor configuration. 

### ISSUE THREAD

**Issue by mbelanger2** [dbgate/dbgate#856]
dbGate doesn't check if position in config-root.json is still on the screen when openning. If you sometime use a multiple monitor setup and sometime you don't (IE : on a laptop), you might not be able to see the application window. The app should check if the position in the config is withing the visible bondaries of the current configuration when the application is started, and when it get the focus (if the user unplug a monitor while the app is open).

**Comment by janproch** [comment]
Fixed in BETA version
