### ISSUE TITLE
BUG: Connection permissions configuration is broken

### ISSUE THREAD

**Issue by camposdelima** [dbgate/dbgate#860]
**Describe the bug**
The documentation says that we can configure the connections allowed for the user (or for all users) using the environment variable 'PERMISSION' (or 'LOGIN_PERMISSIONS_login'), but these configurations don't work.

**To Reproduce**
1. Set the connection configuration env variables:
![image](https://github.com/user-attachments/assets/3a5e927c-cb95-4683-b063-fd9e331d0c56)
2. Set the permission configuration env variable to deny access to the configured connection:
![image](https://github.com/user-attachments/assets/2432fe5d-e2d5-404f-b683-c29e91ddcc9d)
2. Reload DBGate.
4. Observe the DBGate UI ignoring the configuration.
5. Observe the DBGate API ignoring the configuration as well.

**Expected behavior**
As documented, the UI should not show the denied connections:
![image](https://github.com/user-attachments/assets/35269a05-5765-4ca1-8f4c-553b6e5e5145)
https://dbgate.org/docs/env-variables.html

**Screenshots**
![image](https://github.com/user-attachments/assets/46b1b911-3da8-44ee-b2bb-f4a142b59d08)
![image](https://github.com/user-attachments/assets/96405f7a-fcbc-468c-a312-b3649f86e068)
![image](https://github.com/user-attachments/assets/33335061-ef31-45dc-b544-ca6021893003)

**Version Information (please complete the following information):**
 - OS: Linux(docker)
 - App Version: 5.3.1
 - Install source: Docker
 - Type: Web
 - Database engine: All

**Comment by camposdelima** [comment]
It seems related:

https://github.com/dbgate/dbgate/pull/584
https://github.com/dbgate/dbgate/issues/717

**Comment by janproch** [comment]
Now is lot of refactor of this stuff in develop branch, will be merged approx. in one month

**Comment by janproch** [comment]
The refactor is now in BETA version, permissions should be fixed now
