### ISSUE TITLE
missing Execute, Export bar

### ISSUE THREAD

**Issue by lenardlopezticketek** [dbgate/dbgate#861]
missing Execute, Export bar after 5.3.3 update.

![image](https://github.com/user-attachments/assets/cfb636c4-0239-49ea-b42c-32c386f43446)

**Comment by lenardlopezticketek** [comment]
after I right click on results it appeared again.
![image](https://github.com/user-attachments/assets/2839e143-4af4-410a-969a-e6969965178b)

**Comment by janproch** [comment]
Thanks for reporting, it is fixed now in BETA, will be released in ine hour
