### ISSUE TITLE
BUG: Linux : 5.3.3 appimage on blank system does not start (window does not appear)

### ISSUE THREAD

**Issue by mtudury** [dbgate/dbgate#862]
**Describe the bug**
Starting the DbGate 5.3.3 AppImage on an x86_64 Ubuntu system doesn't work. No other versions were installed previously.

**To Reproduce**
- On a system where DbGate has not been used before,
- download 5.3.3 appImage
- make eXecutable
- Start it.

Observed result : 
- The Window does not appear.

**Workaround**
- Download 5.3.1 appImage
- make it eXecutable
- Launch it.
- Upgrade to 5.3.3

**Expected behavior**
I expected DbGate to start properly.

**More informations**
When launching from the console, I see warnings about the settings file.

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version : 5.3.3
 - Install source : AppImage
 - Type - Web/Application ?
 - Database engine: N/A

Thanks for DbGate 🙏

I hope this report helps.

**Comment by janproch** [comment]
Thanks for reporting, it is fixed now in BETA, will be released in ine hour
