### ISSUE TITLE
BUG: DBGate Application is not opening

### ISSUE THREAD

**Issue by adarsh-chakraborty** [dbgate/dbgate#864]
**Describe the bug**
I tried installing the app on my system but DBGate window does not open. I can see the process in the Task Manager.
I've tried running it as Admin, Restarting, Tried the Zip version as well. Maybe I am missing some dependency. But I don't know what's the issue here. I am currently using the web version.

**To Reproduce**
Steps to reproduce the behavior: Open the DBGate Application

**Expected behavior**

**Version Information (please complete the following information):**
 - OS: Windows 11
 - App Version: 5.33 winx64
 - Install source: Installer/Zip

**Comment by janproch** [comment]
Please try the newest version 5.3.4 . This bug is already fixed here
