### ISSUE TITLE
notifying will update

### ISSUE THREAD

**Issue by lenardlopezticketek** [dbgate/dbgate#865]
always notifying will update even if I already exit and open.
using portable Windows version

![image](https://github.com/user-attachments/assets/df499e65-b3d1-4240-a6df-29ed0438b250)

**Comment by lenardlopezticketek** [comment]
workaround is download the latest and overwrite the existing dbgate folder

**Comment by janproch** [comment]
Portable windows installation has no support for autoupgrade

Should be fixed in the newest version
