### ISSUE TITLE
FEAT: Allow CSV and JSON files as a Data Source

### ISSUE THREAD

**Issue by djrobby** [dbgate/dbgate#87]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability to browse a static CSV or JSON file as a datasource

**Describe alternatives you've considered**
None

**Additional context**
Traditionally, I've been using Microsoft Excel/Sublime Text for CSVs and [JSONViewer](http://jsonviewer.stack.hu/) for JSON. It would be really nice to be able to view both types of files as a datasource inside **DbGate** since it already supports these formats in some way.

**Comment by janproch** [comment]
CSV files can be already imported - using drag & drop or with Open file menu, if you let the default config, imported file appears in newly created archive folder
![image](https://user-images.githubusercontent.com/2543891/115896171-6ba6ba00-a45b-11eb-8fc2-de0b05c2e125.png)

I think whether this process is reasonable difficult to be still usable...

But editing CSV files directly could be also confusing, as CSV format has varying parameters (delimiter, encoding...)

About JSON, JSON viewer feature is planned
