### ISSUE TITLE
QUESTION: How to save connections

### ISSUE THREAD

**Issue by Jianan-liu** [dbgate/dbgate#870]
**Version Information [might be relevant to your issue]**
Operating System:  win11
App Version [help -> about]:   Version: 5.3.4

**Screenshot [if appropriate]**:
![image](https://github.com/user-attachments/assets/c5062098-aacd-407e-97dd-acd9004702bf) how to save?

**Comment by janproch** [comment]
Try Connection context menu/View Details, Save. Save button is visible, when connection is not connected, if connected, click Disconnect at first
