### ISSUE TITLE
BUG: Can not run queries when mongodb in read-only mode

### ISSUE THREAD

**Issue by artem-zherdiev-ingio** [dbgate/dbgate#875]
**Describe the bug**
With read-only mode not possible to execute the query in MongoDB. For example, Postgres doesn't have such a problem. Also mentioned here https://github.com/dbgate/dbgate/issues/312#issuecomment-1550164734

**To Reproduce**
1. Make your MongoDB connection read-only
2. Create a new query
3. See that Execution is not active, or active when trying over MongoDB but "Connection without read-only session is read only" 

**Expected behavior**
MongoDB in read mode should allow to execute read queries

**Screenshots**
![image](https://github.com/user-attachments/assets/d88ab7c3-eafd-4374-bfff-aa8dc45c3f98)

**Version Information (please complete the following information):**
 - App Version 5.3.4
 - Install source Docker
 - Type - Web
 - Database engine: MongoDB

**Comment by janproch** [comment]
This is intentional, because MongoDB doesn't support readonly sessions, so executing scripts may change the database on connections marked readonly.

If you need to run scripts, the best method is to create DB user with readonly rights and use dbgate connection without write restrictioni

**Comment by artem-zherdiev-ingio** [comment]
Ok, got it, thanks
