### ISSUE TITLE
BUG: ssh key file authentication option missing

### ISSUE THREAD

**Issue by dinkonin** [dbgate/dbgate#876]
I've updated dbgate via npm (on linux) to 5.3.4. And noticed that ssh key file auth option is missing in SSH tunnel settings when adding new hosts.

Already configured connections work as expected.

Tried the latest beta-11 with podman, same result.

**Comment by janproch** [comment]
Key file auth is available only in electron app, not in docker or NPM (this behaviour was implemented 3 years ago)

There is file chooser for key file, which works only in electron app

I have changed that, now is key file auth available always, and on web platforms there is only textbox without file chooser

**Comment by dinkonin** [comment]
Tested the latest beta, all is good. Thanks for your work! Should I close this ?

**Comment by janproch** [comment]
Perfect, thanks for the test. I will close this after releasing this feature
