### ISSUE TITLE
BUG: Script with escaped backslash causes error

### ISSUE THREAD

**Issue by timataran** [dbgate/dbgate#880]
**Describe the bug**
If a script contains more than one query inserting a string with a backslash, it triggers an error. 
For example, a script with two INSERT statements:
```
INSERT INTO names (name) VALUES('one\\');
INSERT INTO names (name) VALUES('two\\');
```
Results in the following error:
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO names (name) VALUES('two\\')' at line 2
```

Running each line individually does not cause an error.

**To Reproduce**
1. Choose a table with a VARCHAR field.
2. Create a script with multiple INSERT statements, each inserting a string that contains an escaped backslash (\\) into the VARCHAR field.
3. Run the script. Observe that an error occurs.

**Expected behavior**
All queries in the script execute without error, and the rows are inserted successfully.

**Screenshots**
![dbgate-backslash-error](https://github.com/user-attachments/assets/3697a542-8fe0-4abb-826c-ecddab4193bb)

**Version Information (please complete the following information):**
 - OS: [Ubuntu 24.04]
 - App Version [5.4.3]
 - Install source [SNAP / Web demo]
 - Type - Web/Application
 - Database engine: [MySQL]

**Comment by janproch** [comment]
Good catch, thanks
