### ISSUE TITLE
BUG: Upgrade from 5.3.4 to 5.4.0 DBGate App won't start [ Loading plugins ]

### ISSUE THREAD

**Issue by WMCerberus** [dbgate/dbgate#881]
**Describe the bug**
The application [v 5.4.0] won't start on Ubuntu 24.04, due to the below plugins not being able to load.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install on version 5.3.4: dbgate-plugin-postgres-jumpserver 1.0.2 / dbgate-plugin-sysbase 0.3.0
2. Update version to 5.4.0 using dpkg -i [dbgate-5.4.0-linux_amd64.deb](https://github.com/dbgate/dbgate/releases/download/v5.4.0/dbgate-5.4.0-linux_amd64.deb)
3. App won't start, will be stale at loading [dbgate-plugin-postgres-jumpserver /  dbgate-plugin-sysbase]

**Expected behaviour**
Application should start normally

**Screenshots**
![Screenshot_2024-09-04_10-42_58](https://github.com/user-attachments/assets/12691124-fb84-45f1-b7f7-92661407a1bf)

**Version Information (please complete the following information):**
 - OS: Ubuntu 24.04
 - App Version: 5.4.0
 - Install source: .deb
 - Type - Application
 - Database engine: MySQL/PostgreSQL

**Workaround**

1. Installed back version 5.3.4
2. Removed/uninstalled those 2 plugins
3. Reinstalled version 5.4.0

**Result**

Application v. 5.4.0 started.

Can this be reviewed please and if so maybe remove those 2 plugins from plugins list ?

Thank you in advance.

**Comment by janproch** [comment]
Fixed in 5.4.1. Older plugins will work also in new version
