### ISSUE TITLE
BUG: dbgate version 5.2.8 broke SSL with MongoDB

### ISSUE THREAD

**Issue by paulbehrisch** [dbgate/dbgate#885]
**Describe the bug**
Using any Dbgate docker image between version `5.2.8` and the latest version breaks MongoDB SSL connections, causing the below error when attempting to connect to the database. 
"The tlsInsecure option cannot be used with the tlsAllowInvalidCertificatesOption"
<img width="373" alt="Screenshot 2024-09-06 at 19 16 23" src="https://github.com/user-attachments/assets/2d5d992e-2450-429d-b63e-7f928d7979f2">

A [comparision](https://github.com/dbgate/dbgate/compare/v5.2.7...v5.2.8#diff-89d832f0f4d028875f17c96d0a0c040d4c88e972ea0c3085034b67dcdc7577c9R31) between 5.2.7 and 5.2.8 shows that the `mongodb` and `mongodb-client-encryption` packages were [upgraded](https://github.com/dbgate/dbgate/commit/6f4c0edb46133fb960a469ad08ea44ed297bef28).

The [error message originates from the Mongo driver](https://github.com/mongodb/node-mongodb-native/blob/65e0e15cd59809558fb2570ef4d7fe6d6d376d5d/src/connection_string.ts#L159-L166) itself and it appears that Dbgate is passing in the wrong [options](https://github.com/dbgate/dbgate/blob/5daf64360c8d21552f38ab239215f8f8f81faeca/plugins/dbgate-plugin-mongo/src/backend/driver.js#L76-L77). 

Dbgate should call the driver with either `tlsInsecure` or `tlsAllowInvalidCertificates`.

I tried getting a shell in the docker container and edited the minified source code in `/home/dbgate-docker/plugins/dbgate-plugin-mongo/dist` and after removing the `tlsAllowInvalidCertificates` line from the driver config, I was able to establish a database connection.
<img width="1006" alt="Screenshot 2024-09-06 at 18 53 37" src="https://github.com/user-attachments/assets/981b6000-1b9b-42e2-98c5-9d2608612a15">

**To Reproduce**
Pull docker image version 5.2.8 or higher and set these env vars:

```
    - name: CONNECTIONS
      value: STAGING
    - name: LABEL_STAGING
      value: STAGING
    - name: ENGINE_STAGING
      value: mongo@dbgate-plugin-mongo
    - name: USE_SSL_STAGING
      value: "1"
    - name: SSL_REJECT_UNAUTHORIZED_STAGING
      value: "0"
```

**Expected behavior**
The database should open.

**Screenshots**

**Version Information (please complete the following information):**
- Kubernetes +  image: dbgate/dbgate:5.2.8 or higher

**Comment by janproch** [comment]
Fixed in 5.4.3
