### ISSUE TITLE
FEAT: Force Check Update and Force Update

### ISSUE THREAD

**Issue by datgausaigon** [dbgate/dbgate#886]
Hi,

I can't find a way to update the software.

The software updates itself, sometimes I have to turn it on and off and wait for it to update without knowing if it is updating or not. I want to check for updates and update them immediately like other software when entering its About/App section/menu (Chrome, Firefox,...).

Force Check and Update of KeKa app in macOS:
![332059819-2e7d5031-e989-4b14-87b4-a4ca09156fdf](https://github.com/user-attachments/assets/c5e5c93f-0a03-4d8c-8ae7-f7c302f08940)

Force Check and Update of drawio app in macOS:
![Screenshot 2024-09-07 at 16 10 47](https://github.com/user-attachments/assets/ba319f45-ffd4-4f9d-b3ad-3aa6b71c6afd)

Can you add this feature? 
Thanks
🐻

**Comment by janproch** [comment]
Added menu Help/Check for updates

**Comment by datgausaigon** [comment]
@janproch 
Thanks for update.
🐻
