### ISSUE TITLE
BUG: Operator does not exist: jsonb ~~* unknown, while using multi column filter

### ISSUE THREAD

**Issue by vinod27agarwal** [dbgate/dbgate#889]
**Describe the bug**
If you have a column, with json values (JSON) and using 

**To Reproduce**
1. Download DbGate for mac (Version: 5.4.4)
2. Create table column with json type (as shown in screenshot) 
3. Try multi column filter

**Expected behavior**
Multicolumn filter should work

**Screenshots**
<img width="346" alt="image" src="https://github.com/user-attachments/assets/5a697ed8-cdda-4de1-99a5-85f6b6985bb7">

**Comment by janproch** [comment]
Which database engine are you using?

**Comment by vinod27agarwal** [comment]
I am using postgres

**Comment by vinod27agarwal** [comment]
I can see a similar issue as 
https://github.com/dbgate/dbgate/issues/855
