### ISSUE TITLE
BUG: OIDC authentication not working anymore

### ISSUE THREAD

**Issue by tedstriker** [dbgate/dbgate#891]
**Describe the bug**
Haven't used DbGate for a while, but updated it to the recent version every now and then. Currently running 5.4.4
Trying to log in using OIDC doesn't work anymore. Maybe something in Authentik (auth provider) has been misconfigured, but nothing I can point my finger at.
Any hint is appreciated

**To Reproduce**
1. Go to your installed instance of dbgate in the browser
2. Try to log in using your OIDC provider
3. See error
<img width="547" alt="image" src="https://github.com/user-attachments/assets/5dc3e09c-cba9-4f3b-a3d3-2a6231737598">

from the log:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:405:5)
    at ServerResponse.setHeader (node:_http_outgoing:648:11)
    at S.set.S.header (/home/dbgate-docker/bundle.js:2:261527)
    at S.send (/home/dbgate-docker/bundle.js:2:257161)
    at h (/home/dbgate-docker/bundle.js:2:1669023)
    at authMiddleware (/home/dbgate-docker/bundle.js:2:1670078)
    at o.handle_request (/home/dbgate-docker/bundle.js:2:268782)
    at /home/dbgate-docker/bundle.js:2:266151
    at /home/dbgate-docker/bundle.js:2:266173
    at m.process_params (/home/dbgate-docker/bundle.js:2:266665)
```

**Expected behavior**
I expected to be logged in as the authenticated user.

**Screenshots**

**Version Information (please complete the following information):**
 - OS: Debian
 - App Version: 5.4.4
 - Install source: Docker
 - Type - Web/Application
 - Database engine: not relevant for this

**Comment by janproch** [comment]
Du you have properly configured allowed redirect_uri in authentik?

**Comment by tedstriker** [comment]
I haven't changed it after I got it working months ago, so I guess yes, but it seems like something changed.
What I've found in the [docs](https://dbgate.org/docs/web-app-config.html) (text above the last screenshot) is, that it's the same URL as when you open it. No sub path or anything.
So it's `https://dbgate.mydomain.example/`
Was a sub path added to it recently?

**Comment by pmpetit** [comment]
i have the same problem...
fail for > 5.4.0
![image](https://github.com/user-attachments/assets/b1f85941-19d5-4dc6-a7f9-73fe10542c5b)

ok for version 5.3.4

**Comment by tedstriker** [comment]
Can confirm. Reverted back to 5.3.4 and authentication is working again.

**Comment by janproch** [comment]
You are right, this functionality was broken, it is fixed now. Redirect URL is the same, also it os now written to console before redirecting

**Comment by tedstriker** [comment]
Thank you
