### ISSUE TITLE
FEAT: Quick export when dealing with multiple results from queries

### ISSUE THREAD

**Issue by jesbanales** [dbgate/dbgate#892]
I'm not entirely certain, but I believe that this was implemented before. DBGate updated automatically today and now I have to go through the export page instead of before when I could simply right click on my results and hover over export before choosing a file type. I believe this is only the case whenever my queries output multiple sets of results. I tested with a query that only outputs one set of results and the quick export button was there as well as the export option when right clicking on data that allowed me to select the file type I wanted.

I would like to once again be able to right click on results and quickly export from queries that output multiple result sets.

I understand that I can use the regular export page as it is now, however this was already a part of my workflow before and I was well adjusted to it. Thanks!

**Comment by janproch** [comment]
Export from bottom toolbar is not possible, when there are multiple result sets, it is feature

But you can choose Quick export from right-click-on-table menu. There is one bugfix, quick export was not accessible from context men

It is in l;atest BETA 5.4.5-beta.11 https://github.com/dbgate/dbgate/releases/tag/v5.4.5-beta.11
