### ISSUE TITLE
err: import pg dump sql file error

### ISSUE THREAD

**Issue by banbushi** [dbgate/dbgate#893]
**Details:**

**import error**
when  import a sql，it report err !

![import](https://github.com/user-attachments/assets/4aed5c6f-e866-4a84-afa9-9827bc29b495)

![error](https://github.com/user-attachments/assets/bc919922-2890-4b5e-9fb1-f128f806a149)

**Version**
running on windows 
![pg-version](https://github.com/user-attachments/assets/9bfa4e92-4577-4eeb-a398-16ca8af53594)

same as 
#702

**Comment by janproch** [comment]
Solution of this problem is a bit more complicated, only error reporting is fixed now. The reason of this error is that pg_dump uses command COPY FROM stdin; , which is now not supported by DbGate.
