### ISSUE TITLE
BUG: Unable to load tables from postgresql DB

### ISSUE THREAD

**Issue by Korosys** [dbgate/dbgate#894]
**Describe the bug**
One DB with many schema on postgresql, have tried dbgate on windows, linux, and docker, all have the same problem and cannot load. Sometimes gets to "loading tables" and then "loading primary keys" if left open but this takes an excessive amount of time.

**To Reproduce**
1. open a postgresql connection with a large db
2. Click on the db to load schemas
3. hangs on loading model or loading tables

**Expected behavior**
dbgate displays the schema normally

**Screenshots**
![image](https://github.com/user-attachments/assets/a1ba5adb-be26-4beb-b21c-2f0dcbba09b1)

**Version Information (please complete the following information):**
 - OS: win/linux/docker
 - App Version [5.4.4]
 - Install source [installer/Docker]
 - Type - Application
 - Database engine: [PostgreSQL]

**Comment by janproch** [comment]
Could you try the newest BETA?

There is new option on screen below, then only one schema is loaded

This feature must be tested for a while, it is quite a bit change, but basically it should work now

![image](https://github.com/user-attachments/assets/726ed0ac-f4a7-4f93-821b-78b4bfb68708)

**Comment by janproch** [comment]
So are you using docker versipn configured with environment variables?

**Comment by Korosys** [comment]
> Could you try the newest BETA?
> 
> There is new option on screen below, then only one schema is loaded
> 
> This feature must be tested for a while, it is quite a bit change, but basically it should work now
> 
Hey guys, i tried the beta 8 5.4.5 appimage linux x86_64 and enabled the option for use schemas separately but i am having two issues

clicking on the DB from my original post now does nothing, as if i had not clicked on it. Other DBs on the same connection do not have this issue and function normally.

Second, clicking on any DB other than that one functions normally as i said, but if i then click disconnect from the server, dbgate crashes with this message in the console
![image](https://github.com/user-attachments/assets/37943c20-3367-4c10-9736-52ba33fa725b)

if i disable the new option, this behavior disappears

**Comment by Korosys** [comment]
I created a gist with the logs https://gist.github.com/janproch/4147a26bc8f4f8a56783605524b9859a
i am not sure if the crash shows up in these logs, but it was showing something about db connection not alive

**Comment by Korosys** [comment]
> @Korosys thank you for the reports. The crash is fixed now. After clicking database in separate schemas mode, list of schemas is loaded, I added some logging, error reports and progress indicator for this action. Probably there is some problem with this query
> 
> Could you please also try the following query in problematic database (dbgate now uses this query):
> 
> ```sql
> select oid as "object_id", nspname as "schema_name" from pg_catalog.pg_namespace
> ```
> 
> Alternatively, this query:
> 
> ```sql
> SELECT schema_name FROM information_schema.schemata;
> ```
> 
> @mehta-rohan If you are using docker, please use newest BETA image and set USE_SEPARATE_SCHEMAS_xxx connection variable (https://dbgate.org/docs/env-variables.html)
> 
> > USE_SEPARATE_SCHEMAS_[connection id] - set value 1 or true for load schemas separately. Use this if you have large schemas.

The crash issue does look like it was fixed in the most recent beta as of writing.

both queries execute and produce a list of the schema in the database, but when clicking on the DB now, instead of nothing at all happening, it shows the loading spinner next to the db name but never gets past that

![image](https://github.com/user-attachments/assets/e288fac5-a2ea-4fb8-b0ec-95c51fc1f0d7)

**Comment by mehta-rohan** [comment]
> @mehta-rohan If you are using docker, please use newest BETA image and set USE_SEPARATE_SCHEMAS_xxx connection variable (https://dbgate.org/docs/env-variables.html)
> 
> > USE_SEPARATE_SCHEMAS_[connection id] - set value 1 or true for load schemas separately. Use this if you have large schemas.
@Korosys 
I have made changes accordingly 

`sudo docker run -d -it --name dbgate-instance --restart always -p 3000:3000 
-e CONNECTIONS='postgres' -e LABEL_postgres='Vizio Beta' -e SERVER_postgres='xx'
 -e USER_postgres='vizio_pg_beta' -e PASSWORD_postgres='?Adarsh@2003?' -e ENGINE_postgres='postgres@dbgate-plugin-postgres' 
-e USE_SEPARATE_SCHEMAS_postgres='1' dbgate/dbgate:beta`

No luck still not able to see the tables 

Error in the browser console when I click the refresh button on the website

`{
Unhandler error, checking whether crashed 
unhandledrejection { target: Window, isTrusted: true, promise: Promise { "rejected" }, reason: SyntaxError, srcElement: Window, currentTarget: Window, eventPhase: 2, bubbles: false, cancelable: true, returnValue: true, … }
ErrorHandler.svelte:1:17

}`

**Comment by janproch** [comment]
@Korosys @mehta-rohan 

Could you please upload GIST with logs after you try to open problemmatic database?
I have improved logging, please use the newest BETA https://github.com/dbgate/dbgate/releases/tag/v5.4.5-beta.13
Uploading error gist is possible also from web app

**Comment by Korosys** [comment]
@janproch Here is the gist, i am running on windows at the moment. https://gist.github.com/janproch/c58c8e499da99b857b1c35a3600f01e8

**Comment by janproch** [comment]
@Korosys thanks. It seems that loading schemas hangs up.

Could you please try the newest BETA https://github.com/dbgate/dbgate/releases/tag/v5.4.5-beta.14 ?

If it doesn't help, could you please test the following queries in problematic database?
```sql
SHOW SEARCH_PATH;
```

```sql
SELECT current_schema
```

I the newest BETA, I replaced the first one, which could bring problems, with the second one

**Comment by janproch** [comment]
I am closing it for now, as separate-schema mode is part of current release, please reopen this, if it still will make problems

**Comment by Korosys** [comment]
@janproch Hello, after updating to the latest release the problem still persists. running the queries returns the following result:
![image](https://github.com/user-attachments/assets/d29cbb7f-84c4-4f54-aee9-9afa2c9ab9bd)
![image](https://github.com/user-attachments/assets/ced6a167-70e0-4a9e-8ef3-e769ad9ca509)

i have uploaded another gist for you to look at, let me know if you need anything else!
https://gist.github.com/janproch/8dfa190eb65e9c631580813bdcb548e4

**Comment by janproch** [comment]
Thanks for the feedback. I believe I see the problem now, I will prepare BETA with fix tomorrow

**Comment by janproch** [comment]
The problem reported in the last comment is fixed in the newest BETA: https://github.com/dbgate/dbgate/releases/tag/v5.5.3-beta.1

I have also added some new log messages, in case if it still will not work correctly
