### ISSUE TITLE
Shortctus bug: Action with mutiple shortcuts using "CtrlOrCommand" only is triggered by the first shortcut

### ISSUE THREAD

**Issue by erickcomp** [dbgate/dbgate#898]
### Describe the bug
I'm migrating from another tool and I'd like to keep my muscle memory, so I tried to setup 2 shortcuts: one for execute selection and other for executing the whole script, but it did not work.
The shortcuts are:

```CtrlOrCommand+R | CtrlOrCommand+Shift+R```
or
```CtrlOrCommand+Shift+R | CtrlOrCommand+R```

Only the fisrt shortcut is used. If I use the shortcut to another action, it works (for test puporses, I used one of them to trigger formatting and I realized they both work if assigned to different actions).

### To Reproduce
Set the "CtrlOrCommand+R | CtrlOrCommand+Shift+R" shortcuts to the ```query.execute``` action 

### Expected behavior
Both shortcuts trigger the ```query.execute``` action

### Version Information:

    OS             : Zorin OS 17 (Ubuntu 22.04)
    App Version    : 5.4.4
    Install source : AppImage
    Type           : Application
    Database engine: MySQL

### Additional info

While checking the code, I realized that the tool is smart and get the selection when executing,
so I can use the same shortcut to execute the whole script or the selection, but the bug with these 2 shortcuts remains.

I decided to find the reason of the bug. In fact, I tracked it down already. :)

The problem is on the "packages/web/src/commands/CommandListener.svelte" or on the "packages/web/src/utility/common.ts" file. It kinda depends on how you look at it.
On the function "resolveKeyText", you use String.replace function to exchange "CtrlOrCommand+" with "Ctrl+", but String.replace WITHOUT REGEX only replaces the first occurence of the needle in the haystack.
The possible solutions here could be using regex or applying the resolveKeyText after splitting the shortcuts string by vertical bar, on the function "handleCommandKeyDown" of the "CommandListener.svelte" file:

#### Solution 1:

Change "resolveKeyText" function

from:

```typescript
export function resolveKeyText(keyText: string): string {
  if (isMac()) {
    return keyText.replace('CtrlOrCommand+', 'Command+');
  }
  return keyText.replace('CtrlOrCommand+', 'Ctrl+');
}
```

to:
```typescript
export function resolveKeyText(keyText: string): string {
  if (isMac()) {
    return keyText.replaceAll('CtrlOrCommand+', 'Command+');
  }
  return keyText.replaceAll('CtrlOrCommand+', 'Ctrl+');
}
```

#### Solution 2:

Change the piece of code that filters the matching commands on the "handleCommandKeyDown" function

from:

```typescript
let commandsFiltered: any = Object.values(commandsValue).filter(
      (x: any) =>
        x.keyText &&
        resolveKeyText(x.keyText)
          .toLowerCase()
          .split('|')
          .map(x => x.trim())
          .includes(keyText.toLowerCase()) &&
        (x.disableHandleKeyText == null ||
          !resolveKeyText(x.disableHandleKeyText)
            .toLowerCase()
            .split('|')
            .map(x => x.trim())
            .includes(keyText.toLowerCase()))
    );
```

to:

```typescript
let commandsFiltered: any = Object.values(commandsValue).filter(
      (x: any) =>
        x.keyText &&
        x.keyText
          .toLowerCase()
          .split('|')
          .map(x => resolveKeyText(x.trim()))
          .includes(keyText.toLowerCase()) &&
        (x.disableHandleKeyText == null ||
          !x.disableHandleKeyText
            .toLowerCase()
            .split('|')
            .map(x => resolveKeyText(x.trim()))
            .includes(keyText.toLowerCase()))
    );
```

I won't submit a PR to resolve this because I'm not a Svelte/JS/TS dev and I really don't know how to start writing tests for this kind of app.

Since I found the problem, the current workaround is to set the second shortcut to ```Ctrl+``` instead of ```CtrlOrCommand+```

Anyway, thanks for this amazing app! 🙏

**Comment by janproch** [comment]
Thank you for great analysis! It is fixed now

Currectly there are no frontend tests

**Comment by erickcomp** [comment]
Thank you for your work!
