### ISSUE TITLE
hello need your help 

### ISSUE THREAD

**Issue by mamtavtayade** [dbgate/dbgate#899]
![Screenshot 1946-07-03 at 12 53 41 PM](https://github.com/user-attachments/assets/7ac519dd-9c5e-4804-9f3e-6d4532737aa4)
![Screenshot 1946-07-03 at 12 53 51 PM](https://github.com/user-attachments/assets/b1336402-1997-457b-a3cc-af94565bd13c)
this 
![Uploading Screenshot 1946-07-03 at 12.53.57 PM.png…](
![Screenshot 1946-07-03 at 12 54 05 PM](https://github.com/user-attachments/assets/76aae42f-dc82-4e12-b21b-7139528d66ec)

error issue kindly resolved this issue i want to preview and shart working on what i created plz its urgent

**Comment by mamtavtayade** [comment]
![Uploading Screenshot 1946-07-03 at 12.57.07 PM.png…]()

**Comment by janproch** [comment]
Closing, this is not related to dbgate
