### ISSUE TITLE
BUG: Can't view JSON fields in PostgreSQL

### ISSUE THREAD

**Issue by grassick** [dbgate/dbgate#90]
**Describe the bug**
In a query, JSON fields show up as "(JSON)". I can't copy, view, or do anything with them

**To Reproduce**
1. Go to select * from table_with_jsonb field
2. Attempt to view field with JSON

**Expected behavior**
I expected a summary of the JSON or the complete text, or something that I could expand to view

**Screenshots**
![image](https://user-images.githubusercontent.com/1238335/115749492-22743e80-a365-11eb-94a4-cc449a3fa27b.png)

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version 4.1.9
 - Install source AppImpage
 - Type - Application
 - Database engine: PostgreSQL

**Additional context**
It also randomly crashed while in the background while writing this bug report.

**Comment by janproch** [comment]
Thanks for report
Native JSON field could be already viewed with cell data view 

I have added handing for native JSON field in following way:
- Copy to clipboard
- Tooltip on (JSON) in datagrid will show JSON object
- Cell data view - view as text
- Editing JSON value in datagrid will work

![image](https://user-images.githubusercontent.com/2543891/115955680-50d65300-a4f8-11eb-9b3a-0783e6144b42.png)

**Comment by janproch** [comment]
About crashes, could you be please more exact? What error message deos it show? Is there any error in console?

**Comment by janproch** [comment]
fixed in version 4.1.10
