### ISSUE TITLE
Update from 5.4.4 to 5.5.1

### ISSUE THREAD

**Issue by WMCerberus** [dbgate/dbgate#900]
**Describe the bug**
Unable to connect to PostgreSQL DB

**To Reproduce**
1. Open DBGate Application

**Expected behavior**
Should be able to connect to PostgreSQL DB's

**Screenshots**
![image](https://github.com/user-attachments/assets/16ebbf96-b9eb-4c96-9beb-67cdb67833c6)

**Version Information (please complete the following information):**
 - OS: Mac Os [15.0]
 - App Version: 5.5.1
 - Install source : Auto update from DBGate App
 - Type - Application
 - Database engine: PostgreSQL
 
 Thank you in advacne.

**Comment by janproch** [comment]
Could you please upload GiST for this situation? Menu Tools/Upload error to gist

It seems like you are using old version of postgre plugin

**Comment by janproch** [comment]
One question, are you using a readonly connection?

**Comment by bdoucette** [comment]
I have the same issue with a MySQL readonly connection.
However, the same connection without readonly works so the issues seems to be with `readonly`

**Comment by WMCerberus** [comment]
Yes Read Only all of them.

**Comment by janproch** [comment]
Thanks for reporting, I have fixed it now, this critical fix will be ready after pipeline https://github.com/dbgate/dbgate/actions/runs/11029615623 will finish

**Comment by WMCerberus** [comment]
Thank you very much, for the quick fix.
