### ISSUE TITLE
BUG: DBGate Helper still running with high CPU when the app is already terminated

### ISSUE THREAD

**Issue by kussumma** [dbgate/dbgate#915]
**Describe the bug**
Dear community, thanks for the awesome app, I don't really sure that it's a bug or not, but I found DBGate helper still running with high CPU when the app is already closed. Please check the video below

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
https://github.com/user-attachments/assets/380d8163-bf5d-4040-bf98-6a5c553f3f4f

**Version Information (please complete the following information):**
 - OS: MAC (Intel)
 - App Version: 5.5.4
 - Install source: DMG
 - Type: Application
 - Database engine: I have used multiple database engine (mysql, postgresql, mongodb)

**Comment by janproch** [comment]
What do you mean exactly with "App is closed"? Did you terminate quit the app (Cmd+Q) or close main window?

**Comment by kussumma** [comment]
> What do you mean exactly with "App is closed"? Did you terminate quit the app (Cmd+Q) or close main window?

Hi Jan, sorry for the confusion, I mean the app is terminated (Cmd + Q)

**Comment by ghosh9691** [comment]
Same here. Multiple instances of the DbGate Helper processes running with high cpu load well after the app is terminated via CMD+Q

**Comment by janproch** [comment]
This should be fixed in the newest BETA
