### ISSUE TITLE
BUG: dbgate background process consumes 100% CPU after UI closed

### ISSUE THREAD

**Issue by Pavel-Husakouski** [dbgate/dbgate#917]
**Describe the bug**
Some processes of dbgate are alive after UI closing and consume 100% of cpu
Example:
/tmp/.mount_dbgateN1U9Zo/resources/app.asar/packages/api/dist/bundle.js --is-forked-api --start-process sshForwardProcess  --native-modules /tmp/.mount_dbgateN1U9Zo/resources/app.asar/src/nativeModules

**To Reproduce**
1. Start application
2. Create a connection to some remote db
3. save connection
4. restart application
5. connect to a db
6. close application when connection is made or connection is in progress
7. repeat steps 4,5,6 several times

**Expected behavior**
No dbgate entries in the ps -A

**Screenshots**
![image](https://github.com/user-attachments/assets/7685192a-8e99-46ca-bb94-3efd047b947e)

**Version Information (please complete the following information):**
 - OS: Manjaro Linux
 - App Version 5.5.5
 - Install source AppImage from official site
 - Type - AppImage
 - Database engine: RDS for postgres

**Comment by Kwonunn** [comment]
can confirm, i'm getting the same issue. sometimes the processes exit after a while by themselves, but sometimes they stick around seemingly indefinitely.

i'm running the flatpak on Fedora Workstation 40

**Comment by luanbt21** [comment]
I'm having the same issue on macOS. Already quit DBGate, but after logging in from sleep, 3 `DbGate Helper` processes were taking up a lot of my CPU
