### ISSUE TITLE
BUG: Schema selection in Export does not provide all schemas

### ISSUE THREAD

**Issue by vavramovski** [dbgate/dbgate#924]
**Describe the bug**
The dropdown in the **Export** db menu does not show all the schemas for a given database.
It only shows default schemas. **Not selecting the right schema is blocking me from exporting tables**.

**To Reproduce**
1. Go to Connections Side Bar
2. Right Click on any Database
3. Go to Export
4. DB Export form will show, click on the Schemas form field

**Expected behavior**
All Schemas should show, including user defined.

**Screenshots**
<img width="858" alt="image" src="https://github.com/user-attachments/assets/58780d7e-5c29-41bc-a452-0856a5fd5b4d">

**Version Information (please complete the following information):**
 - OS: Ubuntu
 - App Version 5.5.6
 - Install source Docker
 - Type - Web
 - Database engine: PostgreSQL

**Comment by janproch** [comment]
It works for me...

Could you please upload GITST with error logs? (menu Tools/upload error to Gitst) ?

**Comment by apocrx** [comment]
The export tool seems to load schemas from different database or default database.

**Comment by janproch** [comment]
The bug you described should be now solved - in the newest BETA
