### ISSUE TITLE
BUG: Typecast ::date is treated as a parameter

### ISSUE THREAD

**Issue by sancho2934489** [dbgate/dbgate#925]
Hello,

I have encountered an issue related to date type casting in ClickHouse. In other SQL databases, I am accustomed to using `::date` for type casting, but it seems that ClickHouse does not support this syntax and interprets it as a parameter instead.

I would like to suggest improving the documentation or providing a more intuitive way to handle date type casting, similar to other SQL databases. Currently, I am using functions like `toDate` or `parseDateTimeBestEffort` to work with dates, but it would be helpful to have a more straightforward method.

Thank you for your attention to this matter.

**Comment by janproch** [comment]
I changed default behaviour, now when you want to use parameters, you have to choose parameter style at first
