### ISSUE TITLE
FEAT: Support for Clicking on Table with SQL Server 2008

### ISSUE THREAD

**Issue by ConradSollitt** [dbgate/dbgate#93]
**Is your feature request related to a problem? Please describe.**
First off great job on DbGate! I forward to trying and using it with SQLite once supported as well. And based on my initial testing I expect DbGate to be my main SQLite query tool in the future. :)

I tested it at work on a Windows Machine and found that if used with older versions of SQL Server (I'm on 2008 R2) and you click on a table it shows an error because SQL Server prior to 2012 does not support `OFFSET`.

**Describe the solution you'd like**
Without looking at the code in more detail I would think an alternative would be to simply return the top 100 rows in a new query tab if clicking on table. The user can then modify the query if the would like to see different records.

Example:
```sql
SELECT TOP 100 *
FROM {table}
```

**Describe alternatives you've considered**
After a quick Google and some testing I think implementing a `OFFSET` alternative would be too complex to handle reliably for all cases and I wouldn't expect good performance.

https://stackoverflow.com/questions/3219409/sql-server-offset-equivalent

**Additional context**
Here is a screen shot of what happens. If a change is made I'm happy to help test.

![image](https://user-images.githubusercontent.com/57777521/115801071-bc051580-a390-11eb-8ff4-d84f70f67571.png)

**Comment by janproch** [comment]
Thanks for analysing. ROW_NUMBER should be quite effective. This must depend on SQL Server version, so that row_number variant is not used on SQL 2012 and newer

**Comment by janproch** [comment]
fixed in version 4.1.10

**Comment by ConradSollitt** [comment]
Wow great job on making this change so fast @janproch ! I looked at your commit and see that it was a fairly large amount of code you had wrote for this feature so thanks for adding it so fast!

I just tested the new build and it works great. I've tried a variety of tables including large tables from a legacy system that had no primary key and in all cases it works without issue.
