### ISSUE TITLE
BUG: The top part of filter option UI for datetime field are clipped out

### ISSUE THREAD

**Issue by mgoku** [dbgate/dbgate#94]
**Describe the bug**
When trying to choose filter option from datetime field, the top part of the option UI are clipped out

**To Reproduce**
1. Open a table that have datetime field, eg: last_update
2. Click on filter icon on the last_update field
3. The top part of the option UI are clipped out

**Expected behavior**
The UI should not be clipped out.

**Screenshots**
![2021-04-23_10-06](https://user-images.githubusercontent.com/1448244/115812950-89a0fa00-a41c-11eb-8c33-1400339a77dd.png)

**Version Information:**
 - OS: Linux (openSUSE Tumbleweed - KDE)
 - App Version 4.1.9
 - Install source AppImage, Web Demo
 - Database engine: MySQL

**Additional context**
Running KDE on FHD monitor with 1.5 UI scaling

**Comment by janproch** [comment]
fixed in version 4.1.10
