### ISSUE TITLE
FEAT:  add oracle support?

### ISSUE THREAD

**Issue by mei-rune** [dbgate/dbgate#95]
add oracle support?

**Comment by janproch** [comment]
I will add it to plan.

First engine to be added is SQLite, maybe than Oracle

**Comment by ConradSollitt** [comment]
If I have time in the near future I'll see if I can add Oracle Support or a working starting point. I can't promise this but hopefully I'll have time for this in a few weeks or a month.

**Comment by janproch** [comment]
Thanks very much for your offer! I will very appreciate help with Oracle driver. I think I will have other priorities in near future, also I have very small experiences with Oracle. 

There is yeoman generator for driver plugins for DbGate ( https://github.com/dbgate/generator-dbgate ), it is not up to date, but probably it is easier to start with this than copying and modifying existing driver.

**Comment by ConradSollitt** [comment]
Thanks for the tips! That will make it easier to get started. Currently I'm not working with Oracle but have worked with it a lot in the past and have access to a Oracle instance at work that is no longer being used.

**Comment by janproch** [comment]
Oracle supports added in version 5.2.0
