### ISSUE TITLE
DB/Table Open Data on Click issue

### ISSUE THREAD

**Issue by WMCerberus** [dbgate/dbgate#959]
**Describe the bug**
Open/Connect to DB with one click, not working any more with the latest release

**To Reproduce**
Steps to reproduce the behaviour:

1. Click/Select DB Server - won't connect to DB Server, instead will open the Connections settings/View Details, asking to connect.
2. Double-click on DB - will connect to DB Server but won't open the default DB, therefore we need to select the DB even if we have the default DB already set in Connection settings, DB selection the same behaviour on Select/click it won't open the DB so we need to double-click on DB to be able to see the TAB with DB Server/DB name.
3. The same behaviour happens even if we set in settings "Default Actions" - Use last Used Actions, or we chose to Open Data on "select".
4. Right now I need to use 2x double-click to open a connection to DB Server/DB and close a "connections details" TAB which will always pop up upon DB Server selection using 1 click/double-click.
5. Select DB Server - Connection Details tab will open, the connection to DB server will not be done, ---> closing the TAB [connections details] ---> will connect to DB server, strange behaviour.

**Expected behavior**
Previous version worked fine:
1. Select DB Server - which automatically will connect and expand/show available DB's
2. With 2 clicks, I can connect to DB server and select desired DB.
3. No unwanted TAB will pop up [connection details]

**Screenshots**

1. Default Actions:
![image](https://github.com/user-attachments/assets/38d7fb79-5d4b-4bee-b01f-50e561cc0759)

2.Select DB Server:
![image](https://github.com/user-attachments/assets/57edb57a-312f-43c6-b32d-f7ac43537947)

3. Double Click will connect to DB Server but won't select the default DB / Connection Details TAB will still pop up:
![image](https://github.com/user-attachments/assets/40866f89-2e00-4f29-b3c5-1777c9f5ef30)

**Version Information (please complete the following information):**
 - OS: MacOS Sequoia 15.1.1
 - App Version: 6.0.0 
 - Install source: Installer/Upgrade through DBGate
 - Type - Application
 - Database engine: PostgreSQL - read only

**Comment by janproch** [comment]
OK, thanks for your suggestion

It was an intention. The reason, why double click is needed, is to keep consistency between and mouse keyboard navigation.

But there will be definitely improvement in next follow-up version, so any ideas, how to improve new UX, is welcome
Allowing single-click opening connection and choosing database will be surely possible, only now I am not sure, whether it will be the default setting.

Ignoring the default database setting in this action is definitely an UX bug.

**Comment by WMCerberus** [comment]
Thank you very much @janproch, if I recall there were options in previous versions, but I may be wrong where you could choose "One Click to Open" or "Double Click".

If that can be added back will kinda let the user choose the wanted behaviour when it comes to DB Server/DB

Also in previous versions upon "One Click" was connecting to DB server and also opening the DB "tree"  and allowed to select  another DB  instead the default one.

This behaviour is not present in current version, so you need to go and click on "+" to expand it.
