### ISSUE TITLE
Only Single Table Tab in Version 6.0.0

### ISSUE THREAD

**Issue by kwsim539** [dbgate/dbgate#963]
Since updating to version 6.0.0, I can only open one table tab at a time, whereas the previous version allowed me to open multiple table tabs. Please bring this back or add this as an option in Settings.

**Comment by WMCerberus** [comment]
Hi, I do face this issue also where if I open a tab which contains a "function" and after that if I open a new DB it will overwrite the current "function" tab with the DB tab.

To mention is not happening if I open a DB tab -> Function tab -> another DB tab, it happens only if the first tab oppened is the "function tab"

I am using macOS arm64 [DBGate 6.0.1.beta.3] /  same behaviour for macOS Universal [DBGate 6.0.0] 

This behaviour is present in version 6.0.0 and 6.0.1.beta.3

**Comment by janproch** [comment]
Version 6.0 brings tab preview mode, so only one tab in preview mode could be opened. Tab in preview mode is marked as italics.

You could switch tab from preview mode to normal mode by double clicking to tab header. Also you could open tabs in normal mode by clicking (new window) icon in context menu, by mouse middle-click or by double clicking on table.

Tab preview mode prevents to many tabs be opened, if you want only to check something and then work with different table/procedure/function. 

Pleae let me know if it makes sense for you. VS Code users are familiar with tab preview mode (https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode ),but it is possible that it could be confusing for other users. There was issue requesting this - https://github.com/dbgate/dbgate/issues/767 . 
 Maybe I will consider to add setting to disable tab preview mode

**Comment by janproch** [comment]
In new version, there is new option to disable "Tab preview mode", Settings/Behaviour

**Comment by kwsim539** [comment]
> Version 6.0 brings tab preview mode, so only one tab in preview mode could be opened. Tab in preview mode is marked as italics.
> 
> You could switch tab from preview mode to normal mode by double clicking to tab header. Also you could open tabs in normal mode by clicking (new window) icon in context menu, by mouse middle-click or by double clicking on table.
> 
> Tab preview mode prevents to many tabs be opened, if you want only to check something and then work with different table/procedure/function.
> 
> Pleae let me know if it makes sense for you. VS Code users are familiar with tab preview mode (https://code.visualstudio.com/docs/getstarted/userinterface#_preview-mode ),but it is possible that it could be confusing for other users. There was issue requesting this - #767 . Maybe I will consider to add setting to disable tab preview mode
> 
> <img alt="image" width="345" src="https://private-user-images.githubusercontent.com/2543891/396010880-1ac967fb-670b-42e8-838f-0d8e0c4e42c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTM3NzgsIm5iZiI6MTczNDQ1MzQ3OCwicGF0aCI6Ii8yNTQzODkxLzM5NjAxMDg4MC0xYWM5NjdmYi02NzBiLTQyZTgtODM4Zi0wZDhlMGM0ZTQyYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTdUMTYzNzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg5ZjFmMzIxMTcxMWIwNjU4YzNiZGM2ZWJjNTk5MzJjZmFkZTk4Yzk3NDZlNDU4YjU4NDFkOWI0ZDdkNGJiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UOcnpXgH0aKy5qjyBDYLqWXwE2Y0lQA57_UgxsM7bEo">

WOW! I didn't even know this was an option to right-click on a table to open it in a new tab. You might want to consider updating your documentation.

Also, the option added to the Settings would help speed up our work instead of adding extra clicks to access a new table tab.
