### ISSUE TITLE
Import from CSV/XLS creates invalid column name 

### ISSUE THREAD

**Issue by mastras23** [dbgate/dbgate#966]
Importing tables from a csv or xls file where there are whitespaces between teh fields results in column names starting with whitespaces. 
The result is that you then don't know why a simple SELECT shows errors, you need to put the space and the rest of the name in brackets like [ ColumnName].
the suggestion is to add a TRIM function on the results of the line split by separators

[M1_PJP1_2024.csv](https://github.com/user-attachments/files/18166921/M1_PJP1_2024.csv)

**Comment by janproch** [comment]
I tried to import your file into MS SQL database, column names are correctly trimmed

Could you please share the script (under the "Generate script" button)

My script lookgs like following:
```js
// @require dbgate-plugin-csv
// @require dbgate-plugin-mssql

const var1 = await dbgatePluginCsv.shellApi.reader({"fileName":"C:\\Users\\prochazka\\.dbgate\\uploads\\4268965f-bf94-4ead-8e70-cf4cd6d42bb5"});
const var2 = await dbgateApi.tableWriter({"connection":{"server":"XXX","engine":"mssql@dbgate-plugin-mssql","user":"ZZZ","password":"YYY","passwordMode":"saveRaw","database":"test"},"pureName":"M1_PJP1_2024","createIfNotExists":true});
await dbgateApi.copyStream(var1, var2);

```

**Comment by janproch** [comment]
left-trim was added into CSV importer 3 months ago
