### ISSUE TITLE
BUG: Typo of electron (eletron) flag in package.json

### ISSUE THREAD

**Issue by LinusU** [dbgate/dbgate#97]
**Describe the bug**
When running `npm run fillNativeModulesElectron` the flag to `fillNativeModules` gets passed as `--eletron`, but the code in `fillNativeModules` looks for `--electron`.

https://github.com/dbgate/dbgate/blob/64af838f403915b1d2490a1a10fc4b798faa3b77/package.json#L34

https://github.com/dbgate/dbgate/blob/64af838f403915b1d2490a1a10fc4b798faa3b77/fillNativeModules.js#L20

**To Reproduce**
n/a

**Expected behavior**
n/a

**Screenshots**
n/a

**Version Information (please complete the following information):**
 - OS: all
 - App Version: `master`
 - Install source: n/a
 - Type - n/a
 - Database engine: n/a

**Additional context**
I just happened to find this while browsing thru the package.json, so I don't know what the effects of the typo is.

**Comment by janproch** [comment]
Thanks, it is because of bundle size and speed optimalization, which didn't work because of this typo

**Comment by janproch** [comment]
fixed in version 4.1.10
