### ISSUE TITLE
BUG Postgres.  Export to file doesn't work

### ISSUE THREAD

**Issue by ERPBOXUA** [dbgate/dbgate#970]
DBGate 6.1 /Ubuntu 22.4

No errors messages. Export result is empty file (CSV/XML) or nothing (XLS).

Case try import from remote DB to local DB:
{
  "time": 1734685153722,
  "pid": 66247,
  "caller": "apiIndex",
  "name": "script",
  "errorMessage": "options is not defined",
  "errorObject": {},
  "errorStack": "ReferenceError: options is not defined\n    at Query.<anonymous> (/snap/dbgate/522/resources/app.asar/packages/plugins/dbgate-plugin-postgres/dist/backend.js:2:86301)\n    at Query.emit (node:events:518:28)\n    at Query.handleDataRow (/snap/dbgate/522/resources/app.asar/node_modules/pg/lib/query.js:96:10)\n    at Client._handleDataRow (/snap/dbgate/522/resources/app.asar/node_modules/pg/lib/client.js:366:22)\n    at Connection.emit (node:events:518:28)\n    at /snap/dbgate/522/resources/app.asar/node_modules/pg/lib/connection.js:116:12\n    at Parser.parse (/snap/dbgate/522/resources/app.asar/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/snap/dbgate/522/resources/app.asar/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:559:12)",
  "message": "Uncaught exception, exiting process",
  "severity": "error"
}

**Comment by janproch** [comment]
Thanks, good catch

Apparently, beside bug there was a missing test on PostgreSQL export

**Comment by janproch** [comment]
fixed in 6.1.2
