### ISSUE TITLE
QUESTION: How do I download the M processor version for mac osx?

### ISSUE THREAD

**Issue by homerokzam** [dbgate/dbgate#971]
**Details:**
On the website, the link 'https://github.com/dbgate/dbgate/releases/download/v6.1.1/dbgate-premium-latest-arm64.dmg' doesn't work!

**Version Information [might be relevant to your issue]**
Operating System: mac osx (M2)
App Version [help -> about]:

**Comment by janproch** [comment]
Download link fixed, thanks
